### ISSUE TITLE
Visibility option when using the app

### ISSUE THREAD

**Issue by ygreen21** [OfficeDev/microsoft-teams-apps-requestateam#10]
I have added the app to my team but it isn't working correctly:-
I click to create a team from scratch and I am asked for the privacy setting, Team Name and Description. Once completed the Next button doesn't become clickable. After clicking check availability I get an error in the top panel 

CheckTeamAvailability.Run failed: { "error": { "code": 502, "source": "europe-001.azure-apim.net", "clientRequestId": "c64641e0-085f-4ce0-b598-5c8f2949ff11", "message": "BadGateway", "innerError": { "error": { "code": "NoResponse", "message": "The server did not received a response from an upstream server. Request tracking id '08586128545305279791333618999CU67'." } } } }

I chose the Location as australiaeast in the initial script as we are in NZ but this isnt where my tenant resides

I did find the deployment a bit menacing

Many thanks
Yvonne

**Comment by lkanala** [comment]
The app is designed in a way that you can only move forward when user clicks on Check Availability and Team Name is available. Did you replaced the SharePoint site URL with your SharePoint site in 'Check Team Availability' flow. Which you can see my navigating to My flows. It needs to be replaced at two points as per deployment guide.

**Comment by ygreen21** [comment]
Yes I did ... I followed the deployment guide to the letter

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lkanala** [comment]
Can you check the Check Team Availability run history, is it running or failed. If you can see history, click on it, see at what step it failed.

**Comment by ygreen21** [comment]
Thank you. I had accidentally put a 2 in the tenant name so all is working now except I dont get the approval adaptive card and get the following error in the Flow action 'Post_an_Adaptive_Card_to_a_Teams_channel_and_wait_for_a_response' failed

Error
The request failed. Error code: 'BotRequestFailed'. Error Message: 'Request to the Bot framework failed with error: '{"error":{"code":"ConversationNotFound","message":"Conversation not found."}}'.'.

**Comment by pdanbury-cisilion** [comment]
> Thank you. I had accidentally put a 2 in the tenant name so all is working now except I dont get the approval adaptive card and get the following error in the Flow action 'Post_an_Adaptive_Card_to_a_Teams_channel_and_wait_for_a_response' failed
> 
> Error
> The request failed. Error code: 'BotRequestFailed'. Error Message: 'Request to the Bot framework failed with error: '{"error":{"code":"ConversationNotFound","message":"Conversation not found."}}'.'.

I have the very same issue...Would love to know if there is a resolution.

**Comment by lkanala** [comment]
@ygreen21 @pdanbury-cisilion In that step we are providing groupId and ChannelId of the team where we want to post the adaptive card. Can you check that the groupId(TeamId) and ChannelId values inside Team Request Settings SharePoint list. 10th to 12th point in the given link. If there is any confusion about replacing values in channelId follow the "tip" below point 10.
https://github.com/OfficeDev/microsoft-teams-apps-requestateam/wiki/Deployment-guide#step-2-create-admin-group

**Comment by alexc-MSFT** [comment]
Closing this issue due to lack of response.
