### ISSUE TITLE
Duplicate wiki tabs

### ISSUE THREAD

**Issue by shuenSL** [OfficeDev/microsoft-teams-apps-requestateam#100]
Using an existing team as a template, two wiki tabs are created in the provisioned team. Looks like a bug the cloning API. Are there plans to add code in the logic app to remove the extra non-functioning tab? Thanks.

**Comment by alexc-MSFT** [comment]
@shuenSL it is indeed a bug in the Graph API and I've no sight of when this will be fixed. I did think about adding code to fix the duplicate tabs so watch this space.

**Comment by alexc-MSFT** [comment]
@shuenSL we have a duplicate issue so I'm closing this one and will keep the other one open. #94
