### ISSUE TITLE
Failed to Create Three SPO Lists

### ISSUE THREAD

**Issue by CGHEX** [OfficeDev/microsoft-teams-apps-requestateam#105]
I got the message that the deployment completed successfully, but three (3) SharePoint lists are missing in the SharePoint site. What could be the reason and how can I resolve this?

**Comment by loflet** [comment]
Hi @CGHEX , did you face any issue or error when the script was running? If you have the log of that run can you check and confirm if there was an error while running the script?

Regards,
Sanket

**Comment by CGHEX** [comment]
Hi Sanket,

Before I did not see any error. I gave another try today and got the below error. Script was running under the context of a Global Admin account.
 
### REQUESTS SPO SITE CONFIGURATION ###
Configuring SharePoint site...
Applying provisioning template...
WARNING: The source site from which the template was generated had a base template ID value of GROUP#0, while the current target site has a base template ID value of TENA
NTADMIN#0. This could cause potential issues while applying the template.
Apply-PnPProvisioningTemplate : Access denied. You do not have permission to perform this action or access this resource.
At C:\Users\vipinair\Downloads\microsoft-teams-apps-requestateam-master\Deployment\Scripts\deploy.ps1:340 char:9
+         Apply-PnPProvisioningTemplate -Path (Join-Path $packageRootPa ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerUnauthorizedAccessException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Site.ApplyProvisioningTemplate
Applied template
Added settings to Site Requests Settings list
Added templates to Teams Templates list
Adding Service Account to Owners group
Finished configuring site
### AZURE RESOURCES DEPLOYMENT ###
Starting Azure resources deployment...
Creating resource group Collab-Solutions...

Regards,
Rohit

**Comment by CGHEX** [comment]
Script required the correct ManagedPath configured in the tenant as one of the parameter and this one got resolved after correcting the ManagedPath parameter from "sites" to "teams".

**Comment by loflet** [comment]
Glad to know the issue is resolved and thanks for sharing the solution.
