### ISSUE TITLE
UPN != PrimarySMTPAddress = MyRequests not usable

### ISSUE THREAD

**Issue by J-a-k-o-b** [OfficeDev/microsoft-teams-apps-requestateam#106]
Hi,
i´m implementing this solution for a customer where the UPN is not equal to his primary SMTPAddress (Yes, I know...). When users navigate to the "My Requests" screen the Collection used to display the Requests screen stays empty.
The Problem is that the Created By Column in SPO reflects the primarySMTP Adress. The PowerApps Function User().EMail seems to use the email address which is the same as the UPN. So there is a missmatch of the used email addresses. 
I´ve ended up by adding a new column "CreatedBy_Workaround" to the "Teams Requests" List which is filed with the btnnext_ Actions with the value of User().Email. 
Additionaly I adjusted the Filter in the OnVisible Action and the Refresh Button on the Screen to filter the Collection TeamsReqTable by the added column "CreatedBy_Workaround"

It works like expected. But i wonder if there is a more "elegant" way to ship around this issue.

**Comment by alexc-MSFT** [comment]
@J-a-k-o-b unfortunately this is a limitation in terms of the Power Apps and what it can retrieve from the User() object. It may be we could make this more elegant by adding a new option to the settings list but this isn't something we are planning on doing at the moment.

I think the solution you have come up with is the most sensible option at the moment. 

Thanks

**Comment by jocrabtree** [comment]
@J-a-k-o-b I'm having the same issue since my company decided that upn!=email way back when.

Any chance you can share screenshots of what you did in both SharePoint and PowerApps? I'd greatly appreciate it.

**Comment by J-a-k-o-b** [comment]
Hi @jocrabtree,
I will try to summarize it and share it here or via teams/chat with you,

**Comment by jocrabtree** [comment]
@J-a-k-o-b Thanks so much. Whatever is easier for you works for me.

**Comment by J-a-k-o-b** [comment]
Hi @jocrabtree,
we´re using the templates section of the app only, so we´re redesigned the App etc a bit. But in general you will find the same names i have listed in the screenshots in the default app, or you can recycle the procedure
1. Add additional Column to the SPO List "Teams Request". In my Case "CreatedBy_Workaround":
![image](https://user-images.githubusercontent.com/46894290/91530218-0a9a0700-e90b-11ea-8137-9ba6d55a7e0e.png)

**Comment by J-a-k-o-b** [comment]
Hi @jocrabtree ,
we´re using the templates section of the app only, so we´re redesigned the App etc a bit. But in general you will find the similar names that were shown in the screenshots in the default app. You can recycle the methods, in the other screens and functions of the app.

1. SPO:  Add additional Column to the SPO List "Teams Request". In my Case "CreatedBy_Workaround":
![image](https://user-images.githubusercontent.com/46894290/91530218-0a9a0700-e90b-11ea-8137-9ba6d55a7e0e.png)
2. PA: Edit the patch SPO List Procedure in the btnNext_TeamInformation Button in the screen scrnUseTemplate:
![image](https://user-images.githubusercontent.com/46894290/91531106-8779b080-e90c-11ea-8f9f-68b0f896982f.png)
add the Value:
`.{CreatedByWorkaround:User().Email}`
to the Patch command. (Don´t forget to refresh the connection to the database before to have the newly created column available)
3. PA: Edit the btmRefresh_MyRequests in the screen scrnMyRequests:
![image](https://user-images.githubusercontent.com/46894290/91531788-a75da400-e90d-11ea-9e23-3a131a53cebc.png)
Adjust the Filter to
`('Teams Request',CreatedBy_Workaround=gblUser)`
4. PA: Edit the Onvisible Action for Screen scrnMyRequests:
![image](https://user-images.githubusercontent.com/46894290/91533117-a62d7680-e90f-11ea-8be1-758dd557173c.png)
Edit the ClearCollect Filter to
`('Teams Request',CreatedBy_Workaround=gblUser)`

We don´t use the clone action in the MyRequests Settings. It might be that you also have to add the Step 2 to further Buttons on the other screens if you use more than the Templates.

**Comment by jocrabtree** [comment]
@J-a-k-o-b Thanks so much for your help. It's working partially now. 

When I create a request, it doesn't display when I hit the 'refresh' button. I have to exit the app and then come back and click on the 'My Requests' tab for any of my requests to show. After I click out of the 'My Requests' tab all of the requests I have disappear again until I leave the app and come back. Kinda weird and was hoping the 'Refresh' button would work better, but I'm def getting closer.

I'm guessing your 'Refresh' button works and you don't have to complete exit the app to see any requests? Anything else you may recommend trying? I appreciate your feedback.

**Comment by J-a-k-o-b** [comment]
So the scrnMyRequests workd like expected, except the refresh Button?
We don´t experience that issue. Maybe you can compare the ClearCollect function in my Steps 3&4. They are configured the same.

**Comment by jocrabtree** [comment]
@J-a-k-o-b Thanks again for the help. I checked what I had for Step #3 & #4 that you listed above. Both appear to be identical. I noticed on Step #2 that you have a section above the 'if' statement that begins with 'patch.' I do not have that those two lines of code. Is that something I should add? Here's what I have:

![image](https://user-images.githubusercontent.com/51301604/91882806-21ad6180-ec49-11ea-8a78-bad7a6a1bbd9.png)

**Comment by J-a-k-o-b** [comment]
Hi @jocrabtree,
we have this first Patch Method here because we´re skipping the Privacy Site. It shouldn´t be related here.
Do you know the possibility to monitor the app:
![image](https://user-images.githubusercontent.com/46894290/91883540-de70e400-ec84-11ea-841b-646abebb3c61.png)
![image](https://user-images.githubusercontent.com/46894290/91883659-08c2a180-ec85-11ea-8c43-8084bbced14e.png)

You can use this tool to see what happens if you click on the Buttons and so on. Maybe you can find the issue with the help of this.

**Comment by jocrabtree** [comment]
@J-a-k-o-b - Thanks again. Here's what I'm seeing:

When I initially open the app and click on the 'My Requests' tab it shows all of my requests:
![image](https://user-images.githubusercontent.com/51301604/91894462-575b4600-ec5b-11ea-9ac2-eeecbacc30cb.png)

I turned on Monitoring, and I noticed these lines when I clicked on the 'My Requests' tab:
![image](https://user-images.githubusercontent.com/51301604/91894561-807bd680-ec5b-11ea-9c8a-ae9edc4eed18.png)

Here's the details on one of those two warning lines:
![image](https://user-images.githubusercontent.com/51301604/91894652-a5704980-ec5b-11ea-8666-60fa66913453.png)

When I click on the 'Request a Team' tab after the 'My Requests' tab, it opens just fine. However, once I click on the 'My Requests' tab again it shows nothing:
![image](https://user-images.githubusercontent.com/51301604/91894796-d81a4200-ec5b-11ea-9b7a-89524296fa05.png)

I checked the 'Monitoring' page and see this:
![image](https://user-images.githubusercontent.com/51301604/91895005-24658200-ec5c-11ea-817a-09e8640eec07.png)

I see there is a line with '0 rows collected' so I'm guessing that's my issue, somehow? Here's the details for the '0 rows collected' line:
![image](https://user-images.githubusercontent.com/51301604/91895165-65f62d00-ec5c-11ea-855a-5d0d644ac0fc.png)

**Comment by jocrabtree** [comment]
@J-a-k-o-b Oh, forgot to mention the 'Refresh' button on the 'My Requests' page too. Here's what I see when I monitor clicking the 'Refresh' button (I clicked it four separate times, btw):
![image](https://user-images.githubusercontent.com/51301604/91897067-5c21f900-ec5f-11ea-92e2-b2bedb3072c6.png)

**Comment by J-a-k-o-b** [comment]
Hi @jocrabtree,
sorry, I dont have a valuable hint here. Maybe you can ask this question in a new topic here, because it not seems to be related to the adjustments we made.

**Comment by jocrabtree** [comment]
@J-a-k-o-b Will do. Thanks so much for all the help you provided. 💯

**Comment by tomfeather** [comment]
Hi All,

I've also just found this exact issue in our enviroment and I think I've got a more elegant solution.

I replaced all occurences in the Power App of:
`Set(gblUser,User().Email); `

with:
`Set(gblUser,Office365Users.MyProfileV2().mail);`

This gets the user's primary email address instead of thier UPN

I've just tested this with an affected user and they can now see all the requests in the "My requests section"

I've not found any issues with this so far but can you see any reason why this might be a bad idea?

Thanks

**Comment by J-a-k-o-b** [comment]
Hi @tomfeather,
that looks much easier than my workaround. I will try out your solution the next time I have to deal with it.
