### ISSUE TITLE
Error Creating role assignments

### ISSUE THREAD

**Issue by mcasaz** [OfficeDev/microsoft-teams-apps-requestateam#109]
the deployment completes successfully and all other tasks are successful too but this one fails, Any suggestion what I need to change? I am using an account that is Global admin and has all licenses and a mailbox

Creating role assignments
New-AzRoleAssignment : The client 'admin.mc@xxxx.com' with object id '9071b6d0-d2d6-4be6-bc6f-1f4ed44d675e' does not have authorization to perform action
'Microsoft.Authorization/roleAssignments/write' over scope '/subscriptions/16c1d1b2-xxxxxxxxxxxxxxx-4090fe93472e/resourceGroups/weu-t-RequestATeam-rg/providers/Microsoft.Automation
/automationAccounts/teamsautomate-auto/providers/Microsoft.Authorization/roleAssignments/1e87c318-ad20-41dd-87da-cfb3803d1e01' or the scope is invalid. If access was recently
granted, please refresh your credentials.
At C:\Users\Foobar\Downloads\microsoft-teams-apps-requestateam-master\Deployment\Scripts\deploy.ps1:618 char:9
+         New-AzRoleAssignment -ObjectId $global:appServicePrincipalId  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzRoleAssignment], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureRoleAssignmentCommand

New-AzRoleAssignment : The client 'admin.mc@xxxx.com' with object id '9071b6d0-d2d6-4be6-bc6f-1f4ed44d675e' does not have authorization to perform action
'Microsoft.Authorization/roleAssignments/write' over scope '/subscriptions/16c1d1b2-xxxxxxxxxxxxxx-4090fe93472e/resourceGroups/weu-t-RequestATeam-rg/providers/Microsoft.Automation
/automationAccounts/teamsautomate-auto/providers/Microsoft.Authorization/roleAssignments/897dd8d3-a6f3-4118-83d4-8f08f438d4b5' or the scope is invalid. If access was recently
granted, please refresh your credentials.
At C:\Users\Foobar\Downloads\microsoft-teams-apps-requestateam-master\Deployment\Scripts\deploy.ps1:619 char:9
+         New-AzRoleAssignment -ObjectId $global:appServicePrincipalId  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzRoleAssignment], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureRoleAssignmentCommand

![2020-08-05_16-38-14](https://user-images.githubusercontent.com/33139177/89426376-66250a80-d73a-11ea-8ab9-e1ad38a46b93.jpg)

**Comment by marcinciezak** [comment]
My deployment fails on the same step, although with different error:

PS D:\DevProjects\PowerApps\RequestTeamApp\Deployment\Scripts> New-AzRoleAssignment -ObjectId $global:appServicePrincipalId -RoleDefinitionName "Automation Job Operator" -ResourceName $automationAccountName -ResourceType "Microsoft.Automation/automationAccounts" -ResourceGroupName $ResourceGroupName
New-AzRoleAssignment : **Input string was not in a correct format.**
At line:1 char:1
+ New-AzRoleAssignment -ObjectId $global:appServicePrincipalId -RoleDef ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzRoleAssignment], FormatException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureRoleAssignmentCommand

However, error mentioned by @mcasaz shows up in the actual logic app:
![image](https://user-images.githubusercontent.com/13286170/89500861-a92ac080-d7c2-11ea-8145-e22fe91ef332.png)

**Comment by Humpeklumpen** [comment]
I have the same issues, Input string was not in a correct format.

**Comment by mcasaz** [comment]
> @mcasaz @Humpeklumpen can you let me know what permissions the account running the script/the account you are signing into at the popups has please?

@alexc-MSFT I mentioned in my post I am using a Global Admin. Would that answer your question?

**Comment by Humpeklumpen** [comment]
@alexc-MSFT  The same, im using Global admin

**Comment by Lysakers** [comment]
I am getting the same error "not in a correct format" error.
Running the script as global admin with owner rights to the subscription.

**Comment by Lysakers** [comment]
Did some research myself and found a referance to the New-AzRoleAssignment cmdlet was failing with Az.Resources version 2.5.0.
By downgrading to 2.3.0 it worked without errors.

**Comment by mcasaz** [comment]
@alexc-MSFT why has this been labelled as "invalid"?

**Comment by mcasaz** [comment]
I have done all the configuration till the end and tested the app. The request in PowerApps and Flow go through but I do get the same error in Logic App when trying to create an Azure job

![image](https://user-images.githubusercontent.com/33139177/93765106-a4a45500-fc14-11ea-8960-8b3ae0b33440.png)

"The client 'b93ba0bf-98ad-4be1-8862-a83ebe741cb9' with object id 'b93ba0bf-98ad-4be1-8862-a83ebe741cb9' 
does not have authorization to perform action 'Microsoft.Automation/automationAccounts/jobs/write' over scope 
'/subscriptions/xxxxxxxxxxxxxxxxxxxxx/resourceGroups/weu-t-RequestATeam-rg/providers/Microsoft.Automation/automationAccounts/teamsautomate-auto/jobs/1e72313e-1004-4eb4-b656-4e96d63e70fc' 
or the scope is invalid. If access was recently granted, please refresh your credentials."

@Lysakers how did you actually solve the issue? Did you redeploy?

**Comment by Lysakers** [comment]
@mcasaz I uninstalled the Az.Resources module then reinstalled version 2.3.0 of it.
Instead of redeploying i just picked apart the deployment script and ran the few lines of code needed to grant premissions.

Though i imagine if you go to your automation account and add the Logic app with the correct permissions that should solve the error you are seeing:
![bilde](https://user-images.githubusercontent.com/25911660/94359046-20831f00-00a5-11eb-83c9-1f79e7003a00.png)

**Comment by alexc-MSFT** [comment]
Thanks @Lysakers @marcinciezak for flagging this up, the runbook is shortly going to be removed and replaced with a Logic App so I'm going to hold off updating the deployment script for now. Will keep this issue open until the new code is commited.

**Comment by alexc-MSFT** [comment]
Closing this issue as the implementation of a new logic app negates the need for automation and therefore this issue is no longer there.
