### ISSUE TITLE
Similar project on PnP

### ISSUE THREAD

**Issue by pkbullock** [OfficeDev/microsoft-teams-apps-requestateam#11]
Hi

Thought make you aware, there is a similar project on PnP for provisioning - https://github.com/pnp/tutorial-workspace-provisioning

Whilst there are clear differences, there maybe some learning with these contributors that might help stabilize the solution.

**Comment by alexc-MSFT** [comment]
> Hi
> 
> Thought make you aware, there is a similar project on PnP for provisioning - https://github.com/pnp/tutorial-workspace-provisioning
> 
> Whilst there are clear differences, there maybe some learning with these contributors that might help stabilize the solution.

Thanks for the link, we will have a look. If you have any specific issues deploying this specific solution then please raise them. We are currently working on updates to the deployment documenation.

Thanks
