### ISSUE TITLE
Is there a way to make the first Owner combo box value equal to the requestor/logged in user

### ISSUE THREAD

**Issue by ARAlmac** [OfficeDev/microsoft-teams-apps-requestateam#110]
Hi I am wondering if there is a way to make the first combo box equal to the requestor/user logged in as this would be default. I have tried using User().Email in the default and defaultselecteditems property of the combo box but it is giving me an error of "Expected Row" and "Expected Table" values.

Any help would be great thanks!

**Comment by loflet** [comment]
Hi @ARAlmac, yes it is possible to set the default value to the combo box. Follow the steps to set the default value: -

1. Click on the first combo box.
2. From the property pane select "DefaultSelectedItems" and set the value of that to - **Office365Users.UserProfile(User().Email)**

That should do the work. Screenshot for reference.
![image](https://user-images.githubusercontent.com/7891707/89804312-a1b44000-db51-11ea-9e74-afc37c90931e.png)

Regards,
Sanket

**Comment by ARAlmac** [comment]
Hi @loflet,

Thanks for this reply, it works in terms of actually populating that box with the user's email!

However, when i hit next to the summary screen, the owners and members are now not coming across and i am getting a runtime error of : 
![image](https://user-images.githubusercontent.com/32670540/89877980-d0193600-dbb8-11ea-8ac1-52163b4a2ed0.png)

However, when i go back and x out the default users email and select it from the options then it works fine.

Could you test out and see if it carries across to the submit screen for you with default selection? 

or any ideas about the error?

Appreciate the help :)

**Comment by loflet** [comment]
Hi @ARAlmac, yes you are correct I am also facing issue to move ahead. I will spend some time probably on the weekend to see if the default entry can be mapped to the combo box. Will let you know once I have some update on this.

**Comment by loflet** [comment]
Hi @ARAlmac, I was able to fix this. You will have to make the following further changes on the cmbOwners. control and change the value of the DefaultSelectedItems to this: -

```
Table({
        '@odata.type':"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedUser",
        Claims:Concatenate("i:0#.f|membership|",'cmbOwners._2'.Selected.Email),
        Department:'cmbOwners._2'.Selected.Department,
        DisplayName:'cmbOwners._2'.Selected.DisplayName,
        Email:'cmbOwners._2'.Selected.Email,
        JobTitle:'cmbOwners._2'.Selected.JobTitle,
        Picture:""
},{
        @odata.type':"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedUser",
        Claims:Concatenate("i:0#.f|membership|",User().Email),
        Department:'cmbOwners._1'.Selected.Department,
        DisplayName:'cmbOwners._1'.Selected.DisplayName,
        Email:User().Email,
        JobTitle:'cmbOwners._1'.Selected.JobTitle,
        Picture:""
})
```

![image](https://user-images.githubusercontent.com/7891707/90421204-a8553100-e0d6-11ea-8f85-a046b204e12f.png)

Can you try this and let me know if this works for you?

Regards,
Sanket

**Comment by loflet** [comment]
@ARAlmac, have you tried the solution which I mentioned?

**Comment by ARAlmac** [comment]
Hi @loflet,

apologies forgot to reply to you! Yes i have tried this and it works perfectly! Thanks so much

**Comment by loflet** [comment]
Glad to know it worked @ARAlmac.

@alexc-MSFT you can close this issue.

**Comment by alexc-MSFT** [comment]
Thanks all - closing
