### ISSUE TITLE
Unable to select visibility

### ISSUE THREAD

**Issue by JamesMil** [OfficeDev/microsoft-teams-apps-requestateam#111]
Unable to select visibility as seen below, please advise
![Issue 1](https://user-images.githubusercontent.com/69344581/89628069-a946c100-d893-11ea-8658-af049956babf.png)
![Issue 2](https://user-images.githubusercontent.com/69344581/89628076-ac41b180-d893-11ea-8590-b5549a212fec.png)

**Comment by ARAlmac** [comment]
@JamesMil ensure the user has been added to the Sharepoint site. On my demo the other day this happened and this was the fix for me.

**Comment by JamesMil** [comment]
> @JamesMil ensure the user has been added to the Sharepoint site. On my demo the other day this happened and this was the fix for me.

The user has access to the SharePoint site, any other ideas?

**Comment by SPDan** [comment]
@JamesMil I had same problem. Solution was to refresh all SPO data sources again, save and publish new app version. Hope it'll work :)

**Comment by alexc-MSFT** [comment]
@JamesMil as above, either the SPO data sources have not been removed and re-added or the user does not have access to the SharePoint site.

**Comment by JamesMil** [comment]
@alexc-MSFT @SPDan 

Can you confirm how to refresh the data sources?

**Comment by JamesMil** [comment]
Resolved by removing and re-adding the data sources 👍
