### ISSUE TITLE
Multiple Errors

### ISSUE THREAD

**Issue by gbuzue** [OfficeDev/microsoft-teams-apps-requestateam#112]
There were soo many issues wit the deployment which i think it was the initial ones that led to the excess errors. 
I had initial two errors 
pnp provisioning 403 error
unable to convert key vault secret value

The automation got created and ran successfully but for some reason it couldn't import and publish the runbook
api connections and logic app gave a error

The final error was the role assignments  which led to a numerous hosts of errors.

![image](https://user-images.githubusercontent.com/56828665/89727830-9850a800-da6b-11ea-895a-48fe695113f7.png)
![image](https://user-images.githubusercontent.com/56828665/89727834-9d155c00-da6b-11ea-9e82-efc21fb06492.png)
![image](https://user-images.githubusercontent.com/56828665/89727838-a30b3d00-da6b-11ea-89ca-1d2a3a5c93b9.png)
![image](https://user-images.githubusercontent.com/56828665/89727840-a69ec400-da6b-11ea-97a8-a78fe9fe6aa1.png)
My parameters used
![image](https://user-images.githubusercontent.com/56828665/89727886-01d0b680-da6c-11ea-96c1-b65a249d92ff.png)

**Comment by loflet** [comment]
Hi @gbuzue, yes you are correct the initial error might have caused other error. But, I can also see the error where it is not able to find the files. Can you make sure you have cloned the repository properly, having all files in place? The best way to solve this will be to re-run the deployment script following all the deployment steps from the start. It might be possible that some step is missed? 

Regards,
Sanket

**Comment by alexc-MSFT** [comment]
@gbuzue please can you go into Azure AD and delete the azure ad app manually and any old ones that you may have used when running the script and re-run please.

Thanks

**Comment by bouncethebox** [comment]
I received this a couple times and I deleted the automation account teamsautomate-auto and it ran fine afterwards.

**Comment by alexc-MSFT** [comment]
@gbuzue please try @bouncethebox 's suggestion, you shouldn't have to delete the automation account but let's give it a go.

**Comment by alexc-MSFT** [comment]
Closed due to inactivity - reopen if required
