### ISSUE TITLE
Team Creation Issue

### ISSUE THREAD

**Issue by JamesMil** [OfficeDev/microsoft-teams-apps-requestateam#114]
Team requested and approved but stuck on creation without the team created

![Issue](https://user-images.githubusercontent.com/69344581/89785235-fcc64280-db11-11ea-8a4c-efad09aeea91.png)

**Comment by loflet** [comment]
Hi @JamesMil, can you provide more information such as what is it showing on the logic app run log? You can check that by visiting portal.azure.com and navigating to your resource which was deployed using the script. 

It is possible that the team creation failed and the error is not logged back in the SharePoint. Please check your connections are properly set in the logic app or not. Feel free to reply back with more information.

Regards,
Sanket

**Comment by JamesMil** [comment]
@loflet Looking at the logic app run log, i have seen the following:

Get Client ID - failed

{
  "status": 404,
  "message": "Operation failed because the requested resource was not found in the key vault.\r\nclientRequestId: d173eceb-0feb-412b-b7ff-eff86656a28e",
  "error": {
    "message": "Operation failed because the requested resource was not found in the key vault."
  },
  "source": "keyvault-uks.logic-ase-uksouth.p.azurewebsites.net"
}
![Issue](https://user-images.githubusercontent.com/69344581/89796152-2c307b80-db21-11ea-80ad-fd200d0fa061.png)

**Comment by loflet** [comment]
It seems that the Azure Keyvault does not have your Client Id and secret. Can you check in your deployed resources if you can see the keyvault like this (name will be different in your case)
![image](https://user-images.githubusercontent.com/7891707/89802082-9f9cb200-db4e-11ea-820f-39a025452cf0.png)

Once you see your keyvault then navigate to the key vault and Click on secrets to see if you can see the secrets there like this 
![image](https://user-images.githubusercontent.com/7891707/89802279-f30f0000-db4e-11ea-90cf-22b0ba2d6517.png)

I am assuming that your keyvault doesn't have that secret. This might have happened during some issue while running the deployment script.

Regards,
Sanket

**Comment by alexc-MSFT** [comment]
@JamesMil as @loflet says above, it looks like your key vault does not have those secrets. Did you get any errors when running the deployment script?

**Comment by JamesMil** [comment]
@loflet @alexc-MSFT 

Secrets isn't seen as shown:
![Secrets](https://user-images.githubusercontent.com/69344581/89906989-f86a5a00-dbe3-11ea-8683-b0cdbf0e78a5.png)

Deployment was successful, no error messages:
![Complete](https://user-images.githubusercontent.com/69344581/89907019-04eeb280-dbe4-11ea-9594-2c5af7344108.png)

Shall i re-run the deployment?

**Comment by loflet** [comment]
Hi @JamesMil, there are two ways to solve this: -
1. You can re-run the complete script and that should fix it.
2. Manually add the key in the keyvault. Click on +Add in the keyvault secret and create a key named **appid** and simillarly create another key named **appsecret**. Value of these can be found in your AD app (https://aad.portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredApps). Search for the AD app which was created by this script.

If you are not familiar with 2nd step then I will recommend you to re-run the deployment script and make sure there isn't any error thrown throughout the deployment.

Regards,
Sanket

**Comment by JamesMil** [comment]
Manually created the keyvault but getting this error:

{
  "status": 404,
  "message": "Operation failed because the requested resource was not found in the key vault.\r\nclientRequestId: 4825644f-e0eb-4eca-a5d7-24751f6a6b7c",
  "error": {
    "message": "Operation failed because the requested resource was not found in the key vault."
  },
  "source": "keyvault-uks.logic-ase-uksouth.p.azurewebsites.net"
}

**Comment by loflet** [comment]
@JamesMil, I think there are some other areas where the keyvault is not binded properly. In this scenario the quickest fix will be to re-run the deployment. Can you try that?

**Comment by JamesMil** [comment]
@loflet it fails to run as a keyvault is detected

**Comment by loflet** [comment]
@JamesMil, since the keyvault already exist does it not ask you if you want to re-use again? If keyvault exist then it will show a message like this - **Key Vault already exists in this Azure subscription. Do you wish to use it?**

Or did you manually delete the already created keyvault from your Azure resources?

**Comment by alexc-MSFT** [comment]
@JamesMil please can you re-rung the script and specify a different name for the keyvault. In a previous deployment before this app was released I also used 'teamsautomate-kv', this should have been deleted from my subscription a long time ago but I wonder if there is some kind of strange conflict.

Let me know how you get on.

**Comment by JamesMil** [comment]
@loflet @alexc-MSFT, Re-ran the script and it's alot further down the process but now stuck here
![Issue](https://user-images.githubusercontent.com/69344581/90126357-72711f00-dd5b-11ea-94db-e36341d5388f.png)

**Comment by SanderDeVos** [comment]
Also getting the same BadRequest from the Create group action in the Logic App.

**Comment by alexc-MSFT** [comment]
@JamesMil @SanderDeVos  can you view the raw output of the action please and let me know what this states? As this should give more details as to what the error is.

**Comment by JamesMil** [comment]
@alexc-MSFT 

raw output:
{
    "statusCode": 400,
    "headers": {
        "request-id": "1ca8ee77-9d16-4248-9537-4e7a2c1695db",
        "client-request-id": "1ca8ee77-9d16-4248-9537-4e7a2c1695db",
        "x-ms-ags-diagnostic": "{\"ServerInfo\":{\"DataCenter\":\"UK South\",\"Slice\":\"SliceC\",\"Ring\":\"4\",\"ScaleUnit\":\"001\",\"RoleInstance\":\"AGSFE_IN_3\"}}",
        "Strict-Transport-Security": "max-age=31536000",
        "Cache-Control": "private",
        "Date": "Mon, 17 Aug 2020 09:06:14 GMT",
        "Content-Length": "663",
        "Content-Type": "application/json"
    },
    "body": {
        "error": {
            "code": "Request_BadRequest",
            "message": "Object '[ResourceType=User,Id=0429328e-4545-4750-b6b4-c3c8715590b5,ChangedProperties=[],NonDefaultProperties=[INTERNAL_SingleResourceQuery]]' referenced from '[ResourceType=Group,Id=7e893b74-669d-43c7-b215-25dd1a11db79,ChangedProperties=[DisplayName,Description,GroupType,MailEnabled,MailNickname,SecurityEnabled,IsPublic,CreatedByAppId],NonDefaultProperties=[INTERNAL_EnableF14M1SchemaEnumTypes,visibility]]' can only be present once as an add/remove change.",
            "innerError": {
                "date": "2020-08-17T09:06:15",
                "request-id": "1ca8ee77-9d16-4248-9537-4e7a2c1695db"
            }
        }
    }
}

**Comment by loflet** [comment]
Hi @JamesMil, did you add the **service account user** which you used while running the script as a member or owner of the new team that was requested?

**Comment by JamesMil** [comment]
@loflet Thank you for the quick reply this has resolved the issue
