### ISSUE TITLE
Flow issue

### ISSUE THREAD

**Issue by AlanPutt** [OfficeDev/microsoft-teams-apps-requestateam#117]
Hi

I'm having an issue with the Team Request Approval flow.  The connected account is an owner of the Admin Team Chanel where the Adaptive Card should go. But I'm receiving an Unauthorized error: 

![image](https://user-images.githubusercontent.com/69569836/89981126-ad6d4700-dcb6-11ea-9d29-c411f97eac8c.png)

Hope you can help!

Thank

**Comment by loflet** [comment]
Hi @AlanPutt, this is strange. If the connected account (let's call it "Alan") is the owner of the **admin team channel** then this should have worked. Can you once check two things:-
1. if the variables "TeamId" and "ChannelID" are correctly populated with your team and channel id? 
2. if the teams action is using the correct connection ("Alan's" connection)? 

If both the points work for you then can you try to create a new connection (with "Alan's" connection) for that flow action and see if it works?

**Comment by AlanPutt** [comment]
Thanks for the suggestions.

After adding the TeamID and ChannelID the process worked!

Thanks again

A

**Comment by alexc-MSFT** [comment]
Excellent - will close this issue now
