### ISSUE TITLE
Office365GroupsListGroupMembers failed

### ISSUE THREAD

**Issue by bouncethebox** [OfficeDev/microsoft-teams-apps-requestateam#119]
Aright, I didn't get this last deployment; what did I miss?  Any help appreciate, and thanks!
![error](https://user-images.githubusercontent.com/10575421/90084767-436b9680-dce4-11ea-8875-6ea8eb807c4f.png)

**Comment by bouncethebox** [comment]
[ [ RESOLVED ] ] Didn't publish after changing to the group ID.     ¯\_(ツ)_/¯

**Comment by alexc-MSFT** [comment]
Great to hear you have it resolved.
