### ISSUE TITLE
Is it possible to disable the approval process?

### ISSUE THREAD

**Issue by bouncethebox** [OfficeDev/microsoft-teams-apps-requestateam#120]
Is it possible to bypass or disable the approval process so the request is submitted and sent right to provisioning?

**Comment by alexc-MSFT** [comment]
@bouncethebox yes, the easiest way to do this would be simply to disable the Flow and set the status of the request directly to 'Approved' within the Power App.

**Comment by alexc-MSFT** [comment]
Closing

**Comment by bouncethebox** [comment]
Where would I set that status to approved?
