### ISSUE TITLE
Teams requests site creation error

### ISSUE THREAD

**Issue by rferazzi** [OfficeDev/microsoft-teams-apps-requestateam#125]
During the installation script I receive this error:
![image](https://user-images.githubusercontent.com/25500425/90398999-8b9b0800-e09a-11ea-8107-4f83f9ba6db2.png)

![image](https://user-images.githubusercontent.com/25500425/90399278-0106d880-e09b-11ea-8a2b-1de2dce1c3c5.png)

I tried on different tenants and from different PCs

**Comment by alexc-MSFT** [comment]
@rferazzi  sadly it looks like this is an issue with PnP PowerShell - https://github.com/pnp/PnP-PowerShell/issues/2849. 

The previous version of the PnP PowerShell module works so the best option is to uninstall the PnP module and install version 3.23.2007.1.

I would then comment out line 202 in the deployment script to ensure the module doesn't get upgraded again.

Thanks

**Comment by alexc-MSFT** [comment]
Closed due to inactivity - reopen if required
