### ISSUE TITLE
Deployment Script Error: New-PnPSite

### ISSUE THREAD

**Issue by samuel990705** [OfficeDev/microsoft-teams-apps-requestateam#130]
I am trying to deploy the app but line 309 of the deploy.ps1 script seems to be having issues...
"New-PnPSite -Type TeamSite -Title $RequestsSiteName -Alias $requestsSiteAlias -Description $RequestsSiteDesc"

When the script is trying to create a SharePoint site, the following error is thrown (screenshot attached):
"New-PnPSite : App-Only is currently not supported, unless you provide a Microsoft Graph Access Token."

Is there something wrong with my parameters? Could it be something with my tenant?
![SharedScreenshot](https://user-images.githubusercontent.com/32914066/90475878-f3188c80-e15a-11ea-8fd7-edbfd1d31b74.jpg)

**Comment by alexc-MSFT** [comment]
@samuel990705 sadly it looks like this is an issue with PnP PowerShell - https://github.com/pnp/PnP-PowerShell/issues/2849. 

The previous version of the PnP PowerShell module works so the best option is to uninstall the PnP module and install version 3.23.2007.1.

I would then comment out line 202 in the deployment script to ensure the module doesn't get upgraded again.

Thanks

**Comment by samuel990705** [comment]
@alexc-MSFT That seems to have fixed the problem. Thanks a lot!
