### ISSUE TITLE
SharePoint PnP PowerShell Online Automation Module

### ISSUE THREAD

**Issue by SPB21** [OfficeDev/microsoft-teams-apps-requestateam#136]
@alexc-MSFT, the DeployAutomationAssets function adds the SharePoint Pnp Module for version 3.12.1908.1.  If i wanted to use the latest version 3.24.2008.1 how can i get the link from the devopsgallerystore? I am able to go into the module gallery for the deployed automation account and install the latest version that way but wanted to know if it could be done via the deployment script

`New-AzAutomationModule -AutomationAccountName $automationAccountName -Name "SharePointPnPPowerShellOnline" -ContentLink "https://devopsgallerystorage.blob.core.windows.net/packages/sharepointpnppowershellonline.3.12.1908.1.nupkg" -ResourceGroupName $ResourceGroupName`

**Comment by pkbullock** [comment]
@SPB21 just change the file to "sharepointpnppowershellonline.3.24.2008.1.nupkg" 

@alexc-MSFT - I have submitted a new sample to the PnP PowerShell repo for setting this up - https://github.com/pnp/PnP-PowerShell/pull/2835 - this uses the latest Azure AD app-only certificate method.

**Comment by SPB21** [comment]
Thanks @pkbullock
