### ISSUE TITLE
O365 license required to run the solution

### ISSUE THREAD

**Issue by rferazzi** [OfficeDev/microsoft-teams-apps-requestateam#142]
Hello,
I'm testing the solution on my tenant where I have all kind of subscription and Azure services so I don't have any license limitation.
It's very hard to understand which license are required by a "common" customer, could you please help me?
Thanks a lot!

**Comment by alexc-MSFT** [comment]
@rferazzi the only licenses required are as follows - 

- Office 365 license - A1 and up so A1,A3,A5,E3,E5 etc
- Paid Azure subscription (for the billable Azure components)

NO premium licenses for Power Apps or Power Automate are required.

Does that help?

**Comment by alexc-MSFT** [comment]
@rferazzi hope you are sorted now, I'll be closing this issue.

Please raise a new one if you are still stuck.

Thanks
