### ISSUE TITLE
"Approve requests" not visible for an Admin

### ISSUE THREAD

**Issue by tekila747** [OfficeDev/microsoft-teams-apps-requestateam#145]
Hello,

The link "Approve requests" is not visible :

![image](https://user-images.githubusercontent.com/67380644/92386054-4efb8300-f113-11ea-95e0-6620c0712527.png)

Verifications done  ::
- The current user is member of "Site Owners" group of SharePoint Site containing "Teams Requests" List
- The current user is Owner of Administrators Team
- The current user can see the adaptative card in Administrators Team and can validate request

Did I forget something?

Thanks,

**Comment by alexc-MSFT** [comment]
@tekila747 if you edit the Power App and look in the OnStart function you will find some code that uses the Office 365 Groups connector to check of the user is a member of an Office 365 group.

The idea is that you should create an O365 group containing the admins for this solution and update that code with the ID of the group.

You could of course use the same group that is used for the SharePoint site. Just grab the ID from Azure AD and update the code in the Power App.

Hope that makes sense?

**Comment by tekila747** [comment]
@alexc-MSFT Thanks for the details, but I already did what you described.

I solved the problem with these steps :
- I deleted all Admins from O365 Admin Group
- I added again the Admins to O365 Admin Group

And surprise! the problem is solved :)

**Comment by tekila747** [comment]
Solved
