### ISSUE TITLE
Apply-PnPProvisioningTemplate : The remote server returned an error: (403) Forbidden.

### ISSUE THREAD

**Issue by alig26** [OfficeDev/microsoft-teams-apps-requestateam#157]
Can anyone help with this issue, I'm not sure what am I doing wrong, please. 

New-PnPSite : App-Only is currently not supported, unless you provide a Microsoft Graph Access Token.
At C:\Users\Ali.Gomaa\OneDrive -
ProAmpac\Downloads\requestteam\microsoft-teams-apps-requestateam-master\Deployment\Scripts\deploy.ps1:309 char:9
+         New-PnPSite -Type TeamSite -Title $RequestsSiteName -Alias $r ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [New-PnPSite], Exception
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.NewSite
Site created
**TEAMS REQUESTS SITE CREATION COMPLETE**
### REQUESTS SPO SITE CONFIGURATION ###
Configuring SharePoint site...
Applying provisioning template...
Apply-PnPProvisioningTemplate : The remote server returned an error: (403) Forbidden.
At C:\Users\Ali.Gomaa\OneDrive -
ProAmpac\Downloads\requestteam\microsoft-teams-apps-requestateam-master\Deployment\Scripts\deploy.ps1:340 char:9
+         Apply-PnPProvisioningTemplate -Path (Join-Path $packageRootPa ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], WebException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Site.ApplyProvisioningTemplate
Applied template
Error occured while configuring the SharePoint site: Exception calling "ExecuteQuery" with "0" argument(s): "The remote server returned an error: (403) Forbidden."

**Comment by alexc-MSFT** [comment]
@alig26 this is a bug with the latest version of PnP, see issue #134

**Comment by joostvdlinden** [comment]
Just for the record I am experiencing the same issue..

**Comment by alexc-MSFT** [comment]
@alig26 I have also updated the deployment guide to state this is a known issue. Please downgrade PnP as per this note.

I will close this issue for now and please re-open if you are still stuck.

Thanks
