### ISSUE TITLE
Adding own templates

### ISSUE THREAD

**Issue by thondal-evry** [OfficeDev/microsoft-teams-apps-requestateam#162]
How and where do we create reusable templates for the app?

Is it only create a team and then add it in the template list? Or is something else required?
Unsure where to find the template ID

![image](https://user-images.githubusercontent.com/55357093/94780484-ccd84480-03c8-11eb-9cbc-1d2134987d61.png)

Unable to find any documentation on this

**Comment by JvdH-NL** [comment]
Haven't tested yet, but will have to. New custom templates in Teams admin UI, creating them (copy from existing and adjust): generates GUID, use this GUID for 'Base Template Id' ... I was able to provision Teams using (Beta) Mg PowerShell modules, will have to test this with this app soon (planning to use it).

**Comment by alexc-MSFT** [comment]
@JvdH-NL please can you share the body of the Graph call you are using to provision from a template defined in the Teams admin centre?

I've tried this but can't get it to work.

If this does work then we can update the documentation for people to simply copy the guid and paste into the templates list.

There will be Graph APIs available next year I hope for us to retrieve a list of admin defined templates, therefore we will update the app and we won't need the templates list anymore.

Thanks

**Comment by alexc-MSFT** [comment]
@thondal-evry aside from the above which we've yet to confirm, the way you are supposed to do it currently is -

1. Create a team manually and populate how you wish
2. Get the ID for the O365 group behind the Team, you can do this through Azure AD
3. Add a new item to the Teams Templates list, filling out the following fields - 

'Title', 'Team Id' (with the Id copied above), 'Description', 'First Party Template' (should be set to NO), 'Team Visibility' (Optional, if you wish to override and hardcode a visibility for the template.

Leave the other fields blank.

Hope that helps.

**Comment by thondal-evry** [comment]
Thanks @alexc-MSFT , I will try this next week. 
Just curious, what is included from the template? Team logo? Private channels? Pre defined tabs wit I.e projects and planner and other apps...?

**Comment by thondal-evry** [comment]
This worked like a charm :) Thanks
