### ISSUE TITLE
Trouble Provisioning Template

### ISSUE THREAD

**Issue by RobertBondy** [OfficeDev/microsoft-teams-apps-requestateam#165]
Following is the error I am getting when the deploy script is at the Applying Provisioning Template stage:

Apply-PnPProvisioningTemplate : The remote server returned an error: (403) Forbidden.
At C:\users\robb\desktop\Request-A-Team\Scripts\deploy.ps1:340 char:9
+         Apply-PnPProvisioningTemplate -Path (Join-Path $packageRootPa ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], WebException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Site.ApplyProv
   isioningTemplate
Applied template
Error occured while configuring the SharePoint site: Exception calling "ExecuteQuery" with "0" argument(s): "The remote server returned an error: (403) Forbidden."

**Comment by alexc-MSFT** [comment]
@RobertBondy quick one, can you confirm the script definitely created the SharePoint site first?

**Comment by Edjuh1** [comment]
Same issue here. But can confirm that sharepoint site is created.

### TEAMS REQUESTS SITE CREATION ###
Creating Teams Requests SharePoint site...
Account                          Environment TenantId                             TenantDomain   AccountType
-------                          ----------- --------                             ------------   -----------
admin@xxxx.onmicrosoft.com AzureCloud  xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx smevagroup.com User
https://xxxxx.sharepoint.com/sites/Requestateamapp
Site created
**TEAMS REQUESTS SITE CREATION COMPLETE**
### REQUESTS SPO SITE CONFIGURATION ###
Configuring SharePoint site...
Applying provisioning template...
Apply-PnPProvisioningTemplate : The remote server returned an error: (403) Forbidden.
At C:\microsoft-teams-apps-requestateam-master\Deployment\Scripts\deploy.ps1:340 char:9
+         Apply-PnPProvisioningTemplate -Path (Join-Path $packageRootPa ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], WebException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Site.ApplyProvisioningTemplate
Applied template
Error occured while configuring the SharePoint site: Exception calling "ExecuteQuery" with "0" argument(s): "The remote server returned an error: (403) Forbidden."

**Comment by RobertBondy** [comment]
I can state that the site was NOT created

Robert Bondy
Phone: 248-867-2118
E-Mail: robert.bondy@gmail.com

**Comment by RobertBondy** [comment]
The script was unable to connect to the Sharepoint Admin site to add the new RequestATeam site, so I added this line t the deploy script

$pnpConnect = Connect-PnPOnline $tenantAdminUrl -UseWebLogin
CreateRequestsSharePointSite

Now I am getting this error:

New-PnPSite : App-Only is currently not supported, unless you provide a Microsoft Graph Access Token.
At C:\users\robb\desktop\Request-A-Team\Scripts\deploy.ps1:309 char:9
+         New-PnPSite -Type TeamSite -Title $RequestsSiteName -Alias $r ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [New-PnPSite], Exception
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.NewSite

**Comment by alexc-MSFT** [comment]
Closed due to inactivity - reopen if required
