### ISSUE TITLE
How do I Modify fields in request?

### ISSUE THREAD

**Issue by bouncethebox** [OfficeDev/microsoft-teams-apps-requestateam#166]
For example:
1. Owner 2 (not required)
2. Hide Business reason and make it not required
3. Activate confidential check box

**Comment by SPB21** [comment]
HI,
You need to do the following:

1. Owner 2 (not required)
Update the 'OnSelect' for button 'btnNext_AddMembers' and amend the logic to match your requirements.

2. Hide Business reason and make it not required
Update the 'OnSelect' for button 'btnNext_TeamInformation' and remove the checks on the business reason field e.g. (!IsBlank(Trim(txtinpBusinessReason.Text)))

3. Activate confidential check box
Look at the visibility field on the 'Privacy Settings' section.  Basically need to add a label and checkbox to the screen and then on the next button click, patch the selected value into the teams request list:  Modify this code on 'btnNext_PrivacySettings' and instead of setting ConfidentialData = ConfidData, set it equal to the value of your new checkbox.  ConfidData is being set to true if you select 'Private' in the visibility drop down.

`If(
    cmbVisibility.Selected.Value <> "Select" && CountRows(cmbVisibility.SelectedItems) > 0,
    Patch(
        'Teams Requests',
        First(
            Filter(
                'Teams Requests',
                RowKey = Text(rowguid)
            )
        ),
        {
            Visibility: {
                '@odata.type': "#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference",
                Value: cmbVisibility.Selected.Value
            }
        },
        {ConfidentialData: ConfidData},
        {
            Stage: {
                '@odata.type': "#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference",
                Value: "Data Classification"
            }
        }
    )
);`

**Comment by bouncethebox** [comment]
Thanks for the assistance, but I am not quite sure what to edit.

1. Amend the logic how?  What should I look for and replace, etc.
2. How do I remove the checks and hide the business reason?
3. Worked like a charm, thank you!

**Comment by SPB21** [comment]
@bouncethebox so for the first item, Owner not required:

Edit the app and got to the Add Members section in the app.
Select the button **btnNext_AddMembers** and update the OnSelect property.  Then edit the logic which is done on the select of the button.  The image below shows there is a check done for at least one owner to be selected `CountRows(cmbOwners.SelectedItems) >= 1 && (CountRows(cmbMembers.SelectedItems) <= 2)` .  Edit this code to your requirements

![image](https://user-images.githubusercontent.com/68604547/95448795-c7947000-095b-11eb-833e-275c13b2f78d.png)

**Comment by SPB21** [comment]
@bouncethebox  for the second item, Hide Business reason and make it not required:

Edit the app and got to the Team Information section in the app.
Select the controls which relate to Business Reason e.g. lblBusinessReasonErrorMessage, txtinpBusinessReason and either delete the control or set **Visible = false**

![image](https://user-images.githubusercontent.com/68604547/95449620-f0693500-095c-11eb-8901-3368d5645470.png)


Then edit the button **btnNext_TeamInformation** and update the **OnSelect** code logic to remove the checks for business reason:

![image](https://user-images.githubusercontent.com/68604547/95450196-d8de7c00-095d-11eb-863b-c49097439843.png)


Hopefully this points you in the correct direction.

**Comment by nmunkley** [comment]
Sorry for hijacking this post but its probably better than creating my own.

We have a Group Naming Policy enabled, and I've found that if the request does not contain this, it still says it is available but fails during the creation process. Is there any way to change the Power App so it does a check so it matches the naming policy?

e.g

Naming Policy: Suffix = 2020-

Team name request: InsertGenericTeamName
Request-a-Team: Error, please ensure your team name meets the Naming Policy

**Comment by SPB21** [comment]
@bouncethebox, did the above help resolve your issues?

**Comment by alexc-MSFT** [comment]
@nmunkley the app doesn't support the AD group naming policy at the moment, we are currently working on adding the ability to define a naming convention to the app and hope to release this to GitHub soon.

For now, you would need to change the logic in the Power App to hardcode your naming convention.

**Comment by nmunkley** [comment]
> @nmunkley the app doesn't support the AD group naming policy at the moment, we are currently working on adding the ability to define a naming convention to the app and hope to release this to GitHub soon.
> 
> For now, you would need to change the logic in the Power App to hardcode your naming convention.

That would explain why all tests in the last day have failed at the creation stage...thanks

**Comment by SPB21** [comment]
@nmunkley, what we done in the app was add a label underneath the Team name with automatically appended our naming convention.  

![image](https://user-images.githubusercontent.com/68604547/95863409-0d867500-0d5c-11eb-9d70-262874e6e18c.png)

We then use this value as the team name when provisioning

**Comment by nmunkley** [comment]
> @nmunkley, what we done in the app was add a label underneath the Team name with automatically appended our naming convention.
> 
> ![image](https://user-images.githubusercontent.com/68604547/95863409-0d867500-0d5c-11eb-9d70-262874e6e18c.png)
> 
> We then use this value as the team name when provisioning

Thanks. This is the first time im using Power App so I think for now I'll stick to a text description telling the users to add it themselves XD

**Comment by SPB21** [comment]
@nmunkley, the following should do what you require:

`Concatenate(Text( Now(), "yyyy" ),"-",txtinpTeamName.Text)`

Should output the [current year]-[team name] e.g. 2020-My Team name

**Comment by TamasAkos** [comment]
> @bouncethebox so for the first item, Owner not required:
> 
> Edit the app and got to the Add Members section in the app.
> Select the button **btnNext_AddMembers** and update the OnSelect property. Then edit the logic which is done on the select of the button. The image below shows there is a check done for at least one owner to be selected `CountRows(cmbOwners.SelectedItems) >= 1 && (CountRows(cmbMembers.SelectedItems) <= 2)` . Edit this code to your requirements
> 
> ![image](https://user-images.githubusercontent.com/68604547/95449503-cb74c200-095c-11eb-9546-cb4b9817f206.png)

Hi, I know this is a pretty newbie question, although I tried and failed to modify the value which sets how many members can I add at the time of submitting a request. Where should I change the value? Also, is there an option to add a SG is I don't want to add the people 1 by 1? 

Thanks!

**Comment by bouncethebox** [comment]
> @bouncethebox, did the above help resolve your issues?

Everything was spot on, thanks so much and I will work on replying much sooner!

**Comment by kylasrus** [comment]
@SPB21  I am working on the same issue with making the Owner 2 field optional.  I've updated the line of code as you suggested above (editing the OnSelect property of the btnNext_AddMembers), however it doesn't appear to be working.  Now when clicking the 'Next' button nothing happens.  Can you provide more details on how to remove the requirement for a second owner?

**Comment by SPB21** [comment]
@kylasrus, can you share the code in the btnNext_addMembers and i'll take a look at it to see what maybe causing the issue

**Comment by kylasrus** [comment]
@SPB21 Attached is the code as requested.  Thank you!
[btnNextAddMembers.txt](https://github.com/OfficeDev/microsoft-teams-apps-requestateam/files/5489015/btnNextAddMembers.txt)

**Comment by SPB21** [comment]
@kylasrus, in the logic you are setting the following variables: BNReviewAndSubmit & BNMembership.  Can you ensure that the 'visible' property on the button 'btnNext_AddMembers' is set to the variable BNMembership.  The version of the app I used this variable was named 'Membership'.  

Also in line 47 in your file you would need to remove the following '&& (CountRows('cmbOwners._2'.SelectedItems) >= 0)' as this is checking the owner 2 field contains a value.  If it doesnt then the 'Patch' wont update the underlying record in the sharepoint list.

**Comment by kylasrus** [comment]
@SPB21 I confirmed that the Visible property on the button was set to the variable BNMembership.  I removed the piece of code as advised.  When I try to click Next without completed the Owner 2 field, the form will not update the sharepoint list, nor will it progress forward.  It is still requiring the Owner 2 field to be completed.

**Comment by MartinKleynhans** [comment]
May seem like a n00b question but does anyone know how I can use new Columns in the SharePoint list and write this back to the list from the form if I added a field?
