### ISSUE TITLE
Unable to see "Approve Requests" tab in PowerApp

### ISSUE THREAD

**Issue by BSiefferman** [OfficeDev/microsoft-teams-apps-requestateam#167]
I have the app created and working however, I'm missing the third tab "Approve Requests" shown in the Deployment document images. Has layout of the app changed or am I missing something in the configuration? 

![RequestATeam](https://user-images.githubusercontent.com/42012069/95767700-bfe60b80-0c7a-11eb-9113-736b5bdc421b.PNG)

**Comment by thondal-evry** [comment]
Are you @BSiefferman  as the logged in user a member of the "approver" team group? If not then you won't see the tab. Only approvers will see the "approve requests" app. 
Log in with the same account on the make.powerapps.com and see if there is any errors when in edit mode.

**Comment by alexc-MSFT** [comment]
@BSiefferman did you get this fixed as per @thondal-evry 's comment?

**Comment by BSiefferman** [comment]
Hello,

Yes,  this was an error on my part.  This is fixed now,  thank you for following up.

Thanks,
Brian Siefferman

________________________________
