### ISSUE TITLE
Post an Adaptive card fails

### ISSUE THREAD

**Issue by Humpeklumpen** [OfficeDev/microsoft-teams-apps-requestateam#169]
Hi, 

I get an error message when posting adaptive card to teams: 
![image](https://user-images.githubusercontent.com/8370646/96130507-4d825f00-0ef8-11eb-9e7d-86110dd75ce6.png)

Can anybody assist?

Thanks, Aasne

**Comment by alexc-MSFT** [comment]
Closing as this is a duplicate
