### ISSUE TITLE
Issue with editing Logic App (Process team request). 

### ISSUE THREAD

**Issue by dspooren** [OfficeDev/microsoft-teams-apps-requestateam#17]
The deployment completed successfully, without any errors.
Following the document I tried to edit the Logic app to adjust the SharePoint site collection settings

When I tried to edit: Update status to Team Creation, the following message appears:
**_Swagger not found for connector '/subscriptions/c499ec5d-3ce0-4cb3-ac54-XXXXXXf/providers/Microsoft.Web/locations/West Europe/managedApis/sharepointonline'_**

![image](https://user-images.githubusercontent.com/18420047/81829360-19ff6b00-953b-11ea-853b-8dd0543db755.png)
![image](https://user-images.githubusercontent.com/18420047/81829508-41eece80-953b-11ea-81fb-65ff1997a4c7.png)

Any ideas what went wrong?

**Comment by alexc-MSFT** [comment]
> The deployment completed successfully, without any errors.
> Following the document I tried to edit the Logic app to adjust the SharePoint site collection settings
> 
> When I tried to edit: Update status to Team Creation, the following message appears:
> **_Swagger not found for connector '/subscriptions/c499ec5d-3ce0-4cb3-ac54-XXXXXXf/providers/Microsoft.Web/locations/West Europe/managedApis/sharepointonline'_**
> 
> ![image](https://user-images.githubusercontent.com/18420047/81829360-19ff6b00-953b-11ea-853b-8dd0543db755.png)
> ![image](https://user-images.githubusercontent.com/18420047/81829508-41eece80-953b-11ea-81fb-65ff1997a4c7.png)
> 
> Any ideas what went wrong?

Just out of interest when did you get the latest code? There was a previous issue where if the 'Display Name' (West Europe) of the Azure Region was passed to the deployment script as opposed to the 'Internal Name' (West Europe) then the API connections would be created incorrectly.

This should have now been resolved.

**Comment by dspooren** [comment]
I have downloaded the code on Monday May 11th.

**Comment by dspooren** [comment]
> > The deployment completed successfully, without any errors.
> > Following the document I tried to edit the Logic app to adjust the SharePoint site collection settings
> > When I tried to edit: Update status to Team Creation, the following message appears:
> > **_Swagger not found for connector '/subscriptions/c499ec5d-3ce0-4cb3-ac54-XXXXXXf/providers/Microsoft.Web/locations/West Europe/managedApis/sharepointonline'_**
> > ![image](https://user-images.githubusercontent.com/18420047/81829360-19ff6b00-953b-11ea-853b-8dd0543db755.png)
> > ![image](https://user-images.githubusercontent.com/18420047/81829508-41eece80-953b-11ea-81fb-65ff1997a4c7.png)
> > Any ideas what went wrong?
> 
> Just out of interest when did you get the latest code? There was a previous issue where if the 'Display Name' (West Europe) of the Azure Region was passed to the deployment script as opposed to the 'Internal Name' (West Europe) then the API connections would be created incorrectly.
> 
> This should have now been resolved.

I have downloaded the code on Tue May 12th. When has this been changed/fixed exactly?

**Comment by alexc-MSFT** [comment]
> > > The deployment completed successfully, without any errors.
> > > Following the document I tried to edit the Logic app to adjust the SharePoint site collection settings
> > > When I tried to edit: Update status to Team Creation, the following message appears:
> > > **_Swagger not found for connector '/subscriptions/c499ec5d-3ce0-4cb3-ac54-XXXXXXf/providers/Microsoft.Web/locations/West Europe/managedApis/sharepointonline'_**
> > > ![image](https://user-images.githubusercontent.com/18420047/81829360-19ff6b00-953b-11ea-853b-8dd0543db755.png)
> > > ![image](https://user-images.githubusercontent.com/18420047/81829508-41eece80-953b-11ea-81fb-65ff1997a4c7.png)
> > > Any ideas what went wrong?
> > 
> > 
> > Just out of interest when did you get the latest code? There was a previous issue where if the 'Display Name' (West Europe) of the Azure Region was passed to the deployment script as opposed to the 'Internal Name' (West Europe) then the API connections would be created incorrectly.
> > This should have now been resolved.
> 
> I have downloaded the code on Tue May 12th. When has this been changed/fixed exactly?

See the following pull request - https://github.com/OfficeDev/microsoft-teams-apps-requestateam/pull/13.

There is a function in the deploy.ps1 script which should automatically replace any spaces in the 'Location' parameter. Can you double check that this function is indeed in your script? And also did you use -Location 'West Europe' when you executed the script?

**Comment by dspooren** [comment]
> > > > The deployment completed successfully, without any errors.
> > > > Following the document I tried to edit the Logic app to adjust the SharePoint site collection settings
> > > > When I tried to edit: Update status to Team Creation, the following message appears:
> > > > **_Swagger not found for connector '/subscriptions/c499ec5d-3ce0-4cb3-ac54-XXXXXXf/providers/Microsoft.Web/locations/West Europe/managedApis/sharepointonline'_**
> > > > ![image](https://user-images.githubusercontent.com/18420047/81829360-19ff6b00-953b-11ea-853b-8dd0543db755.png)
> > > > ![image](https://user-images.githubusercontent.com/18420047/81829508-41eece80-953b-11ea-81fb-65ff1997a4c7.png)
> > > > Any ideas what went wrong?
> > > 
> > > 
> > > Just out of interest when did you get the latest code? There was a previous issue where if the 'Display Name' (West Europe) of the Azure Region was passed to the deployment script as opposed to the 'Internal Name' (West Europe) then the API connections would be created incorrectly.
> > > This should have now been resolved.
> > 
> > 
> > I have downloaded the code on Tue May 12th. When has this been changed/fixed exactly?
> 
> See the following pull request - #13.
> 
> There is a function in the deploy.ps1 script which should automatically replace any spaces in the 'Location' parameter. Can you double check that this function is indeed in your script? And also did you use -Location 'West Europe' when you executed the script?

Yes, I have used the following parameter: 
![image](https://user-images.githubusercontent.com/18420047/81944394-fb61a880-95fc-11ea-8653-04db6566960d.png)

**Comment by dspooren** [comment]
This is in the script:
#Check that the provided location is a valid Azure location
function ValidateAzureLocation {
    $locations = Get-AzLocation
    
    $Location = $Location.Replace(" ","")

    # Validate that the location exists
    if($null -eq ($locations | Where-Object Location -eq $Location)) {
        throw "Invalid Azure Location. Please provide a valid location. See this list - https://azure.microsoft.com/en-gb/global-infrastructure/locations/"

    }
}

**Comment by alexc-MSFT** [comment]
> This is in the script:
> #Check that the provided location is a valid Azure location
> function ValidateAzureLocation {
> $locations = Get-AzLocation
> 
> ```
> $Location = $Location.Replace(" ","")
> 
> # Validate that the location exists
> if($null -eq ($locations | Where-Object Location -eq $Location)) {
>     throw "Invalid Azure Location. Please provide a valid location. See this list - https://azure.microsoft.com/en-gb/global-infrastructure/locations/"
> 
> }
> ```
> 
> }

Ok so that should solve your issue - let me test and get back to you.

**Comment by alexc-MSFT** [comment]
@dspooren ok so I have fixed this issue and created a pull request for it, in order to get around it for now, please provide the location in lowercase e.g. west europe.

See linked pull request.

Thanks
