### ISSUE TITLE
Can't add guest users

### ISSUE THREAD

**Issue by Amir7464** [OfficeDev/microsoft-teams-apps-requestateam#172]
I'm trying to add guest users as owner or member but the Logic App can't find them.

Is there any solution for this problem?

*Changed some values in the picture*

![image](https://user-images.githubusercontent.com/47493418/96378268-0e1f7100-118b-11eb-95c3-8ce7fa210c41.png)

![image](https://user-images.githubusercontent.com/47493418/96378361-b3d2e000-118b-11eb-8229-fd49c715ba32.png)

I can find the guest user in AAD.

**Comment by Amir7464** [comment]
Update: The issue is in line 2019 and 2069 in the logic app.

I'm trying to change the line to 

`https://graph.microsoft.com/v1.0/users?$filter=UserType eq '*'&$filter=mail eq '@{encodeURIComponent(items('Loop_through_Members')?['Email'])}'`

But it does not work. I think the problem is coming from the API connection "teamsautomate-o365users"

**Comment by Amir7464** [comment]
Update: Found the solution after 6 hours...

Change the Loop through Owner as below Ex.


![image](https://user-images.githubusercontent.com/47493418/96388916-82b6d780-11ac-11eb-8849-c6769a77888a.png)

And Member

![image](https://user-images.githubusercontent.com/47493418/96415261-997e1e00-11ee-11eb-899b-c9aa1ef51bb3.png)

**Comment by alexc-MSFT** [comment]
Thanks @Amir7464 for pointing this one out. Glad you got it sorted.
