### ISSUE TITLE
Replace CheckSiteExists runbook with a Logic App

### ISSUE THREAD

**Issue by alexc-MSFT** [OfficeDev/microsoft-teams-apps-requestateam#188]
**Summary**
With this release the automation runbook which checks if a SharePoint site exists matching the same URL will be removed and replaced with a dedicated Logic App. This is due to a bug that has been reported where if a large number of requests are created per day, the runbook frequently fails due to load on the PnP PowerShell components.

**Intended Outcome**
To be able to remove the automation functionality and replace with Logic Apps.

**How will it work**
A new Logic App will perform the above check and will be executed from the 'ProcessTeamRequest' Logic App.

**Comment by alexc-MSFT** [comment]
Code committed and pull requested created.

**Comment by alexc-MSFT** [comment]
Special thanks to @frankchen76 for this one 👍

**Comment by alexc-MSFT** [comment]
Roadmap item complate

**Comment by alexc-MSFT** [comment]
Roadmap item complete

**Comment by kireetijs** [comment]
Thank you for creating logic app. How can i import the "CheckSiteExist" logic app instead of running deployment script?

**Comment by frankchen76** [comment]
@kireetijs, you can find checksiteexists.json from microsoft-teams-apps-requestateam/Deployment/Scripts folder. you can simply use that JSON file to create your Logic App.

**Comment by kireetijs** [comment]
Thank you for quick response. Created logic app and pasted json code in code view. On save, getting following error- 
Failed to save logic app checksiteexists. The request content is not valid and could not be deserialized: 'Could not find member 'default value' on object of type 'FlowTemplateParameter'.Path 'Properties.parameters.location.defaultvalue', line 1, position 1028'.
