### ISSUE TITLE
Service account rights

### ISSUE THREAD

**Issue by fidoly** [OfficeDev/microsoft-teams-apps-requestateam#19]
Service account is nothing but an Office 365 user who has all the rights the same as admin and has a minimum of E3 license.

Do we really want a service account with admin rights?   What roles are needed to this account to function?

**Comment by abbodh** [comment]
Hello, you do not need a admin rights for service account. Service account is used to post welcome message once team is created. The app is designed to add the service account to new team, send a welcome message and then removing the service account only. Please refer https://docs.microsoft.com/en-us/microsoftteams/user-access#assign-a-teams-license to know how to assign Teams license.
