### ISSUE TITLE
Get-AzureADDirectorySetting : The term 'Get-AzureADDirectorySetting' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by garrytrinder** [OfficeDev/microsoft-teams-apps-requestateam#2]
![image](https://user-images.githubusercontent.com/11563347/80587892-454c6b00-8a0f-11ea-93ba-657eabc80023.png)

**Comment by garrytrinder** [comment]
Azure AD Preview was installed previously to running the script using `Install-Module AzureADPreview -UseClobber` as I already had the `AzureAD` module installed which caused issues with running the `deploy.ps1` script for the first time.

The `Get-AzureADDirectorySetting` is present on my machine.

![image](https://user-images.githubusercontent.com/11563347/80588437-44680900-8a10-11ea-9dc6-0833b5c347f2.png)

**Comment by sharepointalex** [comment]
> Azure AD Preview was installed previously to running the script using `Install-Module AzureADPreview -UseClobber` as I already had the `AzureAD` module installed which caused issues with running the `deploy.ps1` script for the first time.
> 
> The `Get-AzureADDirectorySetting` is present on my machine.
> 
> ![image](https://user-images.githubusercontent.com/11563347/80588437-44680900-8a10-11ea-9dc6-0833b5c347f2.png)

I think this will need a -Force adding to the Install-Module cmdlet in the script i.e. Install-Module AzureADPreview -Scope CurrentUser -Force. It requires the AzureADPreview module specifically.

**Comment by garrytrinder** [comment]
Thanks @sharepointalex , when I ran it the first time and got errors on install, in the error message it suggests using `-UseClobber`. 

I've tried again in a new session and got the same error. I'll try `AzureADPreview -Scope CurrentUser -Force` as you've suggested 👍🏻.

**Comment by garrytrinder** [comment]
Using `Install-Module AzureADPreview -Scope CurrentUser -Force` threw this error.

![image](https://user-images.githubusercontent.com/11563347/80590576-0a990180-8a14-11ea-8cb5-964f460370be.png)

Run again but adding the `-AllowClobber` flag, doesn't error.

We go again...

**Comment by garrytrinder** [comment]
So it turns out that running in an Admin session, neither of those options work.

I created a "normal user" session, ran `Install-Module AzureADPreview -Scope CurrentUser -Force`, re-ran `deploy.ps1` and no error 🎉
