### ISSUE TITLE
Error occured while configuring the SharePoint site

### ISSUE THREAD

**Issue by mitsubishop** [OfficeDev/microsoft-teams-apps-requestateam#20]
Hi,

During installation I am seeing an error while applying the PnP template.

Error shown is:
Error occured while configuring the SharePoint site: Cannot find an overload for "Load" and the argument count: "1".

**Comment by alexc-MSFT** [comment]
> Hi,
> 
> During installation I am seeing an error while applying the PnP template.
> 
> Error shown is:
> Error occured while configuring the SharePoint site: Cannot find an overload for "Load" and the argument count: "1".

Hi,

Please can you let me know which version of PnP you are using? Did you have the module installed by any chance before running the script?

Thanks

**Comment by mitsubishop** [comment]
Hi,

Yes it was installed before running the script - version 3.15.1911.0

Thanks

**Comment by fidoly** [comment]
Hi Alexc,  I ran into errors creating the SharePoint site.   Here is the console output:

### AZURE AD APP CREATION FINISHED ###
Get-AzureADDirectorySetting : The term 'Get-AzureADDirectorySetting' is not recognized 
### TEAMS REQUESTS SITE CREATION ###
Creating Teams Requests SharePoint site...
Error occured while creating of the SharePoint site: The term 'Get-PnPTenantSite' is not recognized...
### REQUESTS SPO SITE CONFIGURATION ###
Configuring SharePoint site...
Applying provisioning template...
Error occured while configuring the SharePoint site: The term 'Apply-PnPProvisioningTemplate' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

thanks.

**Comment by alexc-MSFT** [comment]
> Hi,
> 
> Yes it was installed before running the script - version 3.15.1911.0
> 
> Thanks

The script requires a specific version of PnP -  3.19.2003.0. This should be installed when you run the deployment script. That being said there was a bug recently where these lines were commented out so if you get a fresh copy of the code you should be good.

If in doubt, uninstall your current version of the PnP module and re-run the script.

**Comment by alexc-MSFT** [comment]
> Hi Alexc, I ran into errors creating the SharePoint site. Here is the console output:
> 
> ### AZURE AD APP CREATION FINISHED
> Get-AzureADDirectorySetting : The term 'Get-AzureADDirectorySetting' is not recognized
> 
> ### TEAMS REQUESTS SITE CREATION
> Creating Teams Requests SharePoint site...
> Error occured while creating of the SharePoint site: The term 'Get-PnPTenantSite' is not recognized...
> 
> ### REQUESTS SPO SITE CONFIGURATION
> Configuring SharePoint site...
> Applying provisioning template...
> Error occured while configuring the SharePoint site: The term 'Apply-PnPProvisioningTemplate' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> 
> Everything else was fine.
> 
> thanks.

I have raised a new issue for this, see - https://github.com/OfficeDev/microsoft-teams-apps-requestateam/issues/23

**Comment by alexc-MSFT** [comment]
New issue raised for this - see above
