### ISSUE TITLE
No data in dropdown (Privacy Settings) when creating new team request

### ISSUE THREAD

**Issue by LowManOnTotem** [OfficeDev/microsoft-teams-apps-requestateam#206]
After finally getting the app setup properly, when I click on Build new button from "Scratch", nothing fills into the dropdown. I am assuming that the list would include "Private" or "Public") but there is nothing. Nothing prefills when I want to create a new site from template. I assume again that this would show my templates. Did I miss something?

**Comment by momoangel** [comment]
I am having the same issue. nothing in the drop down.

**Comment by momoangel** [comment]
I was able to resolve this!  Looks like changing the SharePoint site\lists in the power app did not properly save the first time I did this.  I went back through my app and found the lists were again pointing to the fake\initial list.  Deleted these, and ran through the SharePoint connector steps again - chose to save and then publish again and now my dropdown for public\private is populating.

**Comment by alexc-MSFT** [comment]
Closing this as it's a duplicate
