### ISSUE TITLE
Logic App: ProcessTeamRequest uses old SharePoint Column Name

### ISSUE THREAD

**Issue by Alsterwasser** [OfficeDev/microsoft-teams-apps-requestateam#219]
Hey there,
after importing the Logic App "ProcessTeamRequest" I noticed, that in the step "Check template type" still the old SharePoint column name "FirstPartyTemplate" is used. This should be "AdminCenterTemplate" know, as the column [name was changed](https://github.com/OfficeDev/microsoft-teams-apps-requestateam/pull/210).

**Comment by alexc-MSFT** [comment]
@Alsterwasser this should have been updated. Just out of interest which logic app did you deploy - the beta one? i.e. with the UseMSGraph beta param set to true?

This was never updated. I'm planning to remove this logic app as it's not really required anymore.

Thanks

**Comment by Alsterwasser** [comment]
Hey Alex,

Thank you for your response. You are correct, I used the -UseMSGraphBeta parameter. I was not aware, that the logic app ist not required anymore and therefore the logic app was never updated.

I think the issue can therefore than be closed.
