### ISSUE TITLE
Please make this app function for other/all Office 365 Groups/Apps

### ISSUE THREAD

**Issue by colin-small** [OfficeDev/microsoft-teams-apps-requestateam#22]
This app is awesome.. but why restrict it to Teams? This would be a great way to deal with automating the creation of any Office 365 Group for any app. Especially for those of us with Office 365 Group creation restricted in the tenant.

If you could ask, what app are you requesting a group for.. Planner? Teams? and then send the request for approval and if approved automatically create the Office 365 Group and assign the correct owner etc.. That would be super useful. Respecting group naming policies would be ideal.

With the creation of Office 365 Groups restricted, this would really help deal with the issue in a seamless and pleasant way. Otherwise we are left to building our own custom ways of dealing with the issue and that just kind of sucks. This would be more of a turnkey option that many people could benefit from.

If you can accomplish this, please do.

**Comment by alexc-MSFT** [comment]
@colin-small glad you here you like the app.

Thanks for your feedback - I will pass this on.
