### ISSUE TITLE
ActionFailed. An action failed. No dependent actions succeeded.

### ISSUE THREAD

**Issue by russbasiura** [OfficeDev/microsoft-teams-apps-requestateam#223]

**Comment by alexc-MSFT** [comment]
@russbasiura Please can you provide some more info

**Comment by tsstahl** [comment]
I'm having the same error message in the logic app.  During the check template type routing block, specifically Clone team.  The errors are bad requests.  I did add the beta Teams switch to the install script.  Here are the inputs:
{
    "uri": "https://graph.microsoft.com/beta/teams/standard/clone",
    "method": "POST",
    "headers": {
        "content-type": "application/json"
    },
    "authentication": {
        "tenant": "\<redacted\>",
        "audience": "https://graph.microsoft.com",
        "clientId": "\<redacted\>",
        "secret": "*sanitized*",
        "type": "ActiveDirectoryOAuth"
    },
    "body": {
        "classification": null,
        "description": "Desc",
        "displayName": "TM-ATP Demo 7",
        "mailNickname": "TMATPDemo7",
        "partsToClone": "apps,tabs,settings,channels",
        "visibility": "Private"
    }
}

Here is the output/return values:
My apologies if redacting the ID numbers is a Bad Thing; obviously I'm a newb to this. The request and client-request IDs were/are the same.
{
    "statusCode": 400,
    "headers": {
        "Transfer-Encoding": "chunked",
        "Vary": "Accept-Encoding",
        "Strict-Transport-Security": "max-age=31536000",
        "request-id": "\<redacted\>",
        "client-request-id": "\<redacted\>",
        "x-ms-ags-diagnostic": "{\"ServerInfo\":{\"DataCenter\":\"Central US\",\"Slice\":\"E\",\"Ring\":\"2\",\"ScaleUnit\":\"002\",\"RoleInstance\":\"DS3PEPF00001664\"}}",
        "Date": "Tue, 02 Mar 2021 22:05:49 GMT",
        "Content-Type": "application/json",
        "Content-Length": "296"
    },
    "body": {
        "error": {
            "code": "BadRequest",
            "message": "teamId needs to be a valid GUID.",
            "innerError": {
                "date": "2021-03-02T22:05:50",
                "request-id": "\<redacted\>",
                "client-request-id": "\<redacted\>"
            }
        }
    }
}

**Comment by BBenedikt** [comment]
Seems to be the same Issue as #219

**Comment by alexc-MSFT** [comment]
@tsstahl @BBenedikt I'm afraid the beta logic app (provisioned using the UseMSGraphBeta param) has not been updated for some time. I'm going to deprecate this one as the only functionality it provided as extra was the ability to clone private channels, all it really did was re-create them anyhow. 

So it will be removed shortly.

Therefore I would suggest re-deploying with the UseMSGraphBeta flag set to false.
