### ISSUE TITLE
Users Getting user does not have permission to access the path /providers/Microsoft.PowerApps//apps/<GUID>

### ISSUE THREAD

**Issue by NPrice99** [OfficeDev/microsoft-teams-apps-requestateam#224]
Hi

I have installed the PowerApp in Teams and all works well for those who are administrators.  However, Joe Users get the above message when they try and access the PowerApp.

This smells like a permissions issue.

Regards

Nigel

**Comment by alexc-MSFT** [comment]
@NPrice99 hmm that is odd. I've never seen that before. I take it normal users have the app shared with them? Do they have access to the SharePoint site etc?

**Comment by NPrice99** [comment]
Hi Alex - yes it's just this user.  Others work fine. I have checked all of the permissions all good

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by alexc-MSFT** [comment]
@NPrice99 sorry but I'm not sure on this one - seems like a Power Apps bug to me so I would raise a ticket if you can. Thanks

**Comment by alexc-MSFT** [comment]
Closing for now but please re-open if you have updates.
