### ISSUE TITLE
Install PnP.Powershell module script forces 1.3.13-nightly, but that version does not exist in PSGallery

### ISSUE THREAD

**Issue by aqyx** [OfficeDev/microsoft-teams-apps-requestateam#234]
Input:
Install-Module PnP.PowerShell -AllowPrerelease -MinimumVersion "1.3.13-nightly" -MaximumVersion "1.3.13-nightly" -Force

Output:
Install-Module : Cannot process argument transformation on parameter 'MinimumVersion'. Cannot convert value
"1.3.13-nightly" to type "System.Version". Error: "Input string was not in a correct format."
At [xxxxxxxxxxx]\Deployment\Scripts\deploy.ps1:201 char:64
+ ... .PowerShell -AllowPrerelease -MinimumVersion "1.3.13-nightly" -Maximu ...
+                                                  ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Install-Module], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Install-Module
    
   https://www.powershellgallery.com/packages/PnP.PowerShell

**Comment by aqyx** [comment]
Hi @alexc-MSFT - great, thanks for the quick response. Worth updating the deployment guide to clarify?

**Comment by alexc-MSFT** [comment]
@aqyx I'll try - although I'm hoping PnP 1.4.0 will be released this week as planned so I can ditch that nightly one. Sadly 1.3.0 has a bunch of bugs that broke the script 😢

**Comment by alexc-MSFT** [comment]
@aqyx this is now fixed. 1.4.0 has been released so I've updated the script to use that.
