### ISSUE TITLE
Add owners/members combos not working

### ISSUE THREAD

**Issue by goleotti** [OfficeDev/microsoft-teams-apps-requestateam#236]
After getting application set up, in the the Add member step I am not able to select Owners and Members. Combos does not react to click. Can anyone help?

**Comment by alexc-MSFT** [comment]
@goleotti this is an occasional known issue and is a Power Apps service bug. You need to edit the Power App, select the Owners/Members combo boxes and turn off 'Allow searching' then turn this back on straight after.

Once you've done this, save and publish the app.

**Comment by goleotti** [comment]
thank you Alex, I'm sorry: either I have failed somewhere else or the solution does not work for me.
One thing that maybe useful: I have found all combos with 'Allow searching' disabled.

**Comment by goleotti** [comment]
I apologize, I've done the process another one time, and now the combo works!
THANK YOU!

**Comment by alexc-MSFT** [comment]
@goleotti Glad to hear you got it working.
