### ISSUE TITLE
PowerShell Runbook throws error

### ISSUE THREAD

**Issue by pavecer** [OfficeDev/microsoft-teams-apps-requestateam#24]
For both validation I receive this errors, even app is registered to AAD and permissions granted it is not working.

Get-PnPTenantSite : The remote server returned an error: (403) Forbidden. At line:24 char:17 + $site = Get-PnPTenantSite -Url $siteUrl + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : WriteError: (:) [Get-PnPTenantSite], WebException + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.GetTenantSite

Get-PnPTenantRecycleBinItem : The remote server returned an error: (403) Forbidden. At line:27 char:20 + $binItem = Get-PnPTenantRecycleBinItem | Where-Object Url -eq ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : WriteError: (:) [Get-PnPTenantRecycleBinItem], WebException + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.RecycleBin.GetTenantRecycleBinItems

**Comment by alexc-MSFT** [comment]
@pavecer Thanks for highlighting this. 

There is an additional step missing from the deployment documentation which we will need to add.

Essentially the AAD app needs registering as an app within SharePoint for this to work. We will update the documentation ASAP.

**Comment by alexc-MSFT** [comment]
Documentation now updated to include missing steps to fix this.
