### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by rwheeler33** [OfficeDev/microsoft-teams-apps-requestateam#241]
Hello,

When running the deploy.ps1 I ran into the following error. When looking at the modules already installed I have AzureAD 2.0.2.130. 

![image](https://user-images.githubusercontent.com/81416634/112619953-4e4fe300-8dfe-11eb-8c1b-b5d9aeea09d1.png)

**Comment by alexc-MSFT** [comment]
@rwheeler33 can you please uninstall the older AzureAD module first then re-run the script.

The script requires the preview module and won't work with both installed.

Thanks

**Comment by alexc-MSFT** [comment]
Closed due to lack of updates - please re-raise if this is still a problem.
