### ISSUE TITLE
Install not working?

### ISSUE THREAD

**Issue by Farff** [OfficeDev/microsoft-teams-apps-requestateam#242]
During the script deployment, I get the only error message of 

`Invoke-PnPSiteTemplate : Cannot contact site at the specified URL
https://tennanthere.sharepoint.com/teams-request/teams-request. There is no Web named
"/teams-request/teams-request/_vti_bin/sites.asmx".
At C:\scripts\microsoft-teams-apps-requestateam-master\Deployment\scripts\deploy.ps1:365 char:9
+         Invoke-PnPSiteTemplate -Path (Join-Path $packageRootPath $tem ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Invoke-PnPSiteTemplate], ClientRequestException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Site.InvokeSiteTemplate
Applied template
Error occured while configuring the SharePoint site: Exception calling "ExecuteQuery" with "0" argument(s): "Cannot contact site at the specified URL https://tennanthere.sharepoint.com/teams-request/teams-request. There is no Web named "/teams-request/teams-request/_vti_bin/sites.asmx"."`

It doesn't appear to be creating the actual sharepoint site.  Am I doing something wrong or do I have to create this site first for this to work?

**Comment by alexc-MSFT** [comment]
@Farff When you specified the 'Managed Path parameter when running the script, did you use teams-request by any chance?

A valid managed path is either 'sites' or 'teams' and will depend on what your tenant is set to.

The site name should be ok to contain hypens but I've not tested it, I'm certain it's the invalid managed path giving you that error.

**Comment by Farff** [comment]
@alexc-MSFT This solved the problem, thank you so much
