### ISSUE TITLE
Logic App does not find SharePoint Site / Site not created

### ISSUE THREAD

**Issue by ChristianMitCh** [OfficeDev/microsoft-teams-apps-requestateam#243]
Hello, I have following problem. The logic App does not find the Sharepoint site, because the site is not created. Where would the site be created? My Flows where successfully so far'
![image](https://user-images.githubusercontent.com/25382659/113249550-29a4b100-92bf-11eb-9b27-cdbe45bddade.png)
![image](https://user-images.githubusercontent.com/25382659/113249576-345f4600-92bf-11eb-9d0a-ee40e323c94d.png)

Where did I miss something?

It seems, that this step is failing:
![image](https://user-images.githubusercontent.com/25382659/113290004-4bb72700-92f1-11eb-8f91-91cf3aea570c.png)
Where do I have to fix this issue?

**Comment by alexc-MSFT** [comment]
@ChristianMitCh did you register the AD app as a SharePoint add-in as per the documentation?

This error normally occurs if you did not follow this step.

Thanks

**Comment by ChristianMitCh** [comment]
@alexc-MSFT thank you! yes this was exactly the problem. I did it, but somehow it didn´t work the first time! thank you for your reply :)

**Comment by alexc-MSFT** [comment]
@ChristianMitCh Glad you got it working - no worries 😃
