### ISSUE TITLE
First Part Template Issues with the latest version of the app

### ISSUE THREAD

**Issue by kunalkankariya** [OfficeDev/microsoft-teams-apps-requestateam#247]
Dear Alex,

With the new version where "First Party Template" option has been removed doesn't work if Graph beta endpoint is used.

processteamrequestbeta.json - Still contains reference to First Party template whereas processteamrequestv1.0.json doesn't. The beta logic app needs to be updated.

Thanks,
KK

**Comment by alexc-MSFT** [comment]
@kalyankrishna1 I have literally just removed the beta logic app this morning I'm afraid.

It was very out of date and I don't have the capacity to realign both of them.

The only extra piece this offered was the creation of private channels when cloning teams and I don't think this was used very often.

We may look to add this functionality to the 1.0 (now named processteamrequest.json) later down the line.

Thanks

**Comment by kunalkankariya** [comment]
hahaha.. I just saw that the update was literally made 15 minutes back and here I was comparing the solution on my local pc with the one here on GitHub & I was like "Where did I download the solution from?". Anyways, thanks for the update Alex. Fantastic work on the app template.

Cheers,
KK
