### ISSUE TITLE
Additional modules needed during deployment

### ISSUE THREAD

**Issue by pavecer** [OfficeDev/microsoft-teams-apps-requestateam#25]
There are additional modules needed to install prior running script deploy that are not mentioned :

Install-Module -Name WriteAscii
Install-Module SharePointPnPPowerShellOnline
Install-Module ImportExcel

**Comment by alexc-MSFT** [comment]
@pavecer these should be installed by the script. There was a bug where these lines were commented out so depending on when you last got a copy of the deployment script that may be why.
