### ISSUE TITLE
Team Requests Site Creation Failed

### ISSUE THREAD

**Issue by NPrice99** [OfficeDev/microsoft-teams-apps-requestateam#254]
I am trying the new version of the PowerShell Script.

I am the Global Admin of my Azure Tenancy.

### TEAMS REQUESTS SITE CREATION ###
Creating Teams Requests SharePoint site  https://NJPEnterprises.sharepoint.com/sites/Requestateamapp6  Request a team app6...
Account                   Environment TenantId                             TenantDomain       AccountType
-------                   ----------- --------                             ------------       -----------
xxxxx@yyyyyyyyy.com AzureCloud  4e7056d6-0830-41be-a136-93b24c588169 yyyyyyy.com User
New-PnPSite : The remote server returned an error: (403) Forbidden.
At C:\Users\xxxxxx\OneDrive\Documents\RequestATeamsApp\22042021\microsoft-teams-apps-requestateam-master\Deployment\Scri
pts\deploy.ps1:329 char:13
+             New-PnPSite -Type TeamSite -Title $RequestsSiteName -Alia ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [New-PnPSite], WebException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.NewSite
Site created
**TEAMS REQUESTS SITE CREATION COMPLETE**
### REQUESTS SPO SITE CONFIGURATION ###
Configuring SharePoint site...
Applying provisioning template... ..\Templates\requestateam-sitetemplate.xml
Invoke-PnPSiteTemplate : The remote server returned an error: (404) Not Found.
At C:\Users\xxxxxx\OneDrive\Documents\RequestATeamsApp\22042021\microsoft-teams-apps-requestateam-master\Deployment\Scri
pts\deploy.ps1:360 char:9
+         Invoke-PnPSiteTemplate -Path $JoinedPath -ClearNavigation
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Invoke-PnPSiteTemplate], WebException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Site.InvokeSiteTemplate
Applied template
Error occured while configuring the SharePoint site: Exception calling "ExecuteQuery" with "0" argument(s): "The remote server returned an error: (404) Not Found."

**Comment by NPrice99** [comment]
So I have found the problem here.  If you have run the script once and it failed after it create the SharePoint Team Site (New-PnPSite) and then rerun it.  The url of the created site maay not be the one you thought it should be. eg RequestATeamApp2 might comeback as RequestATeamApp277  I think because the system thinks there is a group already there.  A possible work around is straight after the New-PnPSIte  is $createdsite=Get-PnpSite and use the $createdsite as the variable when logging into site later on.

**Comment by alexc-MSFT** [comment]
@NPrice99 that is odd, if you specify the same site name when re-running the script it should overwrite it. Obviously the name of the site would have to be exactly the same.

e.g. if yours was RequestATeamApp and you specified RequestATeamApp again the second time it should not recreate the site but rather apply the template to it.

I'm going to do some testing and report back.

**Comment by NPrice99** [comment]
Hi Alex

If you run the deploy script and it fails, you then delete the created site.  Rerun the deploy script and the created site will not have the same url as the site had when the script was First run.

I hope I have explained things more clearly.

Regards

Nigel
________________________________

**Comment by JabbarAS** [comment]
I am getting the error Invoke-PnPSiteTemplate while running the deploy script. 
Is anyone having a solution to this error?

**TEAMS REQUESTS SITE CREATION COMPLETE**
### REQUESTS SPO SITE CONFIGURATION ###
Configuring SharePoint site...
Applying provisioning template...
Invoke-PnPSiteTemplate : The remote server returned an error: (404) Not Found.
At C:\Deployment\Scripts\deploy.ps1:357 char:9
+         Invoke-PnPSiteTemplate -Path (Join-Path $packageRootPath $tem ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Invoke-PnPSiteTemplate], WebException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Site.InvokeSiteTemplate
Applied template
Error occured while configuring the SharePoint site: Exception calling "ExecuteQuery" with "0" argument(s): "The remote server returne
d an error: (404) Not Found."

**Comment by gordonAndersen** [comment]
Same problem. Any news?

**Comment by SteveWedge** [comment]
> Same problem. Any news?

Had the site, to which you wanted to apply the template, exist? If not, then you will get this 404 error.

**Comment by MadsSWinther** [comment]
Did some digging in the scripts.
apparently the sharepoint site is default created (might be tenant specific) in the /teams/* path since there is a team owner group behind, but setting the "ManagedPath" to sites in the deployment scripts breaks detection of the correct site and causes the error.
simply put, changing "ManagedPath" from sites to teams solved the issue for us.

**Comment by alexc-MSFT** [comment]
Closed due to inactivity - reopen if required
