### ISSUE TITLE
Logic App - Post welcome message part

### ISSUE THREAD

**Issue by pavecer** [OfficeDev/microsoft-teams-apps-requestateam#26]
I found out that this part is adding service principal account to group that was created and then trying to post message to Teams team that was created. 
The problem is that Teams and synchronizing members from underlain group on unpredictable frequency. 
So it can happen that this account will not appear in team at all and then the logic app will fail. Even there is wait for 3 minutes.

I highly suggest to add this principal directly to team, then everything should work smoothly.

**Comment by alexc-MSFT** [comment]
> I found out that this part is adding service principal account to group that was created and then trying to post message to Teams team that was created.
> The problem is that Teams and synchronizing members from underlain group on unpredictable frequency.
> So it can happen that this account will not appear in team at all and then the logic app will fail. Even there is wait for 3 minutes.
> 
> I highly suggest to add this principal directly to team, then everything should work smoothly.

Thanks for the feedback. Have you experienced the logic app failing at this point? 

We will consider adding the service account at the time the group is created.

**Comment by pavecer** [comment]
Yes I see that it fail in this point
I see the pricipal as the owner of group, but not in team.

**Comment by neimadpc** [comment]
> > I found out that this part is adding service principal account to group that was created and then trying to post message to Teams team that was created.
> > The problem is that Teams and synchronizing members from underlain group on unpredictable frequency.
> > So it can happen that this account will not appear in team at all and then the logic app will fail. Even there is wait for 3 minutes.
> > I highly suggest to add this principal directly to team, then everything should work smoothly.
> 
> Thanks for the feedback. Have you experienced the logic app failing at this point?
> 
> We will consider adding the service account at the time the group is created.

I am experiencing the same:

"statusCode": 403,
    "headers": {
        "request-id": "31298477-8d66-4a21-b267-cd8d66730599",
        "client-request-id": "31298477-8d66-4a21-b267-cd8d66730599",
        "x-ms-ags-diagnostic": "{\"ServerInfo\":{\"DataCenter\":\"Central US\",\"Slice\":\"SliceC\",\"Ring\":\"2\",\"ScaleUnit\":\"001\",\"RoleInstance\":\"AGSFE_IN_9\"}}",
        "Strict-Transport-Security": "max-age=31536000",
        "Timing-Allow-Origin": "*",
        "x-ms-apihub-cached-response": "false",
        "Cache-Control": "private",
        "Date": "Wed, 20 May 2020 12:10:25 GMT",
        "Content-Length": "204",
        "Content-Type": "application/json"
    },
    "body": {
        "error": {
            "code": "Forbidden",
            "message": "Forbidden",
            "innerError": {
                "request-id": "31298477-8d66-4a21-b267-cd8d66730599",
                "date": "2020-05-20T12:10:26"

**Comment by alexc-MSFT** [comment]
> > > I found out that this part is adding service principal account to group that was created and then trying to post message to Teams team that was created.
> > > The problem is that Teams and synchronizing members from underlain group on unpredictable frequency.
> > > So it can happen that this account will not appear in team at all and then the logic app will fail. Even there is wait for 3 minutes.
> > > I highly suggest to add this principal directly to team, then everything should work smoothly.
> > 
> > 
> > Thanks for the feedback. Have you experienced the logic app failing at this point?
> > We will consider adding the service account at the time the group is created.
> 
> I am experiencing the same:
> 
> "statusCode": 403,
> 
> Service account is owner of 365 group, not owner/member in Team.

There is a pull request with a change to the logic app which will fix this. I am waiting for it to be approved.

**Comment by neimadpc** [comment]
This is not resolved... New error.
![image](https://user-images.githubusercontent.com/65623205/82478533-ae675180-9a96-11ea-92a9-b417ae00c6e7.png)

{
    "content": {
        "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#directoryObjects",
        "value": [
            {
                "@odata.type": "#microsoft.graph.user",
                "id": "a3282288-11dc-4df9-930b-11751da47f2a",
                "businessPhones": [],
                "displayName": "ScriptAdmin",
                "givenName": null,
                "jobTitle": "Shawn Keifenheim",
                "mail": "ScriptAdmin@schneiderwide.onmicrosoft.com",
                "mobilePhone": null,
                "officeLocation": null,
                "preferredLanguage": null,
                "surname": "ScriptAdmin",
                "userPrincipalName": "ScriptAdmin@schneiderwide.onmicrosoft.com"
            }
        ]
    },
    "schema": {
        "type": "object",
        "properties": {
            "value": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "accountEnabled": {
                            "type": "boolean"
                        },
                        "ageGroup": {},
                        "assignedLicenses": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "disabledPlans": {
                                        "type": "array"
                                    },
                                    "skuId": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "disabledPlans",
                                    "skuId"
                                ]
                            }
                        },
                        "assignedPlans": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "assignedDateTime": {
                                        "type": "string"
                                    },
                                    "capabilityStatus": {
                                        "type": "string"
                                    },
                                    "service": {
                                        "type": "string"
                                    },
                                    "servicePlanId": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "assignedDateTime",
                                    "capabilityStatus",
                                    "service",
                                    "servicePlanId"
                                ]
                            }
                        },
                        "businessPhones": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "city": {},
                        "companyName": {},
                        "consentProvidedForMinor": {},
                        "country": {
                            "type": [
                                "string",
                                "null"
                            ]
                        },
                        "createdDateTime": {
                            "type": "string"
                        },
                        "creationType": {},
                        "deletedDateTime": {},
                        "department": {},
                        "deviceKeys": {
                            "type": "array"
                        },
                        "displayName": {
                            "type": "string"
                        },
                        "employeeId": {},
                        "externalUserState": {},
                        "externalUserStateChangeDateTime": {},
                        "faxNumber": {},
                        "givenName": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        },
                        "identities": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "issuer": {
                                        "type": "string"
                                    },
                                    "issuerAssignedId": {
                                        "type": "string"
                                    },
                                    "signInType": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "signInType",
                                    "issuer",
                                    "issuerAssignedId"
                                ]
                            }
                        },
                        "imAddresses": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "isResourceAccount": {},
                        "jobTitle": {},
                        "legalAgeGroupClassification": {},
                        "mail": {
                            "type": "string"
                        },
                        "mailNickname": {
                            "type": "string"
                        },
                        "mobilePhone": {
                            "type": [
                                "string",
                                "null"
                            ]
                        },
                        "officeLocation": {},
                        "onPremisesDistinguishedName": {},
                        "onPremisesDomainName": {},
                        "onPremisesExtensionAttributes": {
                            "type": "object",
                            "properties": {
                                "extensionAttribute1": {},
                                "extensionAttribute10": {},
                                "extensionAttribute11": {},
                                "extensionAttribute12": {},
                                "extensionAttribute13": {},
                                "extensionAttribute14": {},
                                "extensionAttribute15": {},
                                "extensionAttribute2": {},
                                "extensionAttribute3": {},
                                "extensionAttribute4": {},
                                "extensionAttribute5": {},
                                "extensionAttribute6": {},
                                "extensionAttribute7": {},
                                "extensionAttribute8": {},
                                "extensionAttribute9": {}
                            }
                        },
                        "onPremisesImmutableId": {},
                        "onPremisesLastSyncDateTime": {},
                        "onPremisesProvisioningErrors": {
                            "type": "array"
                        },
                        "onPremisesSamAccountName": {},
                        "onPremisesSecurityIdentifier": {},
                        "onPremisesSyncEnabled": {},
                        "onPremisesUserPrincipalName": {},
                        "otherMails": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "passwordPolicies": {},
                        "passwordProfile": {},
                        "postalCode": {},
                        "preferredDataLocation": {},
                        "preferredLanguage": {
                            "type": [
                                "string",
                                "null"
                            ]
                        },
                        "provisionedPlans": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "capabilityStatus": {
                                        "type": "string"
                                    },
                                    "provisioningStatus": {
                                        "type": "string"
                                    },
                                    "service": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "capabilityStatus",
                                    "provisioningStatus",
                                    "service"
                                ]
                            }
                        },
                        "proxyAddresses": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "refreshTokensValidFromDateTime": {
                            "type": "string"
                        },
                        "showInAddressList": {},
                        "signInSessionsValidFromDateTime": {
                            "type": "string"
                        },
                        "state": {},
                        "streetAddress": {},
                        "surname": {
                            "type": "string"
                        },
                        "usageLocation": {
                            "type": "string"
                        },
                        "userPrincipalName": {
                            "type": "string"
                        },
                        "userType": {
                            "type": "string"
                        },
                        "@odata.type": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "@odata.type",
                        "id"
                    ]
                }
            },
            "@odata.context": {
                "type": "string"
            }
        }
    }
}

**Comment by neimadpc** [comment]
New error post pull request - Parse team owners JSON:

![image](https://user-images.githubusercontent.com/65623205/82486949-3fdcc080-9aa3-11ea-82fe-07021972fde3.png)

**Comment by neimadpc** [comment]
@alexc-MSFT 
This was resolved by populating givenName attribute on the service account I created. I should note that now the 2nd owner from request was added as member, not owner. There were no members provided in my request.

**Comment by alexc-MSFT** [comment]
> @alexc-MSFT
> This was resolved by populating givenName attribute on the service account I created. I should note that now the 2nd owner from request was added as member, not owner. There were no members provided in my request.

Ok great, glad it's resolved. I will make a change however to allow nulls for the givenName just in case.

The 2nd owner should be added as a member and also as an owner, there may be a delay in the syncronisation.

This is because owners also need to be members in order to add Planner Plans.

**Comment by alexc-MSFT** [comment]
@neimadpc see new issue and pull request to fix this - https://github.com/OfficeDev/microsoft-teams-apps-requestateam/issues/35
