### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by Fjsinfo** [OfficeDev/microsoft-teams-apps-requestateam#260]
Hi all !!!

Very thanks for this development.
However, I have several mistakes.
In Teams, when I create a team request, on the Add members screen, I have nothing in the Owners and members drop down lists.
![2021-05-03_15h56_35](https://user-images.githubusercontent.com/80530781/116885407-2424e880-ac28-11eb-9a2f-1e6e963f234d.png)

![2021-05-03_15h58_53](https://user-images.githubusercontent.com/80530781/116885730-8251cb80-ac28-11eb-8f79-5b2f158e3ab8.png)

In PowerApps, all 'Created by'.Email are in error
![2021-05-03_15h55_54](https://user-images.githubusercontent.com/80530781/116885330-0f485500-ac28-11eb-9b34-609274c8aa2a.png)

Thank you in advance for your help.
And again, thank you for your work

**Comment by alexc-MSFT** [comment]
This should now be fixed
