### ISSUE TITLE
No post in Admins team

### ISSUE THREAD

**Issue by Cyrille63** [OfficeDev/microsoft-teams-apps-requestateam#269]
Hi,

We have approvale requests but no message in the admins team of Teams

![image](https://user-images.githubusercontent.com/61985093/121349917-56fa8480-c92a-11eb-9426-5cb794b247ba.png)

![image](https://user-images.githubusercontent.com/61985093/121350053-798c9d80-c92a-11eb-9cbe-19798426f5cc.png)

I have not seen this problem in the issues

Thanks for your help
Cyrille

**Comment by Jonroberts84** [comment]
Same here - can you let me know if you resolved?

**Comment by alexc-MSFT** [comment]
Closed due to inactivity - reopen if required
