### ISSUE TITLE
Subscription Type Not Permitted

### ISSUE THREAD

**Issue by mhodgson3** [OfficeDev/microsoft-teams-apps-requestateam#271]
Hi, I have tried to run the deployment script and am getting an error about the subscription type not being permitted. I have contacted Microsoft support and they said that our Tenant was setup correctly. Any ideas what the problem may be?

Thanks for any help that you can provide.

![teams powershell error](https://user-images.githubusercontent.com/6852689/122564443-412d4380-d03d-11eb-9d72-0a986093fac9.jpg)

**Comment by alexc-MSFT** [comment]
Closed due to inactivity - reopen if required
