### ISSUE TITLE
When a requested team in created in teams, channels and apps are not created from Admin center template

### ISSUE THREAD

**Issue by KaniNous** [OfficeDev/microsoft-teams-apps-requestateam#272]
I tried to create a template type team request. Team is getting created in MS Teams, but admin center template's channels and apps are not added to created team. 

Below are the channels and apps available in Teams admin center for 'Incident Response' template.

![ChannelsApps](https://user-images.githubusercontent.com/86357291/123141917-88b93280-d476-11eb-9432-37adfd8f9319.png)

After team is created, below are the channels shown.
![Channels](https://user-images.githubusercontent.com/86357291/123141939-8ce55000-d476-11eb-88cf-e711f866d971.png)

Below are the apps shown.
![Apps](https://user-images.githubusercontent.com/86357291/123141964-953d8b00-d476-11eb-95a1-eb3256887015.png)

Can anyone help on this?

**Comment by alexc-MSFT** [comment]
Closed due to inactivity - reopen if required
