### ISSUE TITLE
CheckSiteExists Logic App issue when checking SharePoint

### ISSUE THREAD

**Issue by therockett** [OfficeDev/microsoft-teams-apps-requestateam#276]
During the actions "Check if site collection exists" and "Get Site Collection from Recycle Bin" I am getting the following errors. 

I have followed the steps and made sure to Trust the app in SharePoint. 

{
    "statusCode": 403,
    "headers": {
        "X-SharePointHealthScore": "3",
        "x-ms-diagnostics": "3002002; reason=App principal does not exist",
        "SPRequestGuid": "7a04d79f-d07f-0000-cdf8-f91152b1fe83",
        "request-id": "7a04d79f-d07f-0000-cdf8-f91152b1fe83",
        "MS-CV": "n9cEen/QAADN+PkRUrH+gw.0",
        "Strict-Transport-Security": "max-age=31536000",
        "X-FRAME-OPTIONS": "SAMEORIGIN",
        "MicrosoftSharePointTeamServices": "16.0.0.21416",
        "X-Content-Type-Options": "nosniff",
        "X-MS-InvokeApp": "1; RequireReadOnly",
        "Cache-Control": "private",
        "Date": "Wed, 30 Jun 2021 18:07:33 GMT",
        "P3P": "CP=\"ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI\"",
        "Set-Cookie": "SPWorkLoadAttribution=Url=https://TENANT-admin.sharepoint.com/_vti_bin/client.svc/ProcessQuery&AppId=E0D3C05D-9133-40D1-8413-1C4522A4E7C2; expires=Wed, 30-Jun-2021 18:08:03 GMT; path=/",
        "Server": "Microsoft-IIS/10.0",
        "X-AspNet-Version": "4.0.30319",
        "X-Powered-By": "ASP.NET",
        "Content-Length": "0"
    }
}

![image](https://user-images.githubusercontent.com/70723803/124010715-cb15ce80-d9a4-11eb-8280-cf7e2ad79e12.png)

**Comment by siebrenaarts** [comment]
I have the same issue

**Comment by n-tripathi** [comment]
I'm facing the same issue, can anyone help us with the solution?

**Comment by Karlmit** [comment]
I am having the same issue.
