### ISSUE TITLE
"Check Team Availability" flow missing

### ISSUE THREAD

**Issue by aimarpl** [OfficeDev/microsoft-teams-apps-requestateam#278]
Hi, documentation states that there should be at least two flows after importing .zip file, but all I'm getting is single flow named "Team Request Approval". Where should I get "check team availability" flow from?

Docu:
Step 4: Set up Power Automate
**Repeat the above process for the Check Team Availability flow**. Update the SharePoint site address for steps

**Comment by dhx10000** [comment]
I have the same question that is here, I do not see a CHECK TEAM AVAILABILITY FLOW. I see this issue is closed. Where is that flow? Or is the documentation just out dated and there is no CHECK TEAM AVAILABILITY FLOW?

**Comment by noudvanzwam** [comment]
@aimarpl  Have you found it? Where?
