### ISSUE TITLE
Can't find Check Team Availability flow

### ISSUE THREAD

**Issue by HaiyeWang0717** [OfficeDev/microsoft-teams-apps-requestateam#28]
I imported flow, but only have Team Request Approval flow, not Check Team Availability flow.

**Comment by alexc-MSFT** [comment]
@HaiyeWang0717 the 'Check Team Availability' flow is imported when you import the Power App package as it is linked to the Power App.

**Comment by HaiyeWang0717** [comment]
> @HaiyeWang0717 the 'Check Team Availability' flow is imported when you import the Power App package as it is linked to the Power App.
Thank you for your reply. I can find it in PowerApps, but not in My flows. How to update the SharePoint site address in the flow.

**Comment by HaiyeWang0717** [comment]
Found it. Thank you.
