### ISSUE TITLE
Can't click Next after Team Information screen

### ISSUE THREAD

**Issue by bedwell84** [OfficeDev/microsoft-teams-apps-requestateam#285]
I cannot click Next when building a Team from scratch after checking availability, filling in description and business reason. I don't get an error, the button just does nothing. I have the same issue when attempting to create a Team from a template I cannot click next past the first screen.
How do I troubleshoot this?

**Comment by bedwell84** [comment]
I checked in PowerApps Monitor and I can see that the btnNextTeamInformation button is running successfully with OnSelect, but doing nothing. With the previous screen where you set the team classification, the btnNextClassification also runs and then has a second event where it creates a row in the Teams Requests list and submits the form. 
This is the code I think should move to the next screen. I've tried removing the IF statement around it to force it to run with OnSelect but it still doesn't move to the next screen

If(
    (gblSiteExistsOutputs.teamexists = "False" && gblSiteExistsOutputs.requestexists = "False") && (!IsBlank(Trim('txtinpBusinessReason.'.Text))) && (!IsBlank(Trim('txtinpTeamDescription.'.Text))),
    UpdateContext({ScratchlocalStep: ScratchlocalStep + 1}) && Set(
        BNTeamInformation,
        false
    ) && Set(
        BNMembership,
        true
    )
);

**Comment by OliverR-82** [comment]
I think this is because of the missing "Check Team Availability" flow that is mentioned in the deployment guide but is missing from the package. At least that's what the problem is for me.

The 'Next' buttons depend on the result of that flow. You can change the code in the DisplayMode and OnSelect properties of the 'Next' buttons to leave the references to the missing flow out.

**Comment by alexc-MSFT** [comment]
@bedwell84 @OliverR-82 please go into the Power Apps portal > Flows, you will find the Check Team Availability flow in there. Then please update the values in there as per the deployment guide.

**Comment by OliverR-82** [comment]
> @bedwell84 @OliverR-82 please go into the Power Apps portal > Flows, you will find the Check Team Availability flow in there. Then please update the values in there as per the deployment guide.

Hi @alexc-MSFT , thank you for your reply. However, the 'Check Team Availability' flow doesn't seem to be included in the downloaded .zip file. Also see my reply to [issue 281](https://github.com/OfficeDev/microsoft-teams-apps-requestateam/issues/281).

**Comment by Bjurenfors** [comment]
I had the same sort of issue, although Check Team Availability worked fine. It turned out to be a SharePoint column issue as Team Name was missing. The Title column is reused for Team Name but had not been renamed during deployment. Renaming the column under list settings solved the issue for me.
