### ISSUE TITLE
The Setting UseNamingConventions is case sensitive

### ISSUE THREAD

**Issue by gentoouser** [OfficeDev/microsoft-teams-apps-requestateam#300]
Was having issue when I enabled "UseNamingConventions" setting as I used "True" instead of "true".  Please make the "UseNamingConventions" case insensitive to help reduce issues like this.

**Comment by alexc-MSFT** [comment]
@gentoouser  Thanks for the heads up, this is now fixed and is case insensitive

**Comment by oo0JeZ0oo** [comment]
I just deployed the app today and everything worked flawlessly except I found that to get Naming Conventions to work the global value for **UseNamingConventions** must be set to "true" - case sensitive.  Editing the item in Modern SharePoint view would always capitalise the value to "True".  I had to switch to Classic SharePoint view for the list to be able to edit the value to "true" and have it save.  Once that was done the Naming Conventions began to work as documented.
