### ISSUE TITLE
The response is not in JSON format

### ISSUE THREAD

**Issue by MaxwellvDijk** [OfficeDev/microsoft-teams-apps-requestateam#304]
Hi all,

I have just implemented the Request-a-team app and now i am trying to open it under a normal user.
When i open the app i immediately see a error on top.
![image](https://user-images.githubusercontent.com/91314667/134644112-a68ca50e-4b94-42a5-b606-db8d5c2ee884.png)

In English its saying:
The gave up record is not found. Serveranswer: Team Request Settings failed. The response is not in JSON format.

When i choose the option 'From Scratch', i see it also and i am not able to use the dropdown 'Visibility' in the first step.

Anyone any idea?

**Comment by alexc-MSFT** [comment]
@MaxwellvDijk Did you follow the step to **remove** the existing data sources from the Power App and re-add these, pointing at your SharePoint site? That may be your issue.

**Comment by MaxwellvDijk** [comment]
Hi Alexc-MSFT, thank you for your quick reply.
I saw that step, but i couldn't find any demo resources.
I have checked again and this is what i see.

![image](https://user-images.githubusercontent.com/91314667/134797463-e7f47d65-9b32-4fd6-8f98-4027f9492c05.png)
![image](https://user-images.githubusercontent.com/91314667/134797476-77c1d974-1f99-48a4-84c3-a9564991c6a7.png)

**Comment by MaxwellvDijk** [comment]
@alexc-MSFT did you see my last post last week?

**Comment by alexc-MSFT** [comment]
Closed due to inactivity - reopen if required
