### ISSUE TITLE
Cloning a team that was created using a template marks "Admin Center Template" as false and Team creation fails

### ISSUE THREAD

**Issue by krwilson-msft** [OfficeDev/microsoft-teams-apps-requestateam#305]
When creating a team from a template the SP list parameter "Admin Center Template" is marked as true and Team creation succeeds. 

When we then clone that team from the "My Requests" page the "Admin Center Template" parameter is marked as false which leads to a failure in creating the Team in the Process teams Request logic App (Under step Create Team > Check template type)

**Comment by alexc-MSFT** [comment]
This is now fixed, see latest PR - https://github.com/OfficeDev/microsoft-teams-apps-requestateam/pull/306
