### ISSUE TITLE
Team creation fails after several months - Unauthorized (get client id step)

### ISSUE THREAD

**Issue by thondal-evry** [OfficeDev/microsoft-teams-apps-requestateam#309]
It has been working for several weeks but has now suddenly stopped on the step "get client id" with the following error : Unauthorized. 
{
  "status": 401,
  "message": "Operation failed because client does not have permission to perform the operation on the key vault. Please check your permissions in the key vault access policies https://docs.microsoft.com/en-us/azure/key-vault/general/assign-access-policy-portal.\r\nclientRequestId: 75738da4-9fb4-4959-a4d9-cb2293479274",
  "error": {
    "message": "Operation failed because client does not have permission to perform the operation on the key vault. Please check your permissions in the key vault access policies https://docs.microsoft.com/en-us/azure/key-vault/general/assign-access-policy-portal."
  },
  "source": "keyvault-ne.azconn-ne.p.azurewebsites.net"
}

**Comment by ejbenke** [comment]
We ran into the same exact error within that same action (Get Client ID) in the _ProcessTeamRequest_ Logic App.

It was related to the secret for our key vault expiring after a year.  We followed the instructions provided in the link below for refreshing the secret.
https://github.com/OfficeDev/microsoft-teams-apps-requestateam/wiki/Refreshing-Expired-Secrets

That resolved the issue for us.

**Comment by alexc-MSFT** [comment]
Closed due to inactivity - reopen if required
