### ISSUE TITLE
Sharepoint List not created

### ISSUE THREAD

**Issue by PHARKETT** [OfficeDev/microsoft-teams-apps-requestateam#31]
I have run the deploy.ps1 script and it finished without any errors but on verifying the SharePoint site creation, teh site was created but there are no lists under site Content.

Do I have to rerun the install or can I create the lists manually? 

If I have to rerun the script so I have to delete anything?

**Comment by alexc-MSFT** [comment]
@PHARKETT are you sure there were no errors? The script applies a PnP provisioning template which contains the lists so they should be there.

If you need to re-run, please delete the Resource Group that was created in Azure and also use a new name for the SharePoint site.

**Comment by PHARKETT** [comment]
I rerun the script and yes sorry there was an error 
Connect-PnPOnline : The 'Connect-PnPOnline' command was found in the module 'SharePointPnPPowerShellOnline', but the module could not be loaded. For more information, 
run 'Import-Module SharePointPnPPowerShellOnline'.
At C:\Admin\Deployment\Scripts\deploy.ps1:643 char:15
+ $pnpConnect = Connect-PnPOnline -Url $tenantAdminUrl -UseWebLogin
+               ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Connect-PnPOnline:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule


I have tried uninstalling all SharePoint related modules but I still get this error

**Comment by alexc-MSFT** [comment]
> @alexc-MSFT I rerun the script and yes sorry there was an error
> Connect-PnPOnline : The 'Connect-PnPOnline' command was found in the module 'SharePointPnPPowerShellOnline', but the module could not be loaded. For more information,
> run 'Import-Module SharePointPnPPowerShellOnline'.
> At C:\Admin\Deployment\Scripts\deploy.ps1:643 char:15
> 
> * $pnpConnect = Connect-PnPOnline -Url $tenantAdminUrl -UseWebLogin
> * ```
>             ~~~~~~~~~~~~~~~~~
>   ```
>   
>   
>   
>   * CategoryInfo          : ObjectNotFound: (Connect-PnPOnline:String) [], CommandNotFoundException
>   * FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
> 
> I have tried uninstalling all SharePoint related modules but I still get this error

Please try uninstalling PnP with the -Force parameter and reinstall with -Force and see if this works.

Thanks

**Comment by alexc-MSFT** [comment]
Closing this issue due to lack of response.
