### ISSUE TITLE
Access is denied. (deploy.ps1:352 char:9)

### ISSUE THREAD

**Issue by ronaldbok** [OfficeDev/microsoft-teams-apps-requestateam#314]
Hello i Just try to execute the script with release date 27 Sept 2021 (Why are all scripts release version 1.0?) and get the following error

Applying provisioning template...
WARNING: ListInstance Style Library is a Style Library of a site with NoScript enabled and will be skipped
Invoke-PnPSiteTemplate : Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
At C:\tempjes\microsoft-teams-apps-requestateam-master\Deployment\Scripts\deploy.ps1:352 char:9
+         Invoke-PnPSiteTemplate -Path (Join-Path $packageRootPath $tem ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Invoke-PnPSiteTemplate], ServerUnauthorizedAccessException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Site.InvokeSiteTemplate
Applied template
Added settings to Site Requests Settings list
Added templates to Teams Templates list
Adding Service Account to Owners group
Error occured while configuring the SharePoint site: Cannot bind argument to parameter 'Group' because it is null.
### AZURE RESOURCES DEPLOYMENT ###

Can someone help me to solve this error ?

**Comment by alexc-MSFT** [comment]
@ronaldbok please try again as now we use 1.8.0 of the PnP module.

Regarding versioning, this is a good point - we will look to put a version number in the script going forward.
