### ISSUE TITLE
Error in the Request-a-team Tab in Teams with Office365Groups.ListGroupMembers

### ISSUE THREAD

**Issue by lre871** [OfficeDev/microsoft-teams-apps-requestateam#315]
Hi, 

this is my issue with the teams app:
![image](https://user-images.githubusercontent.com/55531023/136914854-2dbee67a-e041-4261-a165-9b467810e0e9.png)

i have tried to install the app with the deployment guide and while deploying it everything worked fine, exept one error message in the powershell output:

WARNUNG: ListInstance Style Library is a Style Library of a site with NoScript enabled and will be skipped
Invoke-PnPSiteTemplate : Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
In C:\tfs\microsoft-teams-apps-requestateam\Deployment\Scripts\deploy.ps1:361 Zeichen:9
         Invoke-PnPSiteTemplate -Path (Join-Path $packageRootPath $tem ...
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : WriteError: (:) [Invoke-PnPSiteTemplate], ServerUnauthorizedAccessException
     FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Site.InvokeSiteTemplate 

**I dont know if this is the reason for the error i have in teams tab:**

×
Error with "Office365Groups.ListGroupMembers": 
{ "error": { "code": "Request_ResourceNotFound", 
"message": "Resource '05d73b8d-a3d1-4eaf-8c7d-7593d6e35c33'
 does not exist or one of its queried reference-property objects
 are not present.", "innerError": { "date": "2021-10-12T07:35:40",
 "request-id": "1fc6e199-0db9-4046-b01d-e4f0011b1552", 
"client-request-id": "1fc6e199-0db9-4046-b01d-e4f0011b1552" } } }

This error message is shown if i open the teams tab. 

I hope someone can help me to fix this issue because  I dont know how to do this.
Thank you

**Comment by alexc-MSFT** [comment]
@lre871 It is likely you missed the step to update the code in the OnStart method of the Power App to replace the guid with an id of a group in your organisation. Did you carry out this step?

**Comment by alexc-MSFT** [comment]
Closed due to inactivity - reopen if required
