### ISSUE TITLE
Azure tenant different than Office 365 tenant

### ISSUE THREAD

**Issue by glblinck** [OfficeDev/microsoft-teams-apps-requestateam#317]
The documentation states that the Azure subscription for the solution needs to be the same as the Office 365 tenant. Would there be any way to enhance this app to support split-tenants, where the Azure portion runs using a separate subscription than the Office tenant?

- SubscriptionId - Azure subscription to deploy the solution to (MUST be associated with the Azure AD of the Office 365 tenant that you wish to deploy this solution to.)

**Comment by alexc-MSFT** [comment]
@glblinck sorry for the delay in getting back to you. I've not explored this but I guess it's possible, will be one to investigate but it's not on the immediate roadmap I'm afraid.
