### ISSUE TITLE
Logic App Failed - Add Members and Owners

### ISSUE THREAD

**Issue by neimadpc** [OfficeDev/microsoft-teams-apps-requestateam#32]
Parse team owners JSON:

![image](https://user-images.githubusercontent.com/65623205/82479397-ede26d80-9a97-11ea-8801-e98cb58e7bfd.png)

**Comment by alexc-MSFT** [comment]
@neimadpc please can you send the exact error. I suspect this is because a user in the tenant who has been entered as an owner has a missing property.

**Comment by neimadpc** [comment]
> @neimadpc please can you send the exact error. I suspect this is because a user in the tenant who has been entered as an owner has a missing property.

@alexc-MSFT 
{
    "content": {
        "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#directoryObjects",
        "value": [
            {
                "@odata.type": "#microsoft.graph.user",
                "id": "a3282288-11dc-4df9-930b-11751da47f2a",
                "businessPhones": [],
                "displayName": "xxx",
                "givenName": null,
                "jobTitle": "xxx xxx",
                "mail": "xxx@xxx.onmicrosoft.com",
                "mobilePhone": null,
                "officeLocation": null,
                "preferredLanguage": null,
                "surname": "xxx",
                "userPrincipalName": "xxx@xxx.onmicrosoft.com"
            }
        ]
    },
    "schema": {
        "type": "object",
        "properties": {
            "value": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "accountEnabled": {
                            "type": "boolean"
                        },
                        "ageGroup": {},
                        "assignedLicenses": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "disabledPlans": {
                                        "type": "array"
                                    },
                                    "skuId": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "disabledPlans",
                                    "skuId"
                                ]
                            }
                        },
                        "assignedPlans": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "assignedDateTime": {
                                        "type": "string"
                                    },
                                    "capabilityStatus": {
                                        "type": "string"
                                    },
                                    "service": {
                                        "type": "string"
                                    },
                                    "servicePlanId": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "assignedDateTime",
                                    "capabilityStatus",
                                    "service",
                                    "servicePlanId"
                                ]
                            }
                        },
                        "businessPhones": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "city": {},
                        "companyName": {},
                        "consentProvidedForMinor": {},
                        "country": {
                            "type": [
                                "string",
                                "null"
                            ]
                        },
                        "createdDateTime": {
                            "type": "string"
                        },
                        "creationType": {},
                        "deletedDateTime": {},
                        "department": {},
                        "deviceKeys": {
                            "type": "array"
                        },
                        "displayName": {
                            "type": "string"
                        },
                        "employeeId": {},
                        "externalUserState": {},
                        "externalUserStateChangeDateTime": {},
                        "faxNumber": {},
                        "givenName": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        },
                        "identities": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "issuer": {
                                        "type": "string"
                                    },
                                    "issuerAssignedId": {
                                        "type": "string"
                                    },
                                    "signInType": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "signInType",
                                    "issuer",
                                    "issuerAssignedId"
                                ]
                            }
                        },
                        "imAddresses": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "isResourceAccount": {},
                        "jobTitle": {},
                        "legalAgeGroupClassification": {},
                        "mail": {
                            "type": "string"
                        },
                        "mailNickname": {
                            "type": "string"
                        },
                        "mobilePhone": {
                            "type": [
                                "string",
                                "null"
                            ]
                        },
                        "officeLocation": {},
                        "onPremisesDistinguishedName": {},
                        "onPremisesDomainName": {},
                        "onPremisesExtensionAttributes": {
                            "type": "object",
                            "properties": {
                                "extensionAttribute1": {},
                                "extensionAttribute10": {},
                                "extensionAttribute11": {},
                                "extensionAttribute12": {},
                                "extensionAttribute13": {},
                                "extensionAttribute14": {},
                                "extensionAttribute15": {},
                                "extensionAttribute2": {},
                                "extensionAttribute3": {},
                                "extensionAttribute4": {},
                                "extensionAttribute5": {},
                                "extensionAttribute6": {},
                                "extensionAttribute7": {},
                                "extensionAttribute8": {},
                                "extensionAttribute9": {}
                            }
                        },
                        "onPremisesImmutableId": {},
                        "onPremisesLastSyncDateTime": {},
                        "onPremisesProvisioningErrors": {
                            "type": "array"
                        },
                        "onPremisesSamAccountName": {},
                        "onPremisesSecurityIdentifier": {},
                        "onPremisesSyncEnabled": {},
                        "onPremisesUserPrincipalName": {},
                        "otherMails": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "passwordPolicies": {},
                        "passwordProfile": {},
                        "postalCode": {},
                        "preferredDataLocation": {},
                        "preferredLanguage": {
                            "type": [
                                "string",
                                "null"
                            ]
                        },
                        "provisionedPlans": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "capabilityStatus": {
                                        "type": "string"
                                    },
                                    "provisioningStatus": {
                                        "type": "string"
                                    },
                                    "service": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "capabilityStatus",
                                    "provisioningStatus",
                                    "service"
                                ]
                            }
                        },
                        "proxyAddresses": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "refreshTokensValidFromDateTime": {
                            "type": "string"
                        },
                        "showInAddressList": {},
                        "signInSessionsValidFromDateTime": {
                            "type": "string"
                        },
                        "state": {},
                        "streetAddress": {},
                        "surname": {
                            "type": "string"
                        },
                        "usageLocation": {
                            "type": "string"
                        },
                        "userPrincipalName": {
                            "type": "string"
                        },
                        "userType": {
                            "type": "string"
                        },
                        "@odata.type": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "@odata.type",
                        "id"
                    ]
                }
            },
            "@odata.context": {
                "type": "string"
            }
        }
    }
}

**Comment by neimadpc** [comment]
@alexc-MSFT 
{
    "errors": [
        {
            "message": "Invalid type. Expected String but got Null.",
            "lineNumber": 0,
            "linePosition": 0,
            "path": "value[0].givenName",
            "schemaId": "#/properties/value/items/properties/givenName",
            "errorType": "type",
            "childErrors": []
        }
    ]
}

Looks like you're correct, cant have null for givenName...

**Comment by neimadpc** [comment]
@alexc-MSFT 
The service account I created for the connections was missing the GivenName... A new requirement.. :)

It's working now, thanks!

**Comment by demesg** [comment]
The service account also needs a createdDateTime value.. 

`[
  {
    "message": "Invalid type. Expected String but got Null.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "value[0].createdDateTime",
    "schemaId": "#/properties/value/items/properties/createdDateTime",
    "errorType": "type",
    "childErrors": []
  }
]`
