### ISSUE TITLE
Unable to click 'next' button after filling in team info

### ISSUE THREAD

**Issue by curtishale** [OfficeDev/microsoft-teams-apps-requestateam#324]
After filling in the team name, selecting 'check availability' and entering the description, the next button becomes clickable, but after clicking, nothing happens.

Microsoft have said they see no issues their end and to contact here.

**Comment by alexc-MSFT** [comment]
@curtishale have you got any further with this? I think I responded to support internally. Thanks

**Comment by curtishale** [comment]
Oh, hi Alex!

Sorry, we’ve not been able to test it just yet.

@Matthew ***@***.***> – When you can, please could you do as I mentioned before;


  *   Open the code for the app
  *   Run it in the editor and go through the process
  *   Stop it right after getting to the spot that it doesn’t work (when hitting next after entering name of the team)
  *   See if there’s any errors in the code there

Feel free to let me know if you want me to join you doing this.

Kind Regards,
Curtis Hale
IT Support Analyst II/Business Analyst , ETS
Pronouns: He/Him
Office: 604.694.8028

[Chrysalis]<https://www.chrysalis.co/> [iQmetrix] <https://www.iqmetrix.com/>  [Cova] <https://www.covasoftware.com/>  [Ready] <https://readytopay.com/>  [Shiftlab] <https://shiftlab.io/>

**Comment by curtishale** [comment]
These are the following errors we see in the code.
Also attached is a run through with the monitoring going.


***@***.***
***@***.***
***@***.***

Matthew Vinck
Network Administrator

CCNA, Sec+, Net+, NSE Associate
Extension: 1.866.476.3874 EXT 2608
Direct: 204.594.3501

[Chrysalis]<https://www.chrysalis.co/>[iQmetrix]<https://www.iqmetrix.com/>[Cova]<https://www.covasoftware.com/>[Ready]<https://readytopay.com/>[Shiftlab]<https://shiftlab.io/>

From: Curtis Hale ***@***.***>
Sent: November 2, 2021 5:43 PM
To: OfficeDev/microsoft-teams-apps-requestateam ***@***.***>; OfficeDev/microsoft-teams-apps-requestateam ***@***.***>; Matthew Vinck ***@***.***>
Cc: Mention ***@***.***>; Devin Martinson ***@***.***>
Subject: RE: [OfficeDev/microsoft-teams-apps-requestateam] Unable to click 'next' button after filling in team info (Issue #324)

Oh, hi Alex!

Sorry, we’ve not been able to test it just yet.

@Matthew ***@***.***> – When you can, please could you do as I mentioned before;


  *   Open the code for the app
  *   Run it in the editor and go through the process
  *   Stop it right after getting to the spot that it doesn’t work (when hitting next after entering name of the team)
  *   See if there’s any errors in the code there

Feel free to let me know if you want me to join you doing this.

Kind Regards,
Curtis Hale
IT Support Analyst II/Business Analyst , ETS
Pronouns: He/Him
Office: 604.694.8028

[Chrysalis]<https://www.chrysalis.co/> [iQmetrix] <https://www.iqmetrix.com/>  [Cova] <https://www.covasoftware.com/>  [Ready] <https://readytopay.com/>  [Shiftlab] <https://shiftlab.io/>

**Comment by MelinaDevAdmin** [comment]
Did you manage to solve this issue?  I am running on the same. Check Availability works, but then after clicking "Next" it just don't do anything...

**Comment by curtishale** [comment]
Hi there!

I didn’t. I’m waiting on a response from the creator.

Kind Regards,
Curtis Hale
IT Support Analyst II/Business Analyst , ETS
Pronouns: He/Him
Office: 604.694.8028

[Chrysalis]<https://www.chrysalis.co/> [iQmetrix] <https://www.iqmetrix.com/>  [Cova] <https://www.covasoftware.com/>  [Ready] <https://readytopay.com/>  [Shiftlab] <https://shiftlab.io/>

**Comment by alexc-MSFT** [comment]
@curtishale I have responded to you from my work email, let's continue on there and I will close this thread out.
