### ISSUE TITLE
Error when starting Request a Teams App - Office365Groups.ListGroupMembers error messa

### ISSUE THREAD

**Issue by ChristianHoffmannn** [OfficeDev/microsoft-teams-apps-requestateam#325]
Hello together,

i just deployed the Request a Team App in a customer tenant and used the instructions from here for that:
https://github.com/OfficeDev/microsoft-teams-apps-requestateam/wiki/Deployment-guide

The script worked fine except for a warning message:
WARNUNG: ListInstance Style Library is a Style Library of a site with NoScript enabled and will be skipped
Invoke-PnPSiteTemplate : Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
In C:\tfs\microsoft-teams-apps-requestateam\Deployment\Scripts\deploy.ps1:361 Zeichen:9
Invoke-PnPSiteTemplate -Path (Join-Path $packageRootPath $tem ...

CategoryInfo : WriteError: (:) [Invoke-PnPSiteTemplate], ServerUnauthorizedAccessException
FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Site.InvokeSiteTemplate

Now when we start the request a team app we get the following error message:
![error message request a teams app](https://user-images.githubusercontent.com/93382975/139433143-330fecb0-74ac-417b-a9a0-037cbb114024.png)

We also deployed the app in a test tenant before and there we are getting the same error.

Does anyone else have seen this error before?
Or has a tipp what to do?

Kind regards

Christian

**Comment by alexc-MSFT** [comment]
@ChristianHoffmannn so your first error is likely related to the PnP Powershell module which has been a bit of a sticking point due to bugs.

I would uninstall all versions of PnP on your machine - 

Uninstall-Module PnP.PowerShell -AllVersions -Force

Then re-run the script and it will install the latest one.

With regards to the app error, there is a line of code in the OnStart function where you specify the ID of an O365 group for Request-a-team admins (these users can see the Approve requests tab). It is likely you have not updated that ID.

HTH

Thanks

**Comment by ChristianHoffmannn** [comment]
> 
> 
> @ChristianHoffmannn so your first error is likely related to the PnP Powershell module which has been a bit of a sticking point due to bugs.
> 
> I would uninstall all versions of PnP on your machine -
> 
> Uninstall-Module PnP.PowerShell -AllVersions -Force
> 
> Then re-run the script and it will install the latest one.
> 
> With regards to the app error, there is a line of code in the OnStart function where you specify the ID of an O365 group for Request-a-team admins (these users can see the Approve requests tab). It is likely you have not updated that ID.
> 
> HTH
> 
> Thanks

Which line of code do you mean?

I checked the deployment guide again and found 2 two steps, where you need to enter the groupID.
First one in Team Request Settings in SP and second in step 8 Configuring Power App. In both there is the correct groupID entered.
Or is there a third step, where you need to enter that groupID?

Kind regards

Christian Hoffmann

**Comment by NoMan0013** [comment]
Hi Christian,

Just ran into the same problem, re OnStart function. 
Fix was re-saving and publishing the app again in powerapps.

Regards,

Crumpy

**Comment by ChristianHoffmannn** [comment]
> 
> 
> Hi Christian,
> 
> Just ran into the same problem, re OnStart function. Fix was re-saving and publishing the app again in powerapps.
> 
> Regards,
> 
> Crumpy

Hi Crumpy

thanks for the advice, resaving and publishing the app solved the problem and the app is running without an error know.

Thank you very much!!!

Kind regards

Christian

**Comment by alexc-MSFT** [comment]
Glad to hear this has solved it @ChristianHoffmannn. I will close this issue now.
