### ISSUE TITLE
Team request issue with aesthetic formatting of Privacy setting visibility

### ISSUE THREAD

**Issue by nikki-c** [OfficeDev/microsoft-teams-apps-requestateam#328]
When I start to compete the process to create a new Team and select the drop down arrow for Visibility. The box expands to show the options Private and Public. 
I am getting some strange formatting next to the word 'select' (see image)
![image](https://user-images.githubusercontent.com/69439002/140226051-6481d19e-6783-4427-98da-2cfb4e53151e.png)

after about 30 seconds it changes into a cross (see image)
![image](https://user-images.githubusercontent.com/69439002/140229172-f36c0182-1739-4f40-898a-e40c7d6f07e5.png)

This is just an aesthetic issue and does not impact the outcome

**Comment by alexc-MSFT** [comment]
@nikki-c I've seen this too, I think it's a Power Apps bug.

When I release the new responsive app this hopefully won't be a problem.

Going to close this issue for now.
