### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by OxygenGS** [OfficeDev/microsoft-teams-apps-requestateam#329]
Hey guys,

its pretty complicated if you ask me. Is there no video tutorial i can follow to get this setup?

**Comment by Jonroberts84** [comment]
I agree it is complex, but if you read through it a few times you'll get the hang of it. You may miss steps like adding the Sharepoint URLs, making the correct connections, creating the power apps and flows with the service account etc.

**Comment by alexc-MSFT** [comment]
@OxygenGS we don't have a video tutorial I'm afraid, I will pop this on the roadmap, if you run into issues with the documentation then feel free to raise another issue and we can get the documentation updated. Thanks
