### ISSUE TITLE
Ignoring non letter characters in Team Names

### ISSUE THREAD

**Issue by KYTON06** [OfficeDev/microsoft-teams-apps-requestateam#33]
Hi,

When checking for availability of a team the check ignores Underscore in the Team name

e.g. DPT_Telecoms gets condensed to DPTTelecoms

We already have a large number of teams which follow a naming convention with an underscore and want to avoid Accidental Duplicates as well as maintaining the naming convention.

**Comment by alexc-MSFT** [comment]
> Hi,
> 
> When checking for availability of a team the check ignores Underscore in the Team name
> 
> e.g. DPT_Telecoms gets condensed to DPTTelecoms
> 
> We already have a large number of teams which follow a naming convention with an underscore and want to avoid Accidental Duplicates as well as maintaining the naming convention.

Thanks for this feedback. This can be changed by editing the Power App and updating the validation formula used on the relevant text box. We will consider making this change but the quickest way for now is for you to amend the app as required.

Thanks

**Comment by kireetijs** [comment]
Update the formula of "TextSiteAliasValue_1" in power app (screen - scrnBuildNew) to 
**"DPT-" & Concat(Filter(Split(Substitute(Trim('txtinpTeamName.'.Text)," ","-"),""),IsMatch(Result, "^[a-zA-Z0-9_-]*$")),Result)**

This will prefix the team name with "DPT-" and trims the team name and replaces all spaces with -
