### ISSUE TITLE
Deploy script failed to parse json

### ISSUE THREAD

**Issue by Skivemedprim** [OfficeDev/microsoft-teams-apps-requestateam#333]
Need Help with the script on the step "Creating Azure AD App.
We get the error : Failed to parse JSON: ./manifest.json
: Expecting value: line 1 colun 1 (char 0)

Any ideas?
![Skjermbilde 2021-11-17 151932](https://user-images.githubusercontent.com/94545864/142220802-c08fb84b-e78b-42ea-b30b-d36e5b0864c8.png)

**Comment by acanton5** [comment]
I had the same error you can just continue, it will work

**Comment by alexc-MSFT** [comment]
@Skivemedprim I'm assuming this is caused by an update to the Azure CLI, it clearly still works so for now I will close this issue.

Thanks
