### ISSUE TITLE
ProcessTeamRequest logic app error message

### ISSUE THREAD

**Issue by glblinck** [OfficeDev/microsoft-teams-apps-requestateam#334]
I'm getting this error when the ProcessTeamRequest logic app runs. (I've changed the tenant name and subscription GUIDs to remove identity.) I've checked the API connections and they should all be authenticated properly. I've re-run the connection authorizations, and they all seem to connect just fine. Any idea what is causing this?

{
    "method": "get",
    "path": "/datasets/https%253A%252F%252Fxxxxxx.sharepoint.com%252Fsites%252FRequestateamapp/tables//items",
    "host": {
        "connection": {
            "name": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxxxxxx/resourceGroups/teamsgovernanceapp-rg/providers/Microsoft.Web/connections/requestateam-spo"
        }
    }
}

**Comment by alexc-MSFT** [comment]
Closing as this is now fixed.
