### ISSUE TITLE
Office365Groups.ListGroupMembers failed:

### ISSUE THREAD

**Issue by hadigel** [OfficeDev/microsoft-teams-apps-requestateam#336]
I get the error below when trying to launch the app from Teams.

Office365Groups.ListGroupMembers failed: { "error": { "code": "Request_ResourceNotFound", "message": "Resource '05d73b8d-a3d1-4eaf-8c7d-7593d6e35c33' does not exist or one of its queried reference-property objects are not present.", "innerError": { "date": "2021-11-25T03:21:39", "request-id": "76c572df-981c-4f96-9d97-84c73bc97c31", "client-request-id": "76c572df-981c-4f96-9d97-84c73bc97c31" } } }

**Comment by NoMan0013** [comment]
You need to resave and re-publish the app in powerapps.

**Comment by MelinaDevAdmin** [comment]
Did you manage to resolve this? I am having the exact same problem, and tried republishing the app and still fails. Exactly Same  "Resource '05d73b8d-a3d1-4eaf-8c7d-7593d6e35c33' does not exist

**Comment by NoMan0013** [comment]
Did you complete step 8 of the configuring the app?
https://github.com/OfficeDev/microsoft-teams-apps-requestateam/wiki/Deployment-Guide#configuring-the-power-app

If you havent, you want to update that, then save and republish the app. Its what fixed it for me.

**Comment by alexc-MSFT** [comment]
@hadigel you need to make sure you replace that GUID with a valid id of an O365 group in your tenant, then save and republish the Power App and the error should disappear.

**Comment by MelinaDevAdmin** [comment]
Hello, 
I have all this set up correctly. Group ID and Channel....Tried published again and yet the same problem

**Comment by glblinck** [comment]
> Hello, I have all this set up correctly. Group ID and Channel....Tried published again and yet the same problem

I had the same error. I had to go into the versions and delete all the old versions. Then I saved and republished and it worked. It took some trying. It seemed like an old version was cached.

**Comment by alexc-MSFT** [comment]
Is this still causing you issues @MelinaDevAdmin ? Have you deleted the old versions as @glblinck stated?

**Comment by alexc-MSFT** [comment]
Closed due to inactivity - reopen if required
