### ISSUE TITLE
Possibility to delete message from old requests in admin group

### ISSUE THREAD

**Issue by ChristianHoffmannn** [OfficeDev/microsoft-teams-apps-requestateam#338]
Hello together,

I'm working with the request a team App. Is it possible to delete the messages from Power Automate in the Teams Admin Group?
![grafik](https://user-images.githubusercontent.com/93382975/149943429-bfa518aa-35aa-4060-abc1-51527f524f97.png)

I found out that when i delete the request in the team requests sharepoint list, that the request in the app is deleted.
But in the teams admin group it is still there.

Is it possible to also delete them there?

Kind regards

Christian

**Comment by alexc-MSFT** [comment]
@ChristianHoffmannn I'm afraid this isn't possible, It's an out of the box limitation, see - https://powerusers.microsoft.com/t5/Power-Automate-Ideas/Delete-Bot-Message-in-Microsoft-Teams/idi-p/586699.

I'm going to close this issue as unfortunately it's not supported.

Thanks
