### ISSUE TITLE
Re-naming the bot notification that alerts the users of being added to the Team

### ISSUE THREAD

**Issue by laurenmason2** [OfficeDev/microsoft-teams-apps-requestateam#365]
### Description

We are re-branding the app to Create-a-Team instead of Request-a-Team. I have made all the updates to the places that are needed in the app and flow, but I am having an issue with changing the name to a notification inside the logic app that the end-users receive when they are added to the Team in their Teams Activity feed. 

### Steps to reproduce

1. Reviewed the logic app
2. Found the post method of adding the members and owners to the Team
3. It doesn't allow you to update the Teams Activity notification

### Expected results

A way to be able to change who the alert notification is coming from.

### Actual Results

There is currently not a way for me to change the alert name from Request a Team to Create a Team.

### Solution component

Logic Apps

### Operating system (environment)

Windows

### Additional Info

[Create-a-Team App Re-brand Issue.pdf](https://github.com/OfficeDev/microsoft-teams-apps-requestateam/files/8911866/Create-a-Team.App.Re-brand.Issue.pdf)

**Comment by laurenmason2** [comment]
@alexc-MSFT maybe you can assist with this?

**Comment by dav1dbailey** [comment]
Hi @laurenmason2 this idea to rename the 'request' process to 'create' is a fantastic idea which I wish to implement as well. The end user is more familiar with always being able to just create a team and not changing that perception will help with the adoption of the App.  I am looking to 'upgrade' the current (non-production) implementation of 'Request a Team app' with the newest deployment to include sensitivity labels in readiness to begin a Governance adoption process.  Would you be able to share the information with me regarding the changes you have already made to the App deployment?

**Comment by alexc-MSFT** [comment]
@laurenmason2 Sorry for the delayed response, took me a little while to figure out what you wanted to change. So the bit you need to change is the name of the Azure AD application, as this is what is used when adding users to the created Team (we call the Graph using the AD app).

You can go into Azure AD, locate the app registration and edit the manifest to update the name, see the screenshot below:

![image](https://user-images.githubusercontent.com/12395485/179240284-0e39f5c2-55a0-4a15-a1f4-ff15ea4feaa8.png)

Let me know how you get on.

**Comment by laurenmason2** [comment]
Thanks for reaching back out @alexc-MSFT. It looks like I have already changed that in the manifest and it hasn't fixed the alert.

![Create a Team Manifest](https://user-images.githubusercontent.com/107215892/179241786-3b04feac-d011-4c5f-88fc-a08024a069c5.jpg)

**Comment by laurenmason2** [comment]
I disabled the logic app and re-enabled, it kicked whatever cache was happening. The issue is now resolved. Thanks for the help!
