### ISSUE TITLE
Error on Team Request from ?Logic App

### ISSUE THREAD

**Issue by amannall** [OfficeDev/microsoft-teams-apps-requestateam#37]
WHen I use the tool (everything appeared to deploy correctly) I get an error on the screen where you submit your request.

It doesn't fill in the owners and members elements.

The error is ...

The requested operation is invalid. Server Response: Teams Requests failed: The specified user i:0#.f|membership|a.mannall@imperial.ac.uk could not be found. clientRequestId: 2c6265d6-dc0b-4f77-b6a9-6dd17640e549 serviceRequestId: 2c6265d6-dc0b-4f77-b6a9-6dd17640e549

Our UPNs are different to our email addresses - do we need extra steps to look up the user UPN from AzureAD?

**Comment by amannall** [comment]
THink I might have found the error - no given name in the service account.

**Comment by alexc-MSFT** [comment]
Glad you have fixed the issue - I'm closing this. Please re-raise if you have any other problems.

Thanks
