### ISSUE TITLE
Documentation - Cost-Estimates - PowerApps Licenses

### ISSUE THREAD

**Issue by J-a-k-o-b** [OfficeDev/microsoft-teams-apps-requestateam#38]
Hi,
thank you for sharing this great deployment method. It´s very valuable. 
But let me just ask this question: Is my assumption right that every user who should be able to run this "request a teams" app must have a per user license for PowerApps? (Alternatively the per app license). The reason why we have to assign the license is because we´re using premium connectors in Logic Apps where PowerApps is the trigger. 
Regards 
Jakob

**Comment by alexc-MSFT** [comment]
@J-a-k-o-b glad you've found it valuable.

With regards to licensing, in it's current form you **do not** need paid licenses (per user OR per app). 

The logic app is triggered when the list item is updated and therefore is not triggered directly from Power Apps. There is no native way to trigger a Logic App from Power Apps unlike Flow. 

So a normal Office 365 Power Apps license will suffice (known as a seeded license).

Thanks

**Comment by alexc-MSFT** [comment]
I will close this for now, please re-raise if you have any other queries.
