### ISSUE TITLE
Issue with using Team Templates

### ISSUE THREAD

**Issue by dspooren** [OfficeDev/microsoft-teams-apps-requestateam#39]
The solution is working fine for us with new requests. We would like to use existing Teams as templates. Can you explain which values we need to fill in the Teams Templates list item?
Teams Name: testTeam

![image](https://user-images.githubusercontent.com/18420047/82870948-0c7db400-9f31-11ea-968c-66694e5f8be3.png)

Logic App: missing Team Id: which value is required for Team Id? Entering the GroupId value isn't working.

![image](https://user-images.githubusercontent.com/18420047/82871037-31722700-9f31-11ea-90f5-4990167ca512.png)

**Comment by alexc-MSFT** [comment]
> The solution is working fine for us with new requests. We would like to use existing Teams as templates. Can you explain which values we need to fill in the Teams Templates list item?
> Teams Name: testTeam
> 
> ![image](https://user-images.githubusercontent.com/18420047/82870948-0c7db400-9f31-11ea-968c-66694e5f8be3.png)
> 
> Logic App: missing Team Id: which value is required for Team Id? Entering the GroupId value isn't working.
> 
> ![image](https://user-images.githubusercontent.com/18420047/82871037-31722700-9f31-11ea-90f5-4990167ca512.png)

So you need to clear out the Base Template Id and Base Template Type columns and leave these blank (this is required for Microsoft templates only).

You only need the Title and Team Id populated. Team Id should be set to the O365 group ID.

Also first party template will always be set to 'No' for your own templates.

**Comment by dspooren** [comment]
Thanks, this info has solved my issue with custom templates.
