### ISSUE TITLE
Error with Sharepoint template provisioning

### ISSUE THREAD

**Issue by Michai901** [OfficeDev/microsoft-teams-apps-requestateam#4]
When following the deployment guide it fails to provision the template to the sharepoint site the script creates. I get the following error: 

**"Error occured while configuring the SharePoint site: Für "Load" und die folgende Argumenteanzahl kann keine Überladung gefunden werden: "1"**.

All other steps seem to suceed flawless.

**Comment by alexc-MSFT** [comment]
@Michai901 is it possible to get a screenshot of where this occurs please? We will investigate. 

Also please can you let me know what version of PnP PowerShell you are using.

Thanks

**Comment by Michai901** [comment]
Hello Alex, thanks for your awnser.
After your awnser i went ahead and made sure i have the required version of all modules by putting the -force command on the pnp module installation lines in the script. 

After that the script went and actually started deploying the template and the SP Site now actually has the lists. 

However 2 new error arose that werent previously displayed I attached screenshot for reference.
![IdntityError](https://user-images.githubusercontent.com/61748751/80801209-e839ec00-8bab-11ea-9cc0-bb1bd3c00dbd.PNG)
![error2](https://user-images.githubusercontent.com/61748751/80801207-e7a15580-8bab-11ea-9702-b050e0605665.PNG)

**Comment by alexc-MSFT** [comment]
> Hello Alex, thanks for your awnser.
> After your awnser i went ahead and made sure i have the required version of all modules by putting the -force command on the pnp module installation lines in the script.
> 
> After that the script went and actually started deploying the template and the SP Site now actually has the lists.
> 
> However 2 new error arose that werent previously displayed I attached screenshot for reference.
> ![IdntityError](https://user-images.githubusercontent.com/61748751/80801209-e839ec00-8bab-11ea-9cc0-bb1bd3c00dbd.PNG)
> ![error2](https://user-images.githubusercontent.com/61748751/80801207-e7a15580-8bab-11ea-9702-b050e0605665.PNG)

Thanks @Michai901, we've noted the PnP version issue and will update the script. For the issue around the 'Identity' parameter, this is where it is getting the Owners group from the SharePoint site and adding the Service Account into it. 

For some reason it is failing here. 

Please raise a new issue for this one and we can investigate.

As for the New-AzAutomationAccount errors, this could be related to the parameters you are passing into the script so we will need to troubleshoot that with you further directly.

Also, we would recommend anonymising the tenant data in your first screenshot.

Thanks

**Comment by Michai901** [comment]
Thank you, was able to fix the Error of the second screenshot by just setting the AutomationAccountname in the script to smth diffrent, now all automation assets seem to have been created succesfull. Ill create a new issue for the owners group issue and can mark this one as complete thanks for your help!
