### ISSUE TITLE
Admin Guide

### ISSUE THREAD

**Issue by cesmaili** [OfficeDev/microsoft-teams-apps-requestateam#43]
At this time the admins/approvers cannot see all app requests. After some testing the admin can only see a request they put in themselves. How are admins added for this app?

**Comment by cesmaili** [comment]
Are the users in the (Teams) Admin group the same users we would have for the SharePoint site?

**Comment by alexc-MSFT** [comment]
@cesmaili so the Admins would/should be able to see all the entries in the SharePoint list, this is where they would go to view the entire list.

**Comment by abbodh** [comment]
Hi @cesmaili , the SharePoint site is required to be shared by admins as Owners. Please refer #6 of [Step 5 ](https://github.com/OfficeDev/microsoft-teams-apps-requestateam/wiki/Deployment-guide#step-5-share-power-apps-and-sharepoint-site)
