### ISSUE TITLE
Getting 403 forbidden when logical app tries to post wlcome message.

### ISSUE THREAD

**Issue by em0g** [OfficeDev/microsoft-teams-apps-requestateam#44]
I've read the closed issues with the same behavior so I've maked sure I have the updated version of the logical app where serviceaccount is added as owner during the team creation.

I can see that the team is created and the serviceaccountuser is still there as the owner.

I cant figure out why this is happening. any ideas? 

![image](https://user-images.githubusercontent.com/54065567/83160062-004b4f80-a107-11ea-8929-02a1effafca6.png)

**Comment by alexc-MSFT** [comment]
@em0g please can you try and re-authorise the api connection for this please as the service account and see if that fixes it.

Thanks

**Comment by em0g** [comment]
Yes, you are right sir! I've missed the detail to use the service account credentials when authorizing the logic app connection.. sorry, my bad! :)

thanks for help!

cheers!

**Comment by em0g** [comment]
-
