### ISSUE TITLE
Logic App Connections not created correctly

### ISSUE THREAD

**Issue by timmgreen** [OfficeDev/microsoft-teams-apps-requestateam#45]
When running deploy.ps1 I am prompted to authorize the Logic App connections with the service account.  When prompted for modern authentication I provide the service account email address, however, it then takes me to the organization login page (we use third-party SSO) and it authenticates under my account.

Workaround so far has been to grant service account role permission on the resource group.  Then when logged in as service account go to each of the API connections and reauthorize.

**Comment by alexc-MSFT** [comment]
@timmgreen I'm not sure there's much we can do around this. We use the native way of authenticating and do not interact with the authentication popups in any way. 

I think the workaround is the only way forward in this case I'm afraid.

I'm going to close for now but will make the team aware to list this in the documentation.
