### ISSUE TITLE
Reboot step missing in documentation

### ISSUE THREAD

**Issue by ericpskl** [OfficeDev/microsoft-teams-apps-requestateam#49]
deploy.ps1 relies on the "az" command being present in the current PATH, which is not true until after rebooting the system following the installation of the Azure CLI module.

If you follow directions as posted, the script will fail with the following error:

```
### AZURE AD APP CREATION ###
Creating Azure AD App - 'Request-a-team'...
Error occured while creating an Azure AD App: The term 'az' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
```

**Comment by alexc-MSFT** [comment]
Thanks @ericpskl - I will update the documentation.
