### ISSUE TITLE
Approval (Adaptive card) is not been received.

### ISSUE THREAD

**Issue by hugo7sep** [OfficeDev/microsoft-teams-apps-requestateam#50]
I create the request from within the Team or the PowerApp. and it shows as Pending approval.
But I wait for the request and it is not sending any. not to the Admin email or to the Team Channel.
I have added the Team ID in the Variable and also the Channel ID, also fill out the Admin Email Variable. But not getting any notification trying from this different scenarios.
I've also tried to change the condition, such change the value it looks to just 1, tryin to drive the execution for the admin email but it just does not send the adaptive card.

**Comment by timmgreen** [comment]
> I create the request from within the Team or the PowerApp. and it shows as Pending approval.
> But I wait for the request and it is not sending any. not to the Admin email or to the Team Channel.
> I have added the Team ID in the Variable and also the Channel ID, also fill out the Admin Email Variable. But not getting any notification trying from this different scenarios.
> I've also tried to change the condition, such change the value it looks to just 1, tryin to drive the execution for the admin email but it just does not send the adaptive card.

Check the Flow.  I had this as well and found there was a step in which the URL to the Sharepoint site had not yet been updated.

**Comment by medicineshow** [comment]
I have a similar error. I have two admins in the team who can give approval. Me and one other. The approval flow runs without error but the Flow adaptive card only appears in my instance of Teams. Also the admin email designated in the flow is not receiving the email.

**Comment by alexc-MSFT** [comment]
@medicineshow the admin will not receive an email if you are using the Team ID and Channel ID in the settings list, this uses an adaptive card instead of a Power Automate approval task.

Let me do some testing to see if I can replicate it not appearing in other people's instance of Teams.

**Comment by alexc-MSFT** [comment]
@medicineshow are you sorted now?

**Comment by medicineshow** [comment]
Hi Alex,
I understand why the email does not send but there is still the issue that the adaptive card only appears in my Teams client even though there are other people in the Admin Team that is designated to authorise Teams creation.

Kind Regards

Mark Enfield
Mark Enfield | Desktop Architect | HS2/Fujitsu
[cid:image001.png@01D4F167.F8FE2E00]High Speed Two (HS2), 1st  Floor, The Podium Euston, One Eversholt Street, London, NW1 2DN

Advanced Notice Annual Leave:
Tel: +44 (0)207 944 6302
Mob: +44 (0)7867 825 281

Web: uk.fujitsu.com<http://uk.fujitsu.com/>
[youtube-icon.gif]<http://www.youtube.com/user/fujitsuUK>[Facebook-icon.gif]<http://www.facebook.com/fujitsuuk> [twitter-icon.gif] <http://twitter.com/#!/fujitsu_uk>  [linkedin-icon.gif] <http://www.linkedin.com/company/fujitsu-uk-and-ireland>  [blogger.png] <http://blog.uk.fujitsu.com/>  [cid:image013.gif@01D56C84.E4379B30] <https://plus.google.com/103287532874520008913/posts>
[cid:image014.jpg@01D56C84.E4379B30]
Fujitsu is proud to partner with Action for Children<http://www.actionforchildren.org.uk/>

**Comment by asonder** [comment]
A similar issue happened to us where the "Check if we are posting to Teams" step failed in the Team Request Approval flow. We figured out that it was because we had run the deploy script a second time (our api connections weren't created during the first run) and selected yes for "Site already exists. Do you wish to overwrite?"  This created a set of "Modified" Team Request Settings that resulted in TeamId and ChannelId being set to null. We fixed the issue by permanently deleting the SP site, then running the deploy script again.

**Comment by alexc-MSFT** [comment]
@asonder yes the script will modify the settings hence they will be set back to null. Hopefully you are all sorted now so I will close the issue.

Thanks
