### ISSUE TITLE
Flow running for days. Team never gets created

### ISSUE THREAD

**Issue by chetferg** [OfficeDev/microsoft-teams-apps-requestateam#51]
I am experiencing an issue where once a team is approved within the app. The flow will kick off but will not finish or fail. I cant pinpoint exactly where the error is -- since it has been running non stop (over the weekend) and when I tried again this morning its the same thing. It seems like it does not make it to the logic app, so I would imagine it is somewhere in this part of the flow it is failing:
![image](https://user-images.githubusercontent.com/57763795/84028827-66ce3a00-a95f-11ea-943c-1869831bf193.png)

Any help would be greatly appreciated!!!

![image](https://user-images.githubusercontent.com/57763795/84028740-44d4b780-a95f-11ea-924c-2274f0a71698.png)

**Comment by alexc-MSFT** [comment]
@chetferg do you have the solution configured to post an adaptive card into Teams? i.e. populating the values in the settings list or send the approval task? If the latter, please check the email address used in the flow as it is likely sending a task to a user that does not exist and is still sat at approval stage.

**Comment by chetferg** [comment]
Thanks for all your help!
