### ISSUE TITLE
Issue with Check if SharePoint site exists

### ISSUE THREAD

**Issue by simonleray-meyer** [OfficeDev/microsoft-teams-apps-requestateam#52]
Hi,

I've been struggling to get the Logic app to run properly and have narrowed it down to the step "Check if SharePoint site exists".

it comes up with this error
    "message": "The client '4897ab15-b614-499a-b89c-31cd3e0a3' with object id '4897ab15-b614-499a-b89c-31cd3e0a3' does not have authorization to perform action 'Microsoft.Automation/automationAccounts/jobs/write' over scope '/subscriptions/038fcd6a-1503-4adb-87f1-3ab20c84ff28/resourceGroups/Rg-provisionteams-app/providers/Microsoft.Automation/automationAccounts/teamsautomate-auto/jobs/0169ee4a-ffe3-4fa5-98f2-24230d683e9f' or the scope is invalid. If access was recently granted, please refresh your credentials."
![error](https://user-images.githubusercontent.com/34058791/84159454-fd385380-aa64-11ea-9659-3994bbc80896.png)

I am testing this in a lab environment using a single service account that has the GA roles and an E3 licence.  I have checked and the account has owner permissions on the subscription.

The account can happily open up the SharePoint admin screen and Teams as I've been using it to create and deploy the teams-app-request flows.

What am I missing?

regards

Simon

**Comment by simonleray-meyer** [comment]
Hi Alex,

thanks for this.  I re-ran the script and and watched carefully for the errors.

I found two errors.  When the command "Get-AzureADDirectorSetting" runs, it would fail.  I had to change the script to use AzureADPreview\Connect-AzureAD and then it works.

I can then see that the automation account is not being created.

When it gets to "Creating and deploying automation assets..."  the script generates an error, but continues

![image](https://user-images.githubusercontent.com/34058791/84414049-580ab000-ac09-11ea-9c4e-f72f2bc0c14f.png)


I've gone back and checked the script and I think I've set it up correctly.

I am using the location UKSouth

This is my script (just without the subscription details)
-TenantName "fluffylab" -TenantID "" -RequestsSiteName "Teams Provision10" -RequestsSiteDesc "Used to store Teams Requests" -ManagedPath "sites" -SubscriptionId  -Location "UKSouth" -ResourceGroupName "Rg-provisionteams10-app" -AppName "provisionteams10-app" -ServiceAccountUPN "teams-provisioning@fluffytassels.com" -UseMSGraphBeta $false -IsEdu $false

regards

Simon

**Comment by alexc-MSFT** [comment]
@simonleray-meyer glad to hear you have got further. I'm assuming the automation account has never been created by the script before? i.e. it already exists?

FYI - I am updating some of the code in the script to handle if the automation account already exists so this should be submitted soon as a PR.

Can you try and manually create an automation account outside of the script using the New-AzAutomationAccount cmdlet please and see what happens.

Thanks

**Comment by simonleray-meyer** [comment]
Hi Alex,

Yup, the automation account has never been created.  I’m starting it again and will create the automation account manually.

Regards

Simon

**Comment by simonleray-meyer** [comment]
Hi Alex,

I managed to get it to work.  In the end, I had to setup a fresh VM from a Win10 1903 image.  I patched it and then ran the script.

I still found I had to edit the deployment script on line 636 to be AzureADPreview\Connect-AzureAD, otherwise, the Get-AzureADDirectorSetting functions wouldn’t work.

Once I edited the script and ran it on the fresh VM, it worked.

Regards

Simon

**Comment by alexc-MSFT** [comment]
@simonleray-meyer great, glad to hear you got it working. Makes sense on using the backslash with the Get-AzureADDirectorySetting cmdlet. I'm going to make that as a code change.

**Comment by alexc-MSFT** [comment]
Updated deploy code, linked PR and closing
