### ISSUE TITLE
Classification option not working

### ISSUE THREAD

**Issue by Lysakers** [OfficeDev/microsoft-teams-apps-requestateam#55]
I am trying to get the classification option to show in the app, but changing the value in "Teams request settings" has no effects on the controls in the app.

After manuelly setting visibility i get them to appear, but the images are missing and the dropbox had the worng height.

Is the classification options not implemented in the app yet, or am i doing something worng?
Can't find anything in the Wiki posts either.

**Comment by alexc-MSFT** [comment]
@Lysakers classifications are not implemented in the app yet, they were previously in a version prior to this and they have been left in. The app basically doesn't display them but in the Logic App the functionality is technically there to make it work.

We may choose to add these in at some point in the future.

Thanks
