### ISSUE TITLE
Requires AzureRM?

### ISSUE THREAD

**Issue by sandarvanlaan** [OfficeDev/microsoft-teams-apps-requestateam#58]
I'm getting the following on the script:
The term 'get-azlocation' is not recognized as the name of a cmdlet
The term 'connect-azaccount' is not recognized as the name of a cmdlet

Is this because this requires Azure-RM cmdlets? If so, is there any plan to update it to current AZ Module?

Thanks!

**Comment by alexc-MSFT** [comment]
@sandarvanlaan the script does not and should not require AzureRM, it uses the new Az module. Get-AzLocation should be an Az cmdlet. See - https://docs.microsoft.com/en-us/powershell/module/Az.Resources/Get-AzLocation?view=azps-4.2.0.

Thanks
