### ISSUE TITLE
Team request approval-Step "Check if we are posting to Teams" is not sending rejected email

### ISSUE THREAD

**Issue by kireetijs** [OfficeDev/microsoft-teams-apps-requestateam#61]
Implemented this application in our environment. It is working very good. Only one issue-> it is not sending rejected email if we reject the request from app dashboard and flow is still running. If we reject the request from adaptive cards it is sending the reject email. Looks like the problem is at "Check if we are posting to teams". It is stopping at this step if we reject the request.
Thank in advance for suggestions.

**Comment by kireetijs** [comment]
How to stop "Team request approval" flow, if the request is not rejected from the adaptive card?

**Comment by kireetijs** [comment]
Thank you Alex. Hi Abhijeet, If i reject the request from "Approval request" dashboard, the workflow is not continuing execute. It hangs there with status running.
![TeamsRequetApproval](https://user-images.githubusercontent.com/17038284/84697617-15e8b380-af14-11ea-90e3-f3846e752cc2.JPG)

**Comment by lkanala** [comment]
Hi Kireeti,
 If you expand that step, Check if we are posting to Teams, there is a step called post an adaptive card to channel and wait for response, if you approve it from Power App, this flow will keep on waiting until it times out. Since it is a flow there is no other way around to know if that request is rejected while it is waiting for response from adaptive card.

**Comment by kireetijs** [comment]
Thank you Lalith. Is there any workaround to send an rejection email in case of rejection made from PowerApp? I created a SharePoint designer workflow with 5 mins delay to send an email on rejection of request, which is giving error on new request submission--"Conflicts exist with changes on the server, please reload. Server Response: Teams Requests failed: ETAG mismatch"

**Comment by kireetijs** [comment]
Thank you Alex/Lalith. Created a logic app to run every minute when request status changed to "Rejected" with control condition as "Approved Date" is null (Approved Date is blank, If the request is not rejected from adaptive card.) to send rejection email to requester and updating the Approved Date field to Current time. Please let me know if there is better way to achieve this functionality.
