### ISSUE TITLE
Logic app run, Parse team owners JSON step fails

### ISSUE THREAD

**Issue by medicineshow** [OfficeDev/microsoft-teams-apps-requestateam#62]
At the is step, it errors with: Validation failed. The schema validation failed.

**Comment by medicineshow** [comment]
![image](https://user-images.githubusercontent.com/17124284/84568594-61fef100-ad78-11ea-95f5-c4b08232247c.png)

**Comment by medicineshow** [comment]
mistakenly closed it.

**Comment by alexc-MSFT** [comment]
@medicineshow can you please show me where it fails (should be further down in that screenshot), one of the properties of a member/owner user is likely null.

Should be an easy fix once we find which one.

Thanks

**Comment by medicineshow** [comment]
Apologies. I am new to Logic apps so hadn't realised there was more low level information.
So the Outputs/ Errors are below. I have checked in Azure AD and both owners do have Surname properties however, the service account does not. I updated that information and the app has run successfully. Thanks for the help.
[
  {
    "message": "Invalid type. Expected String but got Null.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "value[0].surname",
    "schemaId": "#/properties/value/items/properties/surname",
    "errorType": "type",
    "childErrors": []
  }
]
.
