### ISSUE TITLE
Sharepoint site permissions

### ISSUE THREAD

**Issue by timmgreen** [OfficeDev/microsoft-teams-apps-requestateam#64]
The deployment guide states that the Sharepoint site must be shared with anyone who will use that app but does not discuss required permissions.  In testing, it appears that Contribute is sufficient for requestors.  So far admins are Owners.  I have not tested minimums for admins.  We only have a small group who will be approving requests and they know better than to delete anything from the site.

**Comment by alexc-MSFT** [comment]
@timmgreen so in terms of permissions - Contribute as you say is enough for requestors however I would break the inheritance on the templates and settings lists to that requestors get read only access.

For admins it depends what they are doing. Contribute to the whole site is fine if they are just approving requests/creating teams templates etc.

Hope that helps.

**Comment by alexc-MSFT** [comment]
Closing for now - please raise again if you have any more issues.

Thanks
