### ISSUE TITLE
Conflicts exist with changes on the server, please reload. Server Response: Teams Requests failed: ETAG mismatch. clientRequestId: a0a4dc84-3d3e-453e-9491-bf47f10ea2bb serviceRequestId: a0a4dc84-3d3e-453e-9491-bf47f10ea2bb

### ISSUE THREAD

**Issue by kireetijs** [OfficeDev/microsoft-teams-apps-requestateam#65]
The above error is occurring at "btnNextAddMembers.OnSelect" ---------------------------

If(('cmbOwners._1'.Selected.Email='cmbOwners._2'.Selected.Email)&&(CountRows('cmbOwners._1'.SelectedItems)>0),Set(Varowandmemnotclash,false),Set(Varowandmemnotclash,true)); 
If((CountRows('cmbMembers.'.SelectedItems)>0)&&(CountRows('cmbOwners._1'.SelectedItems)>0),If('cmbOwners._1'.Selected.Email=First('cmbMembers.'.SelectedItems).Email||'cmbOwners._1'.Selected.Email=Last('cmbMembers.'.SelectedItems).Email||'cmbOwners._2'.Selected.Email=First('cmbMembers.'.SelectedItems).Email||'cmbOwners._2'.Selected.Email=Last('cmbMembers.'.SelectedItems).Email,Set(Varowandmemnotclash,false),Set(Varowandmemnotclash,true)));
If(CountRows('cmbOwners.'.SelectedItems)<1||(CountRows('cmbOwners._1'.SelectedItems)<1),Set(BNReviewAndSubmit,false)&&Set(BNMembership,true),If(CountRows('cmbOwners.'.SelectedItems)>0&&(CountRows('cmbMembers.'.SelectedItems)<=2)&&Varowandmemnotclash,UpdateContext({ScratchlocalStep:ScratchlocalStep+1})&&Set(BNReviewAndSubmit,true)&&Set(BNMembership,false)));
If(CountRows('cmbOwners.'.SelectedItems)=2&&(CountRows('cmbMembers.'.SelectedItems)<=2)&&(CountRows('cmbOwners._1'.SelectedItems)>0)&&(CountRows('cmbOwners._2'.SelectedItems)>0)&&Varowandmemnotclash,Patch('Teams Requests',LookUp('Teams Requests',RowKey=srowkey),{Owners:'cmbOwners.'.SelectedItems},{Members:'cmbMembers.'.SelectedItems},{Stage:{'@odata.type':"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference",
  Value:"Requirements"}}));
  If(CountRows('cmbOwners.'.SelectedItems)>0&&(CountRows('cmbMembers.'.SelectedItems)<=2)&&(CountRows('cmbOwners._1'.SelectedItems)>0)&&(CountRows('cmbOwners._2'.SelectedItems)<=0)&&Varowandmemnotclash,Patch('Teams Requests',LookUp('Teams Requests',RowKey=srowkey),{Owners:'cmbOwners._1'.SelectedItems},{Members:'cmbMembers.'.SelectedItems},{Stage:{'@odata.type':"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference",
  Value:"Requirements"}}));

**Comment by kireetijs** [comment]
SharePoint workflow is causing this error. It is working fine after deleting workflow. Is there any workaround to make it work even if there is an SharePoint designer workflow?

**Comment by alexc-MSFT** [comment]
@kireetijs we might have a workaround for this by updating the code in the Power App. This is with another team so let me follow up with them.

**Comment by kireetijs** [comment]
Thank you Alex. Created a logic app to run every minute when request status changed to "Rejected" with control condition as "Approved Date" is null (Approved Date is blank, If the request is not rejected from adaptive card.) to send rejection email to requester and updating the Approved Date field to Current time.
