### ISSUE TITLE
Request remains in 'Approved' status

### ISSUE THREAD

**Issue by jesslyn-omm** [OfficeDev/microsoft-teams-apps-requestateam#66]
I deployed and rechecked all the steps and then went thru the troubleshooting steps, but the logic app never seems to run.  I am about as far from an expert as you can get--hopeing you can assist from this info.

EVALUATION
Evaluated 12 times, fired 0 times in the last 24 hours
and the trigger history says 'Skipped'

Any idea of what is missing or configured incorrectly?

**Comment by alexc-MSFT** [comment]
@jesslyn-omm is this the first request just out of interest?

**Comment by jesslyn-omm** [comment]
No, I’ve done 7-- 6 Approvals, 1 Rejection.

Jesslyn Hendrix
jhendrix@omm.com<mailto:jhendrix@omm.com>
O: +1-213-430-7897

**Comment by alexc-MSFT** [comment]
@jesslyn-omm ok - there is something we can try:

If you edit the logic app (ProcessTeamRequest) and remove the conditional trigger from the When an item is created or modified action (click the three dots > settings icon and click the cross next to the trigger condition - **make a copy of this before**.

If you then go and make another request and approve it.

The logic app should now run but you will probably get multiple runs (without the trigger condition, it is executing every time the item is changed i.e. not just changed to approved). 

Ignore any failed runs and add the trigger condition back in.

After this it should be fine.

Thanks

**Comment by jesslyn-omm** [comment]
Sigh.  Still nothing.  If it helps, the only difference that I can see is that on ‘teamsautomate-authorization’ and ‘teamsautomate-teams, I don’t see Confirm Connections Consent Code listing like I do with the other connectors.

Jesslyn Hendrix
jhendrix@omm.com<mailto:jhendrix@omm.com>
O: +1-213-430-7897

**Comment by jesslyn-omm** [comment]
I figured out where I errored.  I connected the request Team to the site where the information is stored.  Once I created a new Team, the request was processed correctly.  It took me spinning up a test Azure environment to realize what I did wrong in my production environment.

**Comment by alexc-MSFT** [comment]
@jesslyn-omm glad to hear you got it sorted. It was most likely an error in the deployment script that caused the Logic App to not be linked to the SharePoint site correctly. There is an active pull request in place that should fix the majority of issues caused by running the script multiple times.
