### ISSUE TITLE
The request failed. Error code: 'BotRequestFailed'. Error Message: 'Request to the Bot framework failed with error: '{"error":{"code":"BadSyntax","message":"Bad format of conversation ID"}}'.'.

### ISSUE THREAD

**Issue by sneranacdw** [OfficeDev/microsoft-teams-apps-requestateam#67]
When a user adds a request for a teams provision, Teams request Approval flow fails with following error:

The request failed. Error code: 'BotRequestFailed'. Error Message: 'Request to the Bot framework failed with error: '{"error":{"code":"BadSyntax","message":"Bad format of conversation ID"}}'.'.

This steps fails and no Teams Request approval email is sent and no Teams get provisioned

Any suggestions or tips

**Comment by alexc-MSFT** [comment]
@sneranacdw please check the format of the 'Team ID' and 'Channel ID' in the Team Request Settings list as it is likely this is incorrect, please can you post an example of the formatting?

Thanks

**Comment by sneranacdw** [comment]
I am getting the following error now:
Office365Groups.ListGroupMembers failed: { "error": { "code": "Request_ResourceNotFound", "message": "Resource '408a8ddd-d7c6-40a3-8ec1-611eb70b07dc' does not exist or one of its queried reference-property objects are not present.", "innerError": { "date": "2020-06-29T20:41:51", "request-id": "b02143b8-8646-4177-8827-b7f99fb06f31" } } }

**Comment by alexc-MSFT** [comment]
@sneranacdw whereabouts is this error appearing? In the Power App or the Flow?

**Comment by sneranacdw** [comment]
In flow

Thanks
Snehal H Rana
Senior Sharepoint Consultant
Email: snerana@cdw.com
Cell: (773)251-0242

________________________________

**Comment by sneranacdw** [comment]
Quick update:
I was able to resolve this error message by reassigning Teams ID and Channel ID. This is now resolved

**Comment by sneranacdw** [comment]
This issue is now resolved by reassigning Teams ID and Channel ID
