### ISSUE TITLE
Request_BadRequest - Enter admins teams group ID here

### ISSUE THREAD

**Issue by simonleray-meyer** [OfficeDev/microsoft-teams-apps-requestateam#68]
Hi,

I've setup the Request a Teams in my production environment.  When I go to test the app in Power Apps, I get this error
![image](https://user-images.githubusercontent.com/34058791/85558518-b760bb00-b620-11ea-9464-c817c1519f82.png)

I have checked and made sure that I've added the Teams ID for the approval Teams into the power app and the SharePoint sites.

The Teams service account is an Owner of the Teams.

The GA account that I used to create and install everything doesn't have a licence, beyond the Azure P2 and the PowerApps free licence.

I've deleted everything and started again, still no joy.  I've tried a different teams and that doesn't work.

What have I missed?

regards

Simon

**Comment by alexc-MSFT** [comment]
@simonleray-meyer have you definitely updated the App OnStart with the ID of the the Team/O365 group containing the admins?

Thanks

**Comment by simonleray-meyer** [comment]
Hi Alex,

Yup, I have.

[cid:image002.png@01D64BA8.B060A140]

I tested it again this morning and still get this error
[cid:image003.png@01D64BA7.B1A68430]

I checked the URL again today, and the ID is correct.

The Teams service account (the one with the licence) is an owner of that Teams.

The GA account I used to set everything up doesn’t have a Teams licence.  The only licences it has are an Azure P2 and the Power Automate Free licences.

This is the same as I had setup in my lab environment.

I have deleted everything, so, the SharePoint site, the Azure apps and resource groups, plus the Teams and started over again.  All with new names, still the same issue.

Regards

Simon

**Comment by tekila747** [comment]
Hello,

I also had the same error (even after updating the App OnStart with the ID of the the Team/O365 group containing the admins).
I also tried to delete all and restart install from scratsh > same problem.

I tried to Publish after Save, and the error disappeared (Publish step is not mentioned in the deployment guide)
Is it mandatory to publish?

**Comment by simonleray-meyer** [comment]
Hi,

This worked for me as well.

I had done this in my lab, but as it wasn’t on the instructions, I did not do it for my production environment.

Once I published the app and gave it 10 minutes, I was able to request a Teams and have the adaptive card appear.

Now working out why the flows require my GA account to have a Teams licences to work.  The flows are all running as the GA account, as per the instructions, but when I configured it, I told it to use the Teams service account.

Regards

Simon

**Comment by alexc-MSFT** [comment]
> Hi, This worked for me as well. I had done this in my lab, but as it wasn’t on the instructions, I did not do it for my production environment. Once I published the app and gave it 10 minutes, I was able to request a Teams and have the adaptive card appear. Now working out why the flows require my GA account to have a Teams licences to work. The flows are all running as the GA account, as per the instructions, but when I configured it, I told it to use the Teams service account. Regards Simon From: tekila747 <notifications@github.com> Sent: 29 June 2020 15:56 To: OfficeDev/microsoft-teams-apps-requestateam <microsoft-teams-apps-requestateam@noreply.github.com> Cc: Simon LeRay-Meyer <simon.leray-meyer@carbontrust.com>; Mention <mention@noreply.github.com> Subject: Re: [OfficeDev/microsoft-teams-apps-requestateam] Request_BadRequest - Enter admins teams group ID here (#68) Hello, I also had the same error (even after updating the App OnStart with the ID of the the Team/O365 group containing the admins). I also tried to delete all and restart install from scratsh > same problem. I tried to Publish after Save, and the error disappeared (Publish step is not mentioned in the deployment guide) Is it mandatory to publish? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-requestateam%2Fissues%2F68%23issuecomment-651174923&data=02%7C01%7C%7C7a22338b6820495597bf08d81c3c96e0%7C96e14e5a57ac48d7851d12f54eff5a60%7C0%7C0%7C637290393846038451&sdata=Izj013h44%2F2Zqalshz%2B0zLQuDPd3xvWSWBm9ruBlH%2Bk%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAID3EJ3XQAC3U4W4NMPQ5RDRZCTRLANCNFSM4OGUD6CA&data=02%7C01%7C%7C7a22338b6820495597bf08d81c3c96e0%7C96e14e5a57ac48d7851d12f54eff5a60%7C0%7C0%7C637290393846048454&sdata=KnQGB5ybu6iwM6prG5KZ7xx74eV8Vfhr4cB2A81X5HU%3D&reserved=0>. '' This message is for its intended addressee only and may contain confidential or privileged information. If you received this message in error, please notify the sender and delete it immediately. Any review, re-transmission, dissemination or other use of, or taking action in reliance upon, this message by persons or entities other than the intended addressee is prohibited. We have used our reasonable endeavours to scan all attachments for viruses. However, we cannot accept liability for any loss or damage you may incur as a result of virus infection. The views expressed are those of the author only and do not necessarily reflect the views of The Carbon Trust, its subsidiaries or any other person and we accept no liability for any statement or opinion expressed. The Carbon Trust (04190230) is a company limited by guarantee, registered in England and Wales, whose registered office is at 4th Floor, Dorset House, 27-45 Stamford Street, London, SE1 9NT.The following Carbon Trust subsidiaries have the same registered office: Carbon Trust Advisory Limited (06274284), Carbon Trust Assurance Limited (06547658), Carbon Trust Enterprises Limited (05113991), Carbon Trust International Limited (07008522) and Carbon Trust Investments Limited (04649291).The Carbon Trust is authorised and regulated by the Financial Conduct Authority. When you send us e-mails for business purposes, we may collect your personal information and use it to contact you in the future. For more information about how we might use your information, please refer to our Privacy Notice<https://www.carbontrust.com/terms/#privacy>. '

Yes the app should always be published.

In terms of the account needing a Teams licensing this is because it uses the 'Teams' connector in Power Automate/Flow to post the adaptive card so the account setting up the connects would need a Teams license.

Hope this clears things up - I will close this issue for now but please re-open if you are still stuck.

Thanks
