### ISSUE TITLE
Check Team Availability flow zip is not in the package

### ISSUE THREAD

**Issue by oggiejnr** [OfficeDev/microsoft-teams-apps-requestateam#7]
Check Team Availability flow zip is not in the package I downloaded.

**Comment by alexc-MSFT** [comment]
> Check Team Availability flow zip is not in the package I downloaded.

This flow is part of the Power App package and will be created when you import the Power App. Thanks

**Comment by oggiejnr** [comment]
Thanks Alex 🤦‍♂️. 
Can't believe I missed it! It's been a long day.
