### ISSUE TITLE
Deployment Error - Script Error

### ISSUE THREAD

**Issue by jstevens5591** [OfficeDev/microsoft-teams-apps-requestateam#71]
Creating Azure AD App - 'Requestateamapp'...
Error occured while creating an Azure AD App: The term 'az' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

az : The term 'az' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At C:\Users\jstevens\Downloads\microsoft-teams-apps-requestateam-master\microsoft-teams-apps-requestateam-master\Deployment\Scripts\deploy.ps1:638 char:13
+ $cliLogin = az login
+             ~~
    + CategoryInfo          : ObjectNotFound: (az:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Get-AzureADDirectorySetting : The term 'Get-AzureADDirectorySetting' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\jstevens\Downloads\microsoft-teams-apps-requestateam-master\microsoft-teams-apps-requestateam-master\Deployment\Scripts\deploy.ps1:403 char:30
+     $groupDirectorySetting = Get-AzureADDirectorySetting | Where-Obje ...
+                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-AzureADDirectorySetting:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by alexc-MSFT** [comment]
@jstevens5591 the script requires a handful of PowerShell modules, these should be installed when you run the script but it looks like they are not being installed for some reason. In this case please try and install them manually - 

Install-Module microsoft.online.sharepoint.powershell -Scope CurrentUser
Install-Module SharePointPnPPowerShellOnline -Scope CurrentUser -MinimumVersion 3.19.2003.0 -Force
Install-Module ImportExcel -Scope CurrentUser
Install-Module Az -AllowClobber -Scope CurrentUser
Install-Module AzureADPreview -Scope CurrentUser
Install-Module WriteAscii -Scope CurrentUser

Please also download and install the Azure CLI - https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest&tabs=azure-cli

Once that is all done please reboot and try again.

Thanks

**Comment by jstevens5591** [comment]
Thank you for the assist. I was able to get past this error now.

However, I am not 100% clear what it is looking for here:

[cid:image002.jpg@01D64B97.49844B40]


Jeremy Stevens | MCSE 2017-Cloud & Infrastructure, MCSE 2012, MCSA 2016, 2012
Principal Systems Engineer

[cid:image16c607.PNG@db456f54.4cbbdf2e]

E jeremy.stevens@almacgroup.com<mailto:jeremy.stevens@almacgroup.com>
25 Fretz Road | Souderton PA 18964 | United States of America

www.almacgroup.com<http://www.almacgroup.com>

**Comment by jstevens5591** [comment]
Can anyone help me determine what I am suppose to use when the steps asks for an App Domain? This is the last bit holding me up.

Thanks!

**Comment by alexc-MSFT** [comment]
@jstevens5591 when you say 'App Domain' what do you mean? Can you post a screenshot? I'm not sure we ask for an app domain anywhere.

Thanks

**Comment by jstevens5591** [comment]
Screenshot attached.

Thanks!
![Step2 - App Domain](https://user-images.githubusercontent.com/67435951/86107390-c10a7880-ba8f-11ea-8234-560758d97c10.jpg)

**Comment by loflet** [comment]
Hi @jstevens5591 , the screenshot you provided is referred from this link https://github.com/OfficeDev/microsoft-teams-apps-requestateam/wiki/Deployment-Guide which is provided by OfficeDev team. 

To answer your question what should you put in the app domain? - 
**For provider-hosted add-in, this will be the domain where, the add-in is hosted. For token generation add-in, fill in any value. Make sure, not to include protocols(https) or slashes(/).**
You can enter www.localhost.com in the AppDomain

**Comment by jstevens5591** [comment]
@loflet you are correct, that is where I got the screenshot, but it's really not clear what to put there. The add-in is being hosted in SharePoint Online, do I just add my URL? This add-in is not tied to our company domain, example: www.mycompany.com

So do I use my SP Online URL? example "mycompany.sharepoint.com"

**Comment by loflet** [comment]
Hi @jstevens5591 yes you can add your SP online URL example "mycompany.sharepoint.com"

**Comment by jstevens5591** [comment]
@loflet Thank you! I am all sorted.

**Comment by alexc-MSFT** [comment]
@loflet  @jstevens5591  ah yes I forgot about registering the SharePoint add-in. I'll update the documentation now.

**Comment by alexc-MSFT** [comment]
Documentation updated - closing issue.

**Comment by jstevens5591** [comment]
Thank you for the help.
