### ISSUE TITLE
Owner 1 - not find

### ISSUE THREAD

**Issue by rafasoaresmessias** [OfficeDev/microsoft-teams-apps-requestateam#72]
In the check box Owner 1* doesn't find users.

![image](https://user-images.githubusercontent.com/6389391/85819987-a791c580-b74b-11ea-9c0f-f3c90c98557a.png)

Could help me?

In PowerApps configuration box Owner 2* Choices([@'Teams Requests'].Owners)) 

I copied for box Owner 1 but didn't solve!!

**Comment by alexc-MSFT** [comment]
@rafasoaresmessias please try something for me - edit the Power App and click on the Owner 1 combo box, set the 'IsSearchable' property to false, then set it back to true again. Save and publish the Power App and then try again.

Thanks

**Comment by rafasoaresmessias** [comment]
Thanks, solved.

But now the new step don´t work when click (Next) 

Configuration box
![image](https://user-images.githubusercontent.com/6389391/85868967-69bf8c00-b7a1-11ea-8ff8-90927311cb80.png)

**Comment by rafasoaresmessias** [comment]
I solved.
I need edit check box again.
