### ISSUE TITLE
Creating and deploying automation assets

### ISSUE THREAD

**Issue by rhyspmurphy** [OfficeDev/microsoft-teams-apps-requestateam#73]
I get the below errors when running the script:

Creating and deploying automation assets...
New-AzAutomationAccount : Operation returned an invalid status code 'BadRequest'
At C:\Scripts\Requestateam\microsoft-teams-apps-requestateam-master\Deployment\Scripts\deploy.ps1:453 char:9
+         New-AzAutomationAccount -Name $automationAccountName -Locatio ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzAutomationAccount], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.NewAzureAutomationAccount

New-AzAutomationModule : The Resource 'Microsoft.Automation/automationAccounts/teamsautomate-auto' under resource
group 'requestateamapp-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
At C:\Scripts\Requestateam\microsoft-teams-apps-requestateam-master\Deployment\Scripts\deploy.ps1:457 char:9
+         New-AzAutomationModule -AutomationAccountName $automationAcco ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzAutomationModule], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.NewAzureAutomationModule

Get-AzAutomationModule : The module was not found. Module name: Az.Accounts.
At C:\Scripts\Requestateam\microsoft-teams-apps-requestateam-master\Deployment\Scripts\deploy.ps1:459 char:17
+ ...     while ((Get-AzAutomationModule -Name "Az.Accounts" -ResourceGroup ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzAutomationModule], ResourceNotFoundException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationModule

New-AzAutomationModule : The Resource 'Microsoft.Automation/automationAccounts/teamsautomate-auto' under resource
group 'requestateamapp-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
At C:\Scripts\Requestateam\microsoft-teams-apps-requestateam-master\Deployment\Scripts\deploy.ps1:463 char:9
+         New-AzAutomationModule -AutomationAccountName $automationAcco ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzAutomationModule], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.NewAzureAutomationModule

Import-AzAutomationRunbook : The Automation account was not found.
At C:\Scripts\Requestateam\microsoft-teams-apps-requestateam-master\Deployment\Scripts\deploy.ps1:466 char:9
+         Import-AzAutomationRunbook -Name "CheckSiteExists" -Path "./r ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Import-AzAutomationRunbook], ResourceNotFoundException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.ImportAzureAutomationRunbook

Publish-AzAutomationRunbook : The Resource
'Microsoft.Automation/automationAccounts/teamsautomate-auto/runbooks/CheckSiteExists' under resource group
'requestateamapp-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
At C:\Scripts\Requestateam\microsoft-teams-apps-requestateam-master\Deployment\Scripts\deploy.ps1:471 char:9
+         Publish-AzAutomationRunbook -Name "CheckSiteExists" -Resource ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Publish-AzAutomationRunbook], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.PublishAzureAutomationRunbook

New-AzAutomationVariable : The Resource 'Microsoft.Automation/automationAccounts/teamsautomate-auto' under resource
group 'requestateamapp-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
At C:\Scripts\Requestateam\microsoft-teams-apps-requestateam-master\Deployment\Scripts\deploy.ps1:474 char:9
+         New-AzAutomationVariable -AutomationAccountName $automationAc ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzAutomationVariable], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.NewAzureAutomationVariable

New-AzAutomationVariable : The Resource 'Microsoft.Automation/automationAccounts/teamsautomate-auto' under resource
group 'requestateamapp-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
At C:\Scripts\Requestateam\microsoft-teams-apps-requestateam-master\Deployment\Scripts\deploy.ps1:475 char:9
+         New-AzAutomationVariable -AutomationAccountName $automationAc ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzAutomationVariable], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.NewAzureAutomationVariable

New-AzRoleAssignment : The Resource 'Microsoft.Automation/automationAccounts/teamsautomate-auto' under resource group
'requestateamapp-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
At C:\Scripts\Requestateam\microsoft-teams-apps-requestateam-master\Deployment\Scripts\deploy.ps1:478 char:9
+         New-AzRoleAssignment -ObjectId $global:appServicePrincipalId  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzRoleAssignment], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureRoleAssignmentCommand

New-AzRoleAssignment : The Resource 'Microsoft.Automation/automationAccounts/teamsautomate-auto' under resource group
'requestateamapp-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
At C:\Scripts\Requestateam\microsoft-teams-apps-requestateam-master\Deployment\Scripts\deploy.ps1:479 char:9
+         New-AzRoleAssignment -ObjectId $global:appServicePrincipalId  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzRoleAssignment], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureRoleAssignmentCommand

**Comment by alexc-MSFT** [comment]
@rhyspmurphy are you able to share some of the parameters you are using when you execute the script (anonymised obviously). Thanks

**Comment by pkbullock** [comment]
I get the same, not all Azure Regions support Azure automation, e.g. UK West does not, UK South does.

**Comment by alexc-MSFT** [comment]
> I get the same, not all Azure Regions support Azure automation, e.g. UK West does not, UK South does.

Cheers @pkbullock - will make a note of that and update the code to validate the regions that support automation.

**Comment by rhyspmurphy** [comment]
@pkbullock @alexc-MSFT Switched the location from ukwest to uksouth and the issue is resolved. Thanks, much appreciated.

**Comment by alexc-MSFT** [comment]
@rhyspmurphy great thanks, I will close this issue.
