### ISSUE TITLE
Post welcome message to general channel - stop 

### ISSUE THREAD

**Issue by rafasoaresmessias** [OfficeDev/microsoft-teams-apps-requestateam#74]
When is created a Teams don't receive message "Welcome...."

Logic app - ProcessTeamRequest in the action Post welcome message to general channel:

![image](https://user-images.githubusercontent.com/6389391/85912668-a83a6280-b804-11ea-8b6b-398f3c79eeba.png)

The connection API teams is ok

![image](https://user-images.githubusercontent.com/6389391/85912722-1121da80-b805-11ea-9954-fa6d61d78be9.png)

Could you help me?

**Comment by rafasoaresmessias** [comment]
Sometimes it works!!

**Comment by alexc-MSFT** [comment]
@rafasoaresmessias can you try and create a new connection to Teams using the link that is provided and see if that works. Seems odd that it sometimes works and sometimes doesn't.

**Comment by rafasoaresmessias** [comment]
Happened with other action but i did again and it worked.

For me to create new action. What are the parameters?

![image](https://user-images.githubusercontent.com/6389391/86419977-5a61a680-bcab-11ea-8754-940ced0c1a7a.png)

Team: 
Channel:
Body: Welcome.....

**Comment by rafasoaresmessias** [comment]
Solved, thanks @alexc-MSFT .
I created a new connection to Teams with service account.
