### ISSUE TITLE
Failure to deploy SPO site and lists

### ISSUE THREAD

**Issue by monkey-butler** [OfficeDev/microsoft-teams-apps-requestateam#78]
Apply-PnPProvisioningTemplate: C:\Users\fourb\Downloads\microsoft-teams-apps-requestateam-master\Deployment\Scripts\deploy.ps1:285
Line |
 285 |          Apply-PnPProvisioningTemplate -Path (Join-Path $packageRootPa …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The remote server returned an error: (400) Bad Request.

Applied template
Error occured while configuring the SharePoint site: Exception calling "ExecuteQuery" with "0" argument(s): "The remote server returned an error: (400) Bad Request."

**Comment by alexc-MSFT** [comment]
@monkey-butler please can you let me know the version of PnP PowerShell you are using please. Also when did you last get a copy of the code?

Thanks

**Comment by alexc-MSFT** [comment]
@monkey-butler  any updates please?

**Comment by monkey-butler** [comment]
Only just back onto this now sorry, I'm using 3.22.2006.2

Trying to manually create the list columns and the xml for Teams Templates fields #Baser Template Type, Base Template Id and Team Id are all missing 'Type' - are these supposed to be lookups to the templates list

**Comment by monkey-butler** [comment]
Using most recent copy of the code -timestamped July 22nd I believe

**Comment by monkey-butler** [comment]
Ignore the above - the 'Type' is there, just the lines in question are formatted in a different order

**Comment by monkey-butler** [comment]
thanks @alexc-MSFT , I'll try this later this week to see if it resolves my issues

**Comment by alexc-MSFT** [comment]
@monkey-butler I'm going to close this issue due to the length of time it's been open and the latest version should have solved this. Please open another issue if you still have this problem.
