### ISSUE TITLE
EMPTY "Team Name"

### ISSUE THREAD

**Issue by tekila747** [OfficeDev/microsoft-teams-apps-requestateam#79]
Hello,

I successfully deployed the solution, but when I tested it, "Team Name" is showing EMPTY: 
- in "Request a team" form > "Review and submit" step (step 4)
- in "My Requests" 
- in "Approve requests"

But the Team Name is showing correctly : 
- In the Adaptative Card
- In the Team created

Could you please help us for this issue
Thanks!

![image](https://user-images.githubusercontent.com/67380644/86376313-1a88c800-bc87-11ea-9b58-c7d0df9112f3.png)

![image](https://user-images.githubusercontent.com/67380644/86375408-e95bc800-bc85-11ea-878d-f514eec648ed.png)

![image](https://user-images.githubusercontent.com/67380644/86376646-9a169700-bc87-11ea-9803-6e13bf218cfc.png)

**Comment by lkanala** [comment]
Hi @tekila747, In My requests screen can you click on "lblTeamNameGallery_MyRequests" control and on "Text" property verify whether the formula is same as shown below.
![image](https://user-images.githubusercontent.com/64765970/86391525-cb26a580-bc4e-11ea-8c5b-15c50e41b467.png)
if it is not, please use this 
If(Len(ThisItem.'Team Name') > 35,Concatenate(Left(ThisItem.'Team Name',35),"..."),ThisItem.'Team Name')

Same with approve requests screen click on lblTeamNameGallery_ApproveRequests and verify.
In scrnBuildNew , in "frmReviewAndSubmit." click on "cardTeamName_ReviewAndSubmit." check Default property is set to ThisItem.'Team Name'  and "dcvTeamName_ReviewAndSubmit." is Default property is Parent.Default

![image](https://user-images.githubusercontent.com/64765970/86392455-594f5b80-bc50-11ea-8404-355cbd8a7af6.png)

same with scrnUseTemplate in "frmReviewAndSubmit" click on "cardTeamName_ReviewAndSubmit" check Default property is set to ThisItem.'Team Name'  and "dcvTeamName_ReviewAndSubmit" is Default property is Parent.Default

Please let us know if this helped and also please let us know what was in those formula bars if the formula is distorted. It will help us to investigate why this happened.
Thanks.

**Comment by tekila747** [comment]
Hello,

Thank you @lkanala lkanala  for your quick reply.

A global comment :It seems like ThisItem.'Team Name' is not regognized.

There is some differences in the formula (some ; and , differences). 
this is my formula :
If(Len(ThisItem.'Team Name') > 35;Concatenate(Left(ThisItem.'Team Name';35);"...");ThisItem.'Team Name')

![image](https://user-images.githubusercontent.com/67380644/86478799-35bd0b80-bd4b-11ea-9c7c-d90a01550b32.png)

I also tried your formula,  I also have a problem: 

![image](https://user-images.githubusercontent.com/67380644/86479218-08249200-bd4c-11ea-9071-7a117ee79a8a.png)

I tried to replace by ThisItem.'Team Name' --> it is not regognized : (error : utilisation non valide de "." ):
![image](https://user-images.githubusercontent.com/67380644/86479023-a06e4700-bd4b-11ea-901c-f37dc79ea195.png)


In scrnBuildNew > "frmReviewAndSubmit." > "cardTeamName_ReviewAndSubmit."> I have this text : 42
![image](https://user-images.githubusercontent.com/67380644/86479862-35be0b00-bd4d-11ea-896f-27eebca21e73.png)

I replaced by ThisItem.'Team Name' > not recognized (auto completion only recognize : ThisItem.'Team Alias' , ThisItem.'Team Description', ThisItem.'Team Purpose and Content', ThisItem.'Team URL'
![image](https://user-images.githubusercontent.com/67380644/86480639-add90080-bd4e-11ea-808d-63f559ca42ef.png)


Generally I have errors in different formulas (I have a lot of red marks in different screens):

![image](https://user-images.githubusercontent.com/67380644/86479445-7a957200-bd4c-11ea-9a7c-9d8f84112209.png)

![image](https://user-images.githubusercontent.com/67380644/86479460-841eda00-bd4c-11ea-9358-af631aed3287.png)

![image](https://user-images.githubusercontent.com/67380644/86479484-8c771500-bd4c-11ea-9dc4-a17c32019041.png)

![image](https://user-images.githubusercontent.com/67380644/86479513-9bf65e00-bd4c-11ea-8c61-9dcb5a1ec5d4.png)


Thanks,

**Comment by tekila747** [comment]
Hello,

I solved the problem : I corrected the data source team name column title:

Old Value : Title
New value : Team Name

it's working like a charm now!

![image](https://user-images.githubusercontent.com/67380644/86484242-1677ab80-bd56-11ea-92d8-e5c2586ef163.png)

![image](https://user-images.githubusercontent.com/67380644/86484378-635b8200-bd56-11ea-9e54-f8bc35690644.png)

**Comment by alexc-MSFT** [comment]
@tekila747 did you receive any errors running the deployment script by the way? We are currently investigating an issue where the Title column is not being renamed to 'Team Name'. Thanks

**Comment by tekila747** [comment]
@alexc-MSFT no errors for deployment script.
By the way, this was the second deployment (I deleted all dependencies before this second deployment : delete sharepoint site, etc.). I don't think that this can impact column title...

**Comment by alexc-MSFT** [comment]
@tekila747 glad to hear you are up and running, I will close this issue for now. Please re-raise if you experience any more problems.

Thanks
