### ISSUE TITLE
Logic App Error 

### ISSUE THREAD

**Issue by oggiejnr** [OfficeDev/microsoft-teams-apps-requestateam#8]
![Annotation 2020-05-05 082652](https://user-images.githubusercontent.com/64775251/81019598-56cbc200-8eaa-11ea-90d9-4fa637ca9bd5.png)

Get the following when the Logic App is attempting to trigger
Swagger not found for connector '/subscriptions/2ebbbbd3-8a21-489d-910b-1cec4818f6d3/providers/Microsoft.Web/locations/Australia Southeast/managedApis/sharepointonline'

**Comment by lkanala** [comment]
> ![Annotation 2020-05-05 082652](https://user-images.githubusercontent.com/64775251/81019598-56cbc200-8eaa-11ea-90d9-4fa637ca9bd5.png)
> 
> Get the following when the Logic App is attempting to trigger
> Swagger not found for connector '/subscriptions/2ebbbbd3-8a21-489d-910b-1cec4818f6d3/providers/Microsoft.Web/locations/Australia Southeast/managedApis/sharepointonline'

Can you check the status of all API connections inside resource group is connected or not.
![image](https://user-images.githubusercontent.com/64765970/81120971-9adab900-8ee2-11ea-8aee-b1f2ed9be297.png)
If not try to authenticate again by clicking on Edit API connection and by providing service account credentials.

**Comment by oggiejnr** [comment]
They are all saying connected.

**Comment by diver7** [comment]
I'm getting the same error. All 5 of the API connections show the blue "Authorize" bar and I can click on it and login with the service account and save but when I go back to the API connection again it still shows the blue "Authorize" bar like it didn't save.

**Comment by alexc-MSFT** [comment]
> I'm getting the same error. All 5 of the API connections show the blue "Authorize" bar and I can click on it and login with the service account and save but when I go back to the API connection again it still shows the blue "Authorize" bar like it didn't save.
> ![image](https://user-images.githubusercontent.com/18582794/81303736-b6a8a100-9041-11ea-9fd1-504abf680c06.png)

Just out of interest, is the user you are authorising the connections with, a Global Admin?

**Comment by alexc-MSFT** [comment]
> They are all saying connected.

Can you open up the logic app and manually change the connection of the 'When an item is created or modified' connection? One option as a quick fix, is to create a new connection for the SharePoint actions in the logic app.

I will investigate whether there is an issue with having the connections in this specific region. Also @diver7 what region are you using?

**Comment by diver7** [comment]
> > I'm getting the same error. All 5 of the API connections show the blue "Authorize" bar and I can click on it and login with the service account and save but when I go back to the API connection again it still shows the blue "Authorize" bar like it didn't save.
> > ![image](https://user-images.githubusercontent.com/18582794/81303736-b6a8a100-9041-11ea-9fd1-504abf680c06.png)
> 
> Just out of interest, is the user you are authorising the connections with, a Global Admin?

I am setting this up in a sandbox tenant. The service account I created is a global admin.

**Comment by alexc-MSFT** [comment]
> > > I'm getting the same error. All 5 of the API connections show the blue "Authorize" bar and I can click on it and login with the service account and save but when I go back to the API connection again it still shows the blue "Authorize" bar like it didn't save.
> > > ![image](https://user-images.githubusercontent.com/18582794/81303736-b6a8a100-9041-11ea-9fd1-504abf680c06.png)
> > 
> > 
> > Just out of interest, is the user you are authorising the connections with, a Global Admin?
> 
> I am setting this up in a sandbox tenant. The service account I created is a global admin.

Thanks - what Azure region did you use when running the script?

**Comment by diver7** [comment]
> > They are all saying connected.
> 
> Can you open up the logic app and manually change the connection of the 'When an item is created or modified' connection? One option as a quick fix, is to create a new connection for the SharePoint actions in the logic app.
> 
> I will investigate whether there is an issue with having the connections in this specific region. Also @diver7 what region are you using?

I am using the North Central US region. When I ran the deploy script and it asked for "Location" I entered "North Central US" instead of "northcentralus" which I think is the internal name. Could that be the issue?

**Comment by alexc-MSFT** [comment]
> > > They are all saying connected.
> > 
> > 
> > Can you open up the logic app and manually change the connection of the 'When an item is created or modified' connection? One option as a quick fix, is to create a new connection for the SharePoint actions in the logic app.
> > I will investigate whether there is an issue with having the connections in this specific region. Also @diver7 what region are you using?
> 
> I am using the North Central US region. When I ran the deploy script and it asked for "Location" I entered "North Central US" instead of "northcentralus" which I think is the internal name. Could that be the issue?

Potentially - I'll do some testing and report back ASAP.

**Comment by diver7** [comment]
> > > > They are all saying connected.
> > > 
> > > 
> > > Can you open up the logic app and manually change the connection of the 'When an item is created or modified' connection? One option as a quick fix, is to create a new connection for the SharePoint actions in the logic app.
> > > I will investigate whether there is an issue with having the connections in this specific region. Also @diver7 what region are you using?
> > 
> > 
> > I am using the North Central US region. When I ran the deploy script and it asked for "Location" I entered "North Central US" instead of "northcentralus" which I think is the internal name. Could that be the issue?
> 
> Potentially - I'll do some testing and report back ASAP.

Looks like any action that has a connection is showing the same error. So it's not just SharePoint. The URL in the error also shows the location like I mentioned above.

**Comment by alexc-MSFT** [comment]
> > > > > They are all saying connected.
> > > > 
> > > > 
> > > > Can you open up the logic app and manually change the connection of the 'When an item is created or modified' connection? One option as a quick fix, is to create a new connection for the SharePoint actions in the logic app.
> > > > I will investigate whether there is an issue with having the connections in this specific region. Also @diver7 what region are you using?
> > > 
> > > 
> > > I am using the North Central US region. When I ran the deploy script and it asked for "Location" I entered "North Central US" instead of "northcentralus" which I think is the internal name. Could that be the issue?
> > 
> > 
> > Potentially - I'll do some testing and report back ASAP.
> 
> Looks like any action that has a connection is showing the same error. So it's not just SharePoint. The URL in the error also shows the location like I mentioned above.
> ![image](https://user-images.githubusercontent.com/18582794/81313150-18223d00-904d-11ea-81cd-7569dc08b65f.png)

I've just found the same thing when doing some testing. I have a few ideas so will report back.

**Comment by alexc-MSFT** [comment]
@oggiejnr @diver7 ok it's because the location name you are providing has a space in it i.e. it's the display name not the internal name, so Australia Southeast should be 'australiasoutheast'.

I'll make an update to the code shortly to try to automatically fix this but in the meantime if you could please re-try, the connections should then be fine.

**Comment by diver7** [comment]
> @oggiejnr @diver7 ok it's because the location name you are providing has a space in it i.e. it's the display name not the internal name, so Australia Southeast should be 'australiasoutheast'.
> 
> I'll make an update to the code shortly to try to automatically fix this but in the meantime if you could please re-try, the connections should then be fine.

@alexc-MSFT what do you mean by "re-try"? I've been looking for a way to edit the API connections and change the location but I can't find any way to do it.

**Comment by diver7** [comment]
> > @oggiejnr @diver7 ok it's because the location name you are providing has a space in it i.e. it's the display name not the internal name, so Australia Southeast should be 'australiasoutheast'.
> > I'll make an update to the code shortly to try to automatically fix this but in the meantime if you could please re-try, the connections should then be fine.
> 
> @alexc-MSFT what do you mean by "re-try"? I've been looking for a way to edit the API connections and change the location but I can't find any way to do it.

@alexc-MSFT I figured out how to edit the API connections by going to the "Logic app code view" in the designer and changing the text in the connections. Thanks for all your help on this and being so very quick with the help!!

**Comment by ChristianHoffmannn** [comment]
Hello together,
i am writing here, because in a customer tenant we are having the same error like in this issue.
I read through this issue and i thought this error has been fixed?

I used the request a team app version from the deployment guide, where i thought that this would be the current version of the app.

Anyone know how to fix this error?

Kind regards

Christian

**Comment by alexc-MSFT** [comment]
@ChristianHoffmannn So sorry for the delay in coming back to you. Sadly I do not get as much time to devote to Request-a-team these days.

I can confirm that this issue is caused by the location name being entered with spaces when running the script e.g. 'UK South' instead of 'uksouth'.

You can fix it by editing the Logic Apps in code view, scrolling to the bottom and updating each id and connectionid line with the connections array.

I'll look at the above pull request for the deployment page so we can clearly point this out and in future we'll make a script fix.

Thanks
