### ISSUE TITLE
[Evolution Proposal] Adding PREFIX and SUFFIX to Team Name

### ISSUE THREAD

**Issue by tekila747** [OfficeDev/microsoft-teams-apps-requestateam#80]
Hello, 

Is it possible to add the possibility  to enforce PREFIX and SUFFIX to "Team Name" with some templates (each template have PREFIX and SUFFIX that can be defined by Admins)

Option 1 : This can be a defined string (example : "SALES-Tokyo Event", "Tokyo Event - SALES")
Option 2 : Or this can be a Dynamic text (for example extracted from user profile properties > Location > "FR-Tokyo Event")

Thanks!

**Comment by alexc-MSFT** [comment]
Thanks @tekila747 for the suggestion, this is one piece of functionality that we are looking into.

Thanks

**Comment by tekila747** [comment]
Thanks!

**Comment by tekila747** [comment]
Thanks!

**Comment by alexc-MSFT** [comment]
@tekila747 this is now on our roadmap for release. I will link to the roadmap item and close the issue. #174
