### ISSUE TITLE
Need more information on licences to be enable on Service Account used by Logic App

### ISSUE THREAD

**Issue by aravindmunna** [OfficeDev/microsoft-teams-apps-requestateam#81]
Does this service account also needs to have an exchange licence enabled ? Or Just enable only MS Teams License as mentioned in the documentation.

**Comment by FritsH** [comment]
My Team creation failed when there was no valid email address connected to the service account, it returned a NULL value when adding the owners and members as the email address field was empty. I've added a exchange license so there's an mailbox attached to this account. All emails when the teams are created are sent using the service account. 
As is my understanding after testing, I'm not the creator of this app, just a happy user.

**Comment by aravindmunna** [comment]
I too had same issue , it returned null when i assigned only teams license to the service account, But when i enabled exchange license it worked. But documentation only says "**Service account is nothing but an Office 365 user who has Teams licenses enabled** "

**Comment by lkanala** [comment]
Hi @aravindmunna, @FritsH , The minimum license required for the service account is E3. Since there are some tenant's which follows A1, A2 etc, we mentioned Teams License enabled which covers basic requirements like having access to Teams and SharePoint online.

**Comment by aravindmunna** [comment]
> Hi @aravindmunna, @FritsH , The minimum license required for the service account is E3. Since there are some tenant's which follows A1, A2 etc, we mentioned Teams License enabled(to make it simple for user) which covers basic requirements like having access to Teams, SharePoint Online and Exchange. Thanks for your feedback, we will look into it.

Thank You.

**Comment by alexc-MSFT** [comment]
@aravindmunna @FritsH the Service Account requires SPO, Teams and Exchange licenses. It also requires an EXO mailbox. This is because it connects to SPO, Teams and Exchange in the Logic App. The emails are also sent from the Service Account. I have updated the documentation accordingly and will now close this issue.

**Comment by aravindmunna** [comment]
@alexc-MSFT  Sure, You can close.  Thank you.. I appreciate your clear explanation on this. Now i hope it help others as well.
