### ISSUE TITLE
Unable to process template language expressions in action 'Set_SiteExists_variable' inputs at line '1' and column '3845': 'The template language function 'bool' was invoked with a parameter that is not valid. The value cannot be converted to the target type.'

### ISSUE THREAD

**Issue by sneranacdw** [OfficeDev/microsoft-teams-apps-requestateam#84]
I am getting this error in Logic Apps Designer in Portal.azure.com. This happens towards very end when the actual Teams need to get created using the flow

**Comment by alexc-MSFT** [comment]
@sneranacdw please can you have a look at the output of the CheckSiteExists runbook in Azure Automation please. Specifically the 'All Logs' section and let me know what you see. I suspect its an issue with the app secret not being correct, this was a known issue and there is a pull request in to fix. Did you run the deployment script more than once?

**Comment by sneranacdw** [comment]
I ran the deployment script only once. I will provide you with the output of the CheckSiteExists shortly

**Comment by alexc-MSFT** [comment]
@sneranacdw any update on this please?

**Comment by sneranacdw** [comment]
My apologies on delayed response. I was able to resolve this issue with MS Support. We can close this thread.

**Comment by ARAlmac** [comment]
@alexc-MSFT Would you have a fix for this? has started happening in our azure logic app. Set_SiteExists_Variable is getting false in first step but then after check site exists job output step it is receiving this error:
![image](https://user-images.githubusercontent.com/32670540/91556007-ebf73880-e929-11ea-9570-e687543d4e76.png)

Thanks
