### ISSUE TITLE
Items displaying on "Go to Start" window, even though I have "TeamInformation" set as Visibility option

### ISSUE THREAD

**Issue by ARAlmac** [OfficeDev/microsoft-teams-apps-requestateam#87]
Hi, 
I was wondering if i would be able to get some help with this.
I've added a Drop down list, a Text input and radio button options to the "Teams information" screen on both the Template and the Build new screens. I found out that to determine which elements show on which screen they all have different visibility groups. I added the corresponding Visibility options to my items and it displays okay.

The only issue im having is that when I am on the Team Information screen and click the "Go to Start" options, then the elements I have added are displaying over the black rectangle and beside the Popup message:
<img width="411" alt="Request-A-team_VisibilityError" src="https://user-images.githubusercontent.com/32670540/86921597-4b537c00-c123-11ea-897b-6cb44f118e79.PNG">

It may be something simple i am missing, but i have ensured all items on the screen have the same Visibility option so I am not sure what the difference is ? 

Any help would be great, Thanks!

**Comment by alexc-MSFT** [comment]
@ARAlmac it is likely that the two controls you have added are in front of the overlay control. You would need to amend the overlay and bring it to the front by right clicking on it. This would place it in front. Hope that helps.

**Comment by alexc-MSFT** [comment]
@ARAlmac  as this is not an issue with the template I'm going to be closing this issue. I would encourage reading up on Power Apps, we have some great documentation out there. This will arm you with the skills you need to customise the app.

Thanks
