### ISSUE TITLE
Separate Tenants for Office 365 and Azure

### ISSUE THREAD

**Issue by flash265** [OfficeDev/microsoft-teams-apps-requestateam#88]
Our Azure tenant where we have our billed subscription is not connected to our O365/AAD tenant. Is there a way to install the solution on seperate Azure and O365 tenants? Thanks

**Comment by tekila747** [comment]
Hello,

This is mentioned in deployment guide: [https://github.com/OfficeDev/microsoft-teams-apps-requestateam/wiki/Deployment-guide ](url)

"SubscriptionId - Azure subscription to deploy the solution to (MUST be associated with the Azure AD of the Office 365 tenant that you wish to deploy this solution to.)"
So I think this is not possible

From my side, I also tried several installations with separtae tenants, but all failed.

Regards,

**Comment by alexc-MSFT** [comment]
@flash265 as @tekila747  says above, sadly you cannot use this in separate tenants. I'll research if this might be possible in a future update.
