### ISSUE TITLE
Issue when adding owners and members

### ISSUE THREAD

**Issue by ruben1980** [OfficeDev/microsoft-teams-apps-requestateam#90]
in the process where I can add owners and members I get the message that owners cannot be the same as members, while I have selected another account. The owner and member fields also remain empty in the confirmation screen.

**Comment by ruben1980** [comment]
I receive this message:

The requested operation is invalid. Server Response: Teams Requests Failed: Could the specified user be i: 0 # .f | membership | fail to find. clientRequestId: dca508be-b184-432b-96b6-831452165935 serviceRequestId: dca508be-b184-432b-96b6-831452165935

**Comment by aravindmunna** [comment]
@ruben1980  I also faced the same issue when i was testing with some newly created test users in the tenant without exchange licence enabled.

It got fixed when i, provisioned exchange licences for test users in the tenant.

**Comment by alexc-MSFT** [comment]
@ruben1980 is your Service Account also the account you are adding as an Owner of the team?

**Comment by ruben1980** [comment]
Perfect, that was the problem! I have now tested it with full licensed users and it worked well

**Comment by aravindmunna** [comment]
@ruben1980  Good to hear.. ! User With Licences (SharePoint, Exchange ,Ms Teams )and obviously with Power App if needed works well.
