### ISSUE TITLE
M365 groups creation should be disabled?

### ISSUE THREAD

**Issue by mcasaz** [OfficeDev/microsoft-teams-apps-requestateam#92]
Not really an issue, but I haven't found this in the documentation.
I am assuming that M365 Group creation needs to be disabled for all users? Otherwise users will still have the ability to create Teams using the standard option in Teams (Join or create a team)
Is this correct?

**Comment by alexc-MSFT** [comment]
@mcasaz correct, this solution assumes that you would disable/restrict group creation across your tenant, this will stop users being able to create Teams through the client.

Thanks
