### ISSUE TITLE
deploy.ps1 link not valid in Deployment Guide Wiki

### ISSUE THREAD

**Issue by harp365** [OfficeDev/microsoft-teams-apps-requestateam#93]
I was looking for a way to make a pull request against the Wiki but couldn't see how. I believe it needs changing to be that of: https://github.com/OfficeDev/microsoft-teams-apps-requestateam/blob/master/Deployment/Scripts/deploy.ps1

It is currently set to:

https://github.com/OfficeDev/microsoft-teams-apps-requestateam/master/blob/Deployment/deploy.ps1

No biggie as it does exist within the repository but just thought I would give you a nudge :)

Thanks

Henry

**Comment by alexc-MSFT** [comment]
@harp365 thanks for highlighting this, I've amended the Deployment Guide wiki page accordingly.

Thanks
