### ISSUE TITLE
No subscription found

### ISSUE THREAD

**Issue by LeighMichell** [OfficeDev/microsoft-teams-apps-requestateam#96]
Hi 

Can you help please.  The script is failing as it is saying that my tenant doesn't contain accessible subscriptions.  I've taken out a trail Azure licence could that be the issue?

Launching Azure CLI sign-in...
You have logged in. Now let us find all the subscriptions to which you have access...
The following tenants don't contain accessible subscriptions. Use 'az login --allow-no-subscriptions' to have tenant level access.
xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
The following tenants require Multi-Factor Authentication (MFA). Use 'az login --tenant TENANT_ID' to explicitly login to a tenant.
xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
No subscriptions found.

Any help would be appreciated.

Kind regards

Leigh

**Comment by loflet** [comment]
Hi @LeighMichell, on Azure Portal (UI) can you see any azure subscription attached to your tenant? You can check this by visiting https://portal.azure.com/#blade/Microsoft_Azure_Billing/SubscriptionsBlade 
For the deployment script to work, your azure account should have subscription attached to it.

Kind regards,
Sanket

**Comment by LeighMichell** [comment]
Hi Sanket

Yes I can see the Subscription name and the Free Trial with the subscription id.

Kind regards

Leigh

**Comment by alexc-MSFT** [comment]
@LeighMichell this must be something to do with MFA and possibly something we can fix in the script. 

Please can you edit the deploy.ps1 script and replace line 830 with this:

az login --tenant $TenantId

And re-run the script and let me know what happens please.

Thanks

**Comment by LeighMichell** [comment]
Hi Alex

I changed the script and that let me get a bit further on in the process but I am now getting an error saying the teamsgovernanceapp-rg was not found.  I also get a blank pop up window, which I've attached a screenshot of.  I've also attached the script with the error messages.

![teams app blank screen](https://user-images.githubusercontent.com/67949463/89999178-5a7b9b80-dc86-11ea-87ed-fa96ea664267.png)

[powershell script new teams request take 2.txt](https://github.com/OfficeDev/microsoft-teams-apps-requestateam/files/5061777/powershell.script.new.teams.request.take.2.txt)

Kind regards

Leigh

**Comment by LeighMichell** [comment]
Hi, 

Can anyone help please?

Kind regards

Leigh

**Comment by alexc-MSFT** [comment]
@LeighMichell are you still experiencing this issue?

**Comment by alexc-MSFT** [comment]
Closed due to inactivity - reopen if required
