### ISSUE TITLE
property 'keyvault_' doesn't exist

### ISSUE THREAD

**Issue by shuenSL** [OfficeDev/microsoft-teams-apps-requestateam#99]
Encountered the following runtime error in the logic flow Get Client Secret step.

>> InvalidTemplate. Unable to process template language expressions in action 'Get_Client_Secret' inputs at line '1' and column '4084': 'The template language expression 'parameters('$connections')['keyvault_']['connectionId']' cannot be evaluated because property 'keyvault_' doesn't exist, available properties are 'azureautomation, keyvault, office365, office365users, sharepointonline, teams'. Please see https://aka.ms/logicexpressions for usage details.'. >>

In processteamrequestbeta.json line 1585, the "**keyvault_**" should be without the underscore at the end. 

                            "type": "ApiConnection",
                            "inputs": {
                                "host": {
                                    "connection": {
                                        "name": "@parameters('$connections')['keyvault_']['connectionId']"
                                    }
                                },
                                "method": "get",
                                "path": "/secrets/@{encodeURIComponent('appsecret')}/value"
                            },

**Comment by alexc-MSFT** [comment]
@shuenSL good spot, I've created a PR to fix this.
